#!/bin/bash
# Generated by flowsh v1.0.0
# Source: Simple Agent Workflow
# Description: Basic example of agent orchestration
# Version: 1.0.0
# Generated: 2026-01-02T00:54:58.847Z

set -euo pipefail

# =============================================================================
# WORKFLOW CONFIGURATION
# =============================================================================

# Workflow variables
declare -A workflow_vars
declare -A workflow_state

# Control flags for testing and configuration
USE_MOCK_TOOLS=${USE_MOCK_TOOLS:-true}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}
VERBOSE=${VERBOSE:-false}
WORKFLOW_NAME="Simple Agent Workflow"
WORKFLOW_VERSION="1.0.0"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# =============================================================================
# MOCK FUNCTIONS FOR TESTING
# =============================================================================

# Mock opencode command for testing
mock_opencode() {
    local prompt="$1"
    log_info "Mock opencode called with prompt:"
    echo "---"
    echo "${prompt:0:200}..." # Show first 200 chars
    echo "---"
    
    # Simulate some processing time
    sleep 2
    
    log_success "Mock agent completed task successfully"
    return 0
}

# Mock LLM call for testing  
mock_llm() {
    local prompt="$1"
    local model="${2:-gpt-4}"
    
    log_info "Mock LLM ($model) called with prompt:"
    echo "---"
    echo "${prompt:0:200}..." # Show first 200 chars
    echo "---"
    
    # Simulate processing time based on model
    case "$model" in
        *"gpt-4"*) sleep 3 ;;
        *"claude"*) sleep 2 ;;
        *) sleep 1 ;;
    esac
    
    log_success "Mock LLM response generated"
    echo "This is a mock response from $model. In a real implementation, this would be the actual LLM output."
    return 0
}

# Mock command execution
mock_command() {
    local command="$1"
    shift
    local args=("$@")
    
    log_info "Mock command: $command ${args[*]}"
    
    case "$command" in
        "make")
            case "${args[0]:-}" in
                "test")
                    log_info "Running tests..."
                    sleep 1
                    log_success "All tests passed"
                    return 0
                    ;;
                "build")
                    log_info "Building project..."
                    sleep 2
                    log_success "Build completed"
                    return 0
                    ;;
                *)
                    log_error "Unknown make target: ${args[0]:-}"
                    return 1
                    ;;
            esac
            ;;
        "npm"|"yarn"|"pnpm")
            log_info "Running package manager command..."
            sleep 1
            log_success "Package manager command completed"
            return 0
            ;;
        "git")
            log_info "Running git command..."
            sleep 1
            log_success "Git command completed"
            return 0
            ;;
        *)
            log_info "Running generic command: $command"
            sleep 1
            log_success "Command completed"
            return 0
            ;;
    esac
}

# =============================================================================
# TEMPLATE SYSTEM
# =============================================================================

# Template resolution with fallback system
resolve_template() {
    local template_id="$1"
    local source="${2:-library}"
    
    log_debug "Resolving template: $template_id from $source"
    
    case "$template_id" in
        "task-planner")
            cat <<'TEMPLATE'
You are a task planner. Break down this task: {{task_description}}

Create actionable steps and implement them systematically.
Focus on:
1. Understanding requirements
2. Breaking down into subtasks  
3. Implementation planning
4. Testing strategy

Keep your response concise and actionable.
TEMPLATE
            ;;
        "code-reviewer")
            cat <<'TEMPLATE'
Review and analyze this task: {{task_description}}

Provide feedback on:
1. Code quality and best practices
2. Potential security issues
3. Performance considerations
4. Testing coverage
TEMPLATE
            ;;
        *)
            log_error "Unknown template '$template_id'"
            return 1
            ;;
    esac
}

# Template rendering with variable substitution
render_template() {
    local template="$1"
    local task_description="$2"
    
    # Validate inputs
    [[ -z "$template" ]] && {
        log_error "Template content is empty"
        return 1
    }
    [[ -z "$task_description" ]] && {
        log_error "Task description is empty"
        return 1
    }
    
    # Use the variable substitution function
    local rendered_template="$(substitute_variables "$template")"
    
    # Handle specific variable substitutions for backward compatibility
    rendered_template=$(echo "$rendered_template" | sed "s|{{task_description}}|$task_description|g")
    
    echo "$rendered_template"
}

# =============================================================================

# NODE EXECUTION FUNCTIONS

# =============================================================================

# Execute start node: start
execute_node_start() {
    log_step "Starting workflow: Start"
    
    # Validate required variables
    
    log_success "Workflow initialized successfully"
    set_workflow_state "current_node" "start"
}

# Execute agent node: agent_task
execute_node_agent_task() {
    log_step "🤖 Running Agent: Execute Task"
    
    local agent_exit_code=0
    local command="opencode"
    
    # Resolve and render template if provided
    local prompt=""
    if [[ -n "" ]]; then
        local template_content
        if ! template_content=$(resolve_template "" "inline"); then
            log_error "Failed to resolve template ''"
            return 1
        fi
        
        if ! prompt=$(render_template "$template_content" "$(get_workflow_var 'task_description' '')"); then
            log_error "Failed to render template"
            return 1
        fi
    else
        prompt="$(get_workflow_var 'task_description' 'Default task')"
    fi
    
    log_debug "Generated prompt length: ${#prompt} characters"
    
    # Execute agent command with proper error handling
    if [[ "$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock $command"
        mock_opencode "$prompt" || agent_exit_code=$?
    elif command -v "$command" >/dev/null 2>&1; then
        log_debug "Using real $command with timeout ${AGENT_TIMEOUT}s"
        
        timeout "$AGENT_TIMEOUT" "$command" "run" "$prompt" || agent_exit_code=$?
        
        # Handle timeout gracefully
        if [[ $agent_exit_code -eq 124 ]]; then
            log_error "$command timed out after ${AGENT_TIMEOUT}s, falling back to mock"
            mock_opencode "$prompt" || agent_exit_code=$?
        fi
    else
        log_info "$command not found, falling back to mock"
        mock_opencode "$prompt" || agent_exit_code=$?
    fi
    
    if [[ $agent_exit_code -ne 0 ]]; then
        handle_error $agent_exit_code "Agent execution" "agent_task"
        return $agent_exit_code
    fi
    
    log_success "Agent completed successfully"
    set_workflow_state "current_node" "agent_task"
}

# Execute answer node: result
execute_node_result() {
    log_step "📤 Providing Answer: Result"
    
    local answer_text="Task completed successfully"
    local final_answer
    final_answer=$(substitute_variables "$answer_text")
    
    echo "=========================="
    echo "WORKFLOW RESULT"
    echo "=========================="
    echo "$final_answer"
    echo "=========================="
    
    log_success "Workflow completed successfully"
    set_workflow_state "current_node" "result"
    set_workflow_state "completed" "true"
}

# =============================================================================
# MAIN EXECUTION FLOW
# =============================================================================

# Execute the workflow
execute_workflow() {
    log_info "Starting workflow execution: $WORKFLOW_NAME"
    log_info "Nodes: 3, Edges: 2"
    
    execute_node_start
    execute_node_agent_task
    execute_node_result

    
    local completion_status=$(get_workflow_state "completed" "false")
    if [[ "$completion_status" == "true" ]]; then
        log_success "Workflow completed successfully"
    else
        log_warning "Workflow execution finished but completion status unclear"
    fi
}

# =============================================================================
# ARGUMENT PARSING AND INITIALIZATION
# =============================================================================

# Usage help
show_usage() {
    cat <<EOF
$WORKFLOW_NAME v$WORKFLOW_VERSION

Usage: $0 [OPTIONS] <arg1>

Arguments:
  arg1    Task Description - What you want the agent to do
Options:
  --no-mock         Use real tools instead of mocks
  --timeout SECS    Set agent timeout in seconds (default: $AGENT_TIMEOUT)
  --verbose         Enable verbose debug output
  --help            Show this help message

Environment Variables:
  USE_MOCK_TOOLS    Set to 'false' to use real tools (default: true)
  AGENT_TIMEOUT     Agent timeout in seconds (default: 60)
  VERBOSE           Set to 'true' for debug output (default: false)

Examples:
  $0 "Implement user auth" /path/to/project
  $0 --no-mock --verbose "Fix bug in API" /path/to/project
EOF
}

# Initialize workflow with arguments
init_workflow() {
    workflow_vars["task_description"]="${1:-}"

    
    # Validate required arguments
    [[ -z "${workflow_vars["task_description"]}" ]] && {
        log_error "task_description is required"
        show_usage
        exit 1
    }
    
    log_success "Workflow initialized with provided arguments"
    log_debug "task_description: ${workflow_vars["task_description"]}"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-mock)
            USE_MOCK_TOOLS=false
            shift
            ;;
        --timeout)
            [[ -n "${2:-}" ]] || {
                log_error "--timeout requires a value"
                exit 1
            }
            [[ "$2" =~ ^[0-9]+$ ]] || {
                log_error "Timeout must be a positive integer"
                exit 1
            }
            AGENT_TIMEOUT="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        -*)
            log_error "Unknown option: $1"
            show_usage >&2
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

# =============================================================================
# MAIN EXECUTION
# =============================================================================

# Health check function
health_check() {
    log_info "Running system health check..."
    
    # Check required commands based on mode
    if [[ "$USE_MOCK_TOOLS" != "true" ]]; then
        local missing_tools=()
        
        command -v opencode >/dev/null 2>&1 || missing_tools+=("opencode")
        
        if [[ ${#missing_tools[@]} -gt 0 ]]; then
            log_info "Missing tools (will use mocks): ${missing_tools[*]}"
        else
            log_success "All required tools available"
        fi
    else
        log_info "Running in mock mode - no external tools required"
    fi
}

# Main function
main() {
    health_check
    init_workflow "$@"
    execute_workflow
}

# Run if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi