#!/bin/bash
# Generated by flowsh v1.0.0
# Source: Simple Agent Workflow
# Description: Basic example of agent orchestration
# Version: 1.0.0
# Generated: 2026-01-02T15:42:28.300Z

set -euo pipefail

# =============================================================================
# WORKFLOW CONFIGURATION
# =============================================================================

# Workflow variables
declare -A workflow_vars
declare -A workflow_state

# Control flags for testing and configuration
USE_MOCK_TOOLS=${USE_MOCK_TOOLS:-true}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}
VERBOSE=${VERBOSE:-false}
WORKFLOW_NAME="Simple Agent Workflow"
WORKFLOW_VERSION="1.0.0"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# =============================================================================
# MOCK FUNCTIONS FOR TESTING
# =============================================================================

# Mock opencode command for testing
mock_opencode() {
    local prompt="$1"
    log_info "Mock opencode called with prompt:"
    echo "---"
    echo "${prompt:0:200}..." # Show first 200 chars
    echo "---"
    
    # Simulate some processing time
    sleep 2
    
    log_success "Mock agent completed task successfully"
    return 0
}

# Mock LLM call for testing  
mock_llm() {
    local prompt="$1"
    local model="${2:-gpt-4}"
    
    log_info "Mock LLM ($model) called with prompt:"
    echo "---"
    echo "${prompt:0:200}..." # Show first 200 chars
    echo "---"
    
    # Simulate processing time based on model
    case "$model" in
        *"gpt-4"*) sleep 3 ;;
        *"claude"*) sleep 2 ;;
        *) sleep 1 ;;
    esac
    
    log_success "Mock LLM response generated"
    echo "This is a mock response from $model. In a real implementation, this would be the actual LLM output."
    return 0
}

# Mock command execution
mock_command() {
    local command="$1"
    shift
    local args=("$@")
    
    log_info "Mock command: $command ${args[*]}"
    
    case "$command" in
        "make")
            case "${args[0]:-}" in
                "test")
                    log_info "Running tests..."
                    sleep 1
                    log_success "All tests passed"
                    return 0
                    ;;
                "build")
                    log_info "Building project..."
                    sleep 2
                    log_success "Build completed"
                    return 0
                    ;;
                *)
                    log_error "Unknown make target: ${args[0]:-}"
                    return 1
                    ;;
            esac
            ;;
        "npm"|"yarn"|"pnpm")
            log_info "Running package manager command..."
            sleep 1
            log_success "Package manager command completed"
            return 0
            ;;
        "git")
            log_info "Running git command..."
            sleep 1
            log_success "Git command completed"
            return 0
            ;;
        *)
            log_info "Running generic command: $command"
            sleep 1
            log_success "Command completed"
            return 0
            ;;
    esac
}

# =============================================================================
# TEMPLATE SYSTEM
# =============================================================================

# Template cache directory
TEMPLATE_CACHE_DIR="${FLOWSH_TEMP_DIR:-/tmp/flowsh}/templates"
mkdir -p "$TEMPLATE_CACHE_DIR"

# Template resolution with comprehensive source support
resolve_template() {
    local template_id="$1"
    local version="${2:-latest}"
    local cache_key="${template_id}:${version}"
    local cache_file="$TEMPLATE_CACHE_DIR/$cache_key"

    log_debug "$correlation_id" "Resolving template: $template_id (version: $version)"

    # Check local cache first
    if [ -f "$cache_file" ]; then
        local cache_age=$(($(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || echo 0)))
        if [ $cache_age -lt 3600 ]; then
            log_debug "$correlation_id" "Template cache hit: $template_id"
            cat "$cache_file"
            return 0
        else
            log_debug "$correlation_id" "Template cache expired: $template_id"
            rm -f "$cache_file"
        fi
    fi

    # Try built-in templates first
    case "$template_id" in
        "task-planner")
            local content='You are a task planner. Break down this task: {{task_description}}

Create actionable steps and implement them systematically.
Focus on:
1. Understanding requirements
2. Breaking down into subtasks  
3. Implementation planning
4. Testing strategy

Keep your response concise and actionable.'
            echo "$content" > "$cache_file"
            echo "$content"
            return 0
            ;;
        "code-reviewer")
            local content='Review and analyze this task: {{task_description}}

Provide feedback on:
1. Code quality and best practices
2. Potential security issues
3. Performance considerations
4. Testing coverage'
            echo "$content" > "$cache_file"
            echo "$content"
            return 0
            ;;
    esac

    # Try external sources
    
    # Try source 1: file - ./templates
    log_debug "$correlation_id" "Attempting template resolution from file: ./templates"
    
    if resolve_from_file_source "$template_id" "$version" "./templates" > "$cache_file.tmp"; then
        if validate_template "$(cat "$cache_file.tmp")" "$template_id"; then
            mv "$cache_file.tmp" "$cache_file"
            cat "$cache_file"
            return 0
        else
            log_warning "$correlation_id" "Template validation failed from file source"
            rm -f "$cache_file.tmp"
        fi
    else
        log_debug "$correlation_id" "Failed to resolve from file source: ./templates"
        rm -f "$cache_file.tmp"
    fi

    # Try source 2: http - https://templates.flowsh.dev
    log_debug "$correlation_id" "Attempting template resolution from http: https://templates.flowsh.dev"
    
    if resolve_from_http_source "$template_id" "$version" "https://templates.flowsh.dev" > "$cache_file.tmp"; then
        if validate_template "$(cat "$cache_file.tmp")" "$template_id"; then
            mv "$cache_file.tmp" "$cache_file"
            cat "$cache_file"
            return 0
        else
            log_warning "$correlation_id" "Template validation failed from http source"
            rm -f "$cache_file.tmp"
        fi
    else
        log_debug "$correlation_id" "Failed to resolve from http source: https://templates.flowsh.dev"
        rm -f "$cache_file.tmp"
    fi

# Source resolution functions
resolve_from_http_source() {
    local template_id="$1"
    local version="$2" 
    local base_url="$3"
    local url="$base_url/templates/$template_id"
    
    if [ "$version" != "latest" ]; then
        url="$url?version=$version"
    fi
    
    curl -s --max-time 30 \
         -H "Accept: text/plain" \
         -H "User-Agent: flowsh-template-engine/1.0" \
         "$url" 2>/dev/null
}

resolve_from_file_source() {
    local template_id="$1"
    local version="$2"
    local base_path="$3"
    local file_path="$base_path/$template_id"
    
    if [ "$version" != "latest" ]; then
        file_path="$file_path.$version"
    fi
    
    if [ -f "$file_path" ]; then
        cat "$file_path"
        return 0
    fi
    
    return 1
}

resolve_from_git_source() {
    local template_id="$1"
    local version="$2"
    local repo_url="$3"
    
    # Git resolution not yet implemented
    log_warning "$correlation_id" "Git template resolution not implemented"
    return 1
}

resolve_from_registry_source() {
    local template_id="$1"
    local version="$2"
    local registry_url="$3"
    
    # Use HTTP resolution for registry
    resolve_from_http_source "$template_id" "$version" "$registry_url"
}

    # Handle fallback strategy
    case "default" in
        "error")
            log_error "$correlation_id" "Template not found: $template_id"
            return 1
            ;;
        "inline")
            log_warning "$correlation_id" "Using template ID as inline content: $template_id"
            echo "$template_id"
            ;;
        "default")
            log_warning "$correlation_id" "Using default template for: $template_id"
            local default_content="Default template content for $template_id: {{task_description}}"
            echo "$default_content" > "$cache_file"
            echo "$default_content"
            ;;
    esac
}

# Enhanced template rendering with comprehensive variable substitution
render_template() {
    local template="$1"
    local variables="$2"
    
    # Validate inputs
    if [ -z "$template" ]; then
        log_error "$correlation_id" "Template content is empty"
        return 1
    fi
    
    log_debug "$correlation_id" "Rendering template with variables"
    
    # Start with the template
    local rendered="$template"
    
    # Replace common workflow variables
    rendered=$(echo "$rendered" | sed "s|{{task_description}}|$(get_workflow_var 'task_description' 'Default task')|g")
    rendered=$(echo "$rendered" | sed "s|{{input_data}}|$variables|g")
    rendered=$(echo "$rendered" | sed "s|{{correlation_id}}|$correlation_id|g")
    rendered=$(echo "$rendered" | sed "s|{{timestamp}}|$(date -Iseconds)|g")
    
    # Apply variable substitution function for ${} patterns
    rendered=$(substitute_variables "$rendered" "$variables")
    
    echo "$rendered"
}

# Advanced variable substitution supporting nested and complex patterns
substitute_variables() {
    local content="$1"
    local input_data="$2"
    
    # Replace ${variable} patterns with workflow variables
    local result="$content"
    
    # Extract all variable references
    local vars=$(echo "$content" | grep -o '${[^}]*}' | sort -u)
    
    for var_ref in $vars; do
        # Remove ${} wrapper
        local var_name=$(echo "$var_ref" | sed 's/${\([^}]*\)}/\1/')
        
        # Get variable value
        local var_value=$(get_variable_value "$var_name" "$input_data")
        
        # Replace in result
        result=$(echo "$result" | sed "s|\${$var_name}|$var_value|g")
    done
    
    echo "$result"
}

# Get variable value from workflow state or input data
get_variable_value() {
    local var_name="$1"
    local input_data="$2"
    
    # Try workflow variable first
    local value=$(get_workflow_var "$var_name" "")
    
    if [ -n "$value" ]; then
        echo "$value"
        return 0
    fi
    
    # Try environment variable
    local env_value=$(eval "echo \$$var_name" 2>/dev/null || echo "")
    if [ -n "$env_value" ]; then
        echo "$env_value"
        return 0
    fi
    
    # Return empty string as fallback
    echo ""
}

# Validate template content
validate_template() {
    local template="$1"
    local template_id="$2"
    
    # Basic validation checks
    if [ -z "$template" ]; then
        log_error "$correlation_id" "Template validation failed: empty content" "{\"template_id\": \"$template_id\"}"
        return 1
    fi
    
    # Check for potentially dangerous content
    if echo "$template" | grep -q '$(.*rm.*-rf'; then
        log_error "$correlation_id" "Template validation failed: dangerous command detected" "{\"template_id\": \"$template_id\"}"
        return 1
    fi
    
    # Check template size (max 1MB)
    local template_size=${#template}
    if [ $template_size -gt 1048576 ]; then
        log_error "$correlation_id" "Template validation failed: size too large ($template_size bytes)" "{\"template_id\": \"$template_id\"}"
        return 1
    fi
    
    log_debug "$correlation_id" "Template validation passed: $template_id ($template_size bytes)"
    return 0
}

# =============================================================================

# NODE EXECUTION FUNCTIONS

# =============================================================================

# Execute start node: start
execute_node_start() {
    log_step "🚀 Starting Workflow: Start"
    
    # Initialize workflow state
    set_workflow_state "current_node" "start"
    set_workflow_state "status" "running"
    set_workflow_state "start_time" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    
    # Set initial variables from node data
    # No initial variables defined
    
    log_info "Workflow started successfully"
}

# Execute agent node: agent_task
execute_node_agent_task() {
    log_step "🤖 Running Agent: Execute Task"
    
    local agent_command="default-agent"
    local agent_args=()
    local agent_timeout=300
    
    # No inputs to prepare
    
    # Execute agent with timeout
    local agent_exit_code=0
    if [[ "$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock agent execution"
        local mock_output="Mock output from default-agent"
        local mock_result="Mock result: success"
        
        echo "$mock_output"
        set_workflow_var "agent_output" "$mock_output"
        set_workflow_var "agent_result" "$mock_result"
        agent_exit_code=0
    else
        log_debug "Executing agent: $agent_command with args: ${agent_args[*]}"
        
        # Execute with timeout
        local output
        if output=$(timeout "$agent_timeout" "$agent_command" "${agent_args[@]}" 2>&1); then
            agent_exit_code=0
        else
            agent_exit_code=$?
        fi
        
        # Store output
        set_workflow_var "agent_output" "$output"
        
        # Log output (truncated for readability)
        if [[ ${#output} -gt 200 ]]; then
            log_debug "Agent output (truncated): ${output:0:200}..."
        else
            log_debug "Agent output: $output"
        fi
    fi
    
    # Handle agent result
    if [[ $agent_exit_code -eq 0 ]]; then
        log_info "Agent '$agent_command' completed successfully"
        # No outputs to process
    else
        log_error "Agent '$agent_command' failed with exit code $agent_exit_code"
        return $agent_exit_code
    fi
    
    set_workflow_state "current_node" "agent_task"
}

# Execute answer node: result
execute_node_result() {
    log_step "📤 Providing Answer: Result"
    
    local answer_text="Task completed successfully"
    local final_answer
    final_answer=$(substitute_variables "$answer_text")
    
    echo "=========================="
    echo "WORKFLOW RESULT"
    echo "=========================="
    echo "$final_answer"
    echo "=========================="
    
    log_success "Workflow completed successfully"
    set_workflow_state "current_node" "result"
    set_workflow_state "completed" "true"
}

# =============================================================================
# WORKFLOW EXECUTION FLOW
# =============================================================================

# Execute the complete workflow
execute_workflow() {
    log_info "Starting workflow execution..."
    set_workflow_state "status" "running"
    
    # Generate unique correlation ID for this execution
    local correlation_id=$(date +%s%N | sha256sum | head -c 8)
    
    # Execute start node: start
    if ! execute_node_start "" "$correlation_id"; then
        log_error "Workflow failed at node: start"
        set_workflow_state "status" "failed"
        return 1
    fi

    # Execute agent node: agent_task
    if ! execute_node_agent_task "" "$correlation_id"; then
        log_error "Workflow failed at node: agent_task"
        set_workflow_state "status" "failed"
        return 1
    fi

    # Execute answer node: result
    if ! execute_node_result "" "$correlation_id"; then
        log_error "Workflow failed at node: result"
        set_workflow_state "status" "failed"
        return 1
    fi

    
    log_success "Workflow execution completed"
    set_workflow_state "status" "completed"
}

# =============================================================================
# WORKFLOW INITIALIZATION  
# =============================================================================

# Show help message
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Generated workflow script for: ${WORKFLOW_NAME}"
    echo ""
    echo "Options:"
    echo "    --task_description"
    echo "        What you want the agent to do"
    echo "    --help, -h      Show this help message"
    echo "    --mock         Use mock tools (default: true)"  
    echo "    --real         Use real tools instead of mocks"
    echo "    --verbose      Enable verbose output"
    echo "    --timeout=N    Set timeout in seconds (default: ${AGENT_TIMEOUT})"
    echo ""
    echo "Environment Variables:"
    echo "    USE_MOCK_TOOLS    Set to 'false' to use real tools"
    echo "    VERBOSE          Set to 'true' for debug output"
    echo "    AGENT_TIMEOUT    Timeout in seconds for agent calls"
}

# Initialize workflow with command line arguments
init_workflow() {
    log_info "Initializing workflow: ${WORKFLOW_NAME} v${WORKFLOW_VERSION}"
    
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
        --task_description)
            if [[ -z "${2:-}" ]]; then
                log_error "Option --task_description requires a value"
                show_help
                exit 1
            fi
            set_workflow_var "task_description" "$2"
            shift 2
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        --mock)
            USE_MOCK_TOOLS=true
            export USE_MOCK_TOOLS
            shift
            ;;
        --real)
            USE_MOCK_TOOLS=false
            export USE_MOCK_TOOLS
            shift
            ;;
        --verbose)
            VERBOSE=true
            export VERBOSE
            shift
            ;;
        --timeout=*)
            AGENT_TIMEOUT="${1#*=}"
            export AGENT_TIMEOUT
            shift
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        esac
    done
    
    # Set default values for missing variables
        [[ -z "$(get_workflow_var 'task_description' '')" ]] && set_workflow_var "task_description" ""
    
    log_info "Workflow initialization completed"
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

# Health check function
health_check() {
    log_info "Running system health check..."
    
    # Check required commands based on mode
    if [[ "$USE_MOCK_TOOLS" != "true" ]]; then
        local missing_tools=()
        
        command -v opencode >/dev/null 2>&1 || missing_tools+=("opencode")
        
        if [[ ${#missing_tools[@]} -gt 0 ]]; then
            log_info "Missing tools (will use mocks): ${missing_tools[*]}"
        else
            log_success "All required tools available"
        fi
    else
        log_info "Running in mock mode - no external tools required"
    fi
}

# Main function
main() {
    health_check
    init_workflow "$@"
    execute_workflow
}

# Run if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi