#!/bin/bash
# Test Script v2 - With Agent Orchestration
# Generated by flowsh v1.0.0
# Source: Agent Workflow Example

set -euo pipefail

# Workflow variables
declare -A workflow_vars

# Mock opencode command for testing
mock_opencode() {
    echo "🤖 Mock opencode called with prompt:"
    echo "---"
    echo "$1"
    echo "---"
    echo "✅ Mock agent completed task successfully"
    return 0
}

# Mock make command for testing  
mock_make() {
    case "$1" in
        "test")
            echo "🧪 Running tests..."
            echo "✅ All tests passed"
            return 0
            ;;
        *)
            echo "❌ Unknown make target: $1"
            return 1
            ;;
    esac
}

# Initialize workflow
init_workflow() {
    workflow_vars["task_description"]="${1:-}"
    workflow_vars["project_path"]="${2:-}"
    
    [[ -z "${workflow_vars["task_description"]}" ]] && {
        echo "Error: task_description is required" >&2
        echo "Usage: $0 'task description' /path/to/project" >&2
        exit 1
    }
    [[ -z "${workflow_vars["project_path"]}" ]] && {
        echo "Error: project_path is required" >&2
        echo "Usage: $0 'task description' /path/to/project" >&2
        exit 1
    }
    
    # Validate project path exists
    [[ ! -d "${workflow_vars["project_path"]}" ]] && {
        echo "Error: project_path '${workflow_vars["project_path"]}' does not exist" >&2
        exit 1
    }
    
    echo "✓ Workflow initialized successfully"
    echo "  Task: ${workflow_vars["task_description"]}"
    echo "  Project: ${workflow_vars["project_path"]}"
}

# Execute agent node: code_agent
execute_agent_node_code_agent() {
    echo "🚀 Running Code Agent..."
    
    # Resolve template from registry
    local template_content
    template_content=$(resolve_template "task-planner" "library")
    
    local prompt=$(render_template "$template_content" "${workflow_vars["task_description"]}")
    
    # Call agent CLI tool (mocked for testing)
    if command -v opencode >/dev/null 2>&1; then
        opencode run "$prompt"
    else
        echo "📝 opencode not found, using mock"
        mock_opencode "$prompt"
    fi
    
    [[ $? -eq 0 ]] || {
        echo "ERROR: Agent execution failed" >&2
        exit 1
    }
    
    echo "✅ Code agent completed successfully"
}

# Execute code node: validate_code
execute_code_node_validate_code() {
    echo "🔍 Running validation..."
    
    # Change to project directory
    local original_dir=$(pwd)
    cd "${workflow_vars["project_path"]}"
    
    # Execute validation command (mocked for testing)
    local exit_code=0
    if command -v make >/dev/null 2>&1; then
        make test || exit_code=$?
    else
        echo "📝 make not found, using mock"
        mock_make "test" || exit_code=$?
    fi
    
    # Return to original directory
    cd "$original_dir"
    
    # Handle success/failure routing
    if [[ $exit_code -eq 0 ]]; then
        echo "✅ Validation passed - proceeding to deploy"
        execute_node_deploy
    else
        echo "❌ Validation failed - proceeding to fix issues"
        execute_node_fix_issues
    fi
}

# Mock deploy node
execute_node_deploy() {
    echo "🚀 Deploying application..."
    echo "✅ Deployment completed successfully"
}

# Mock fix_issues node
execute_node_fix_issues() {
    echo "🔧 Fixing issues..."
    echo "✅ Issues fixed, ready for re-validation"
}

# Template resolution helper
resolve_template() {
    local template_id="$1"
    local source="$2"
    
    case "$template_id" in
        "task-planner")
            cat <<'TEMPLATE'
You are a task planner. Break down this task: {{task_description}}
Create actionable steps and implement them.
TEMPLATE
            ;;
        *)
            echo "Error: Unknown template '$template_id'" >&2
            return 1
            ;;
    esac
}

# Template rendering helper  
render_template() {
    local template="$1"
    local task_description="$2"
    
    echo "$template" | sed "s|{{task_description}}|$task_description|g"
}

# Main execution
main() {
    init_workflow "$@"
    execute_agent_node_code_agent
    execute_code_node_validate_code
}

# Run if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi