#!/bin/bash
# Test Script v1 - Basic structure
# Generated by flowsh v1.0.0
# Source: Agent Workflow Example

set -euo pipefail

# Workflow variables
declare -A workflow_vars

# Initialize workflow
init_workflow() {
    workflow_vars["task_description"]="${1:-}"
    workflow_vars["project_path"]="${2:-}"
    
    [[ -z "${workflow_vars["task_description"]}" ]] && {
        echo "Error: task_description is required" >&2
        echo "Usage: $0 'task description' /path/to/project" >&2
        exit 1
    }
    [[ -z "${workflow_vars["project_path"]}" ]] && {
        echo "Error: project_path is required" >&2
        echo "Usage: $0 'task description' /path/to/project" >&2
        exit 1
    }
    
    # Validate project path exists
    [[ ! -d "${workflow_vars["project_path"]}" ]] && {
        echo "Error: project_path '${workflow_vars["project_path"]}' does not exist" >&2
        exit 1
    }
    
    echo "✓ Workflow initialized successfully"
    echo "  Task: ${workflow_vars["task_description"]}"
    echo "  Project: ${workflow_vars["project_path"]}"
}

# Template resolution helper
resolve_template() {
    local template_id="$1"
    local source="$2"
    
    case "$template_id" in
        "task-planner")
            cat <<'TEMPLATE'
You are a task planner. Break down this task: {{task_description}}
Create actionable steps and implement them.
TEMPLATE
            ;;
        *)
            echo "Error: Unknown template '$template_id'" >&2
            return 1
            ;;
    esac
}

# Template rendering helper  
render_template() {
    local template="$1"
    local task_description="$2"
    
    echo "$template" | sed "s|{{task_description}}|$task_description|g"
}

# Test basic functions
main() {
    echo "Testing basic workflow functions..."
    
    # Test template resolution
    echo "Testing template resolution..."
    local template_content
    template_content=$(resolve_template "task-planner" "library")
    echo "✓ Template resolved"
    
    # Test template rendering
    echo "Testing template rendering..."
    local rendered_prompt
    rendered_prompt=$(render_template "$template_content" "test task")
    echo "✓ Template rendered: $rendered_prompt"
    
    echo "✓ All basic functions work"
}

# Run if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi