/**
 * Shell Script Generator for flowsh Workflows
 *
 * Generates portable bash/zsh scripts from flowsh workflow definitions.
 * Includes agent orchestration, variable management, error handling, and template resolution.
 */

import {
  FlowshWorkflow,
  WorkflowNode,
  WorkflowEdge,
  isStartNode,
  isEndNode,
  isLLMNode,
  isCodeNode,
  isAgentNode,
  isIfElseNode,
  isAnswerNode,
  isVariableAssignmentNode,
  isLoopNode,
  isIterationNode,
} from '../dsl/types.js';

// =============================================================================
// Generation Configuration
// =============================================================================

export interface GenerationOptions {
  /** Include mock implementations for testing */
  includeMocks?: boolean;
  /** Shell type to target */
  shell?: 'bash' | 'zsh';
  /** Include verbose debugging output */
  verbose?: boolean;
  /** Default timeout for agent calls */
  defaultTimeout?: number;
  /** Template for shell script header */
  headerTemplate?: string;
}

export interface GenerationResult {
  /** Generated shell script content */
  script: string;
  /** Generation success status */
  success: boolean;
  /** Any warnings during generation */
  warnings: string[];
  /** Metadata about the generated script */
  metadata: {
    nodeCount: number;
    edgeCount: number;
    hasAgentNodes: boolean;
    hasLLMNodes: boolean;
    estimatedComplexity: 'low' | 'medium' | 'high';
  };
}

// =============================================================================
// Main Generation Function
// =============================================================================

/**
 * Generates a shell script from a flowsh workflow
 */
export function generateShellScript(
  workflow: FlowshWorkflow,
  options: GenerationOptions = {}
): GenerationResult {
  const { includeMocks = true } = options;

  const warnings: string[] = [];

  // Get workflow graph
  const graph = workflow.graph ?? workflow.spec?.graph;
  if (!graph || !graph.nodes || graph.nodes.length === 0) {
    return {
      script: '',
      success: false,
      warnings: ['No workflow graph found or graph is empty'],
      metadata: {
        nodeCount: 0,
        edgeCount: 0,
        hasAgentNodes: false,
        hasLLMNodes: false,
        estimatedComplexity: 'low',
      },
    };
  }

  // Analyze workflow complexity
  const metadata = analyzeWorkflow(graph.nodes, graph.edges || []);

  // Generate script components
  const scriptParts: string[] = [];

  // 1. Header and setup
  scriptParts.push(generateScriptHeader(workflow, options));

  // 2. Utility functions
  scriptParts.push(generateUtilityFunctions());

  // 3. Mock functions (if enabled)
  if (includeMocks) {
    scriptParts.push(generateMockFunctions());
  }

  // 4. Template system
  scriptParts.push(generateTemplateSystem(workflow));

  // 5. Node execution functions
  scriptParts.push(generateNodeFunctions(graph.nodes));

  // 6. Main execution flow
  scriptParts.push(generateMainFlow(graph.nodes, graph.edges || []));

  // 7. Argument parsing and initialization
  scriptParts.push(generateArgumentParsing(workflow));

  // 8. Script footer
  scriptParts.push(generateScriptFooter());

  const script = scriptParts.join('\n\n');

  return {
    script,
    success: true,
    warnings,
    metadata,
  };
}

// =============================================================================
// Script Components Generation
// =============================================================================

/**
 * Generates the script header with metadata and basic setup
 */
function generateScriptHeader(workflow: FlowshWorkflow, options: GenerationOptions): string {
  const workflowName = workflow.workflow?.name || workflow.metadata?.name || 'Unnamed Workflow';
  const workflowVersion = workflow.workflow?.version || workflow.metadata?.version || '1.0.0';
  const description = workflow.workflow?.description || workflow.metadata?.description || '';

  return `#!/bin/${options.shell || 'bash'}
# Generated by flowsh v1.0.0
# Source: ${workflowName}
${description ? `# Description: ${description}` : ''}
# Version: ${workflowVersion}
# Generated: ${new Date().toISOString()}

set -euo pipefail

# =============================================================================
# WORKFLOW CONFIGURATION
# =============================================================================

# Workflow variables
declare -A workflow_vars
declare -A workflow_state

# Control flags for testing and configuration
USE_MOCK_TOOLS=\${USE_MOCK_TOOLS:-true}
AGENT_TIMEOUT=\${AGENT_TIMEOUT:-${options.defaultTimeout || 60}}
VERBOSE=\${VERBOSE:-${options.verbose ? 'true' : 'false'}}
WORKFLOW_NAME="${workflowName}"
WORKFLOW_VERSION="${workflowVersion}"

# Color codes for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
CYAN='\\033[0;36m'
NC='\\033[0m' # No Color`;
}

/**
 * Generates utility functions for logging, error handling, etc.
 */
function generateUtilityFunctions(): string {
  return `# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "\${CYAN}ℹ️  \$*\${NC}"
}

log_success() {
    echo -e "\${GREEN}✅ \$*\${NC}"
}

log_error() {
    echo -e "\${RED}❌ \$*\${NC}" >&2
}

log_warning() {
    echo -e "\${YELLOW}⚠️  \$*\${NC}" >&2
}

log_debug() {
    [[ "\$VERBOSE" == "true" ]] && echo -e "\${BLUE}🔍 DEBUG: \$*\${NC}" >&2 || true
}

log_step() {
    echo -e "\${CYAN}🚀 \$*\${NC}"
}

# Enhanced error handling
handle_error() {
    local exit_code=\$1
    local context="\$2"
    local node_id="\${3:-unknown}"
    
    case \$exit_code in
        124)
            log_error "Timeout: \$context took longer than \${AGENT_TIMEOUT}s (node: \$node_id)"
            ;;
        127)
            log_error "Command not found in: \$context (node: \$node_id)"
            ;;
        1)
            log_error "General error in: \$context (node: \$node_id)"
            ;;
        *)
            log_error "Unknown error (exit code \$exit_code) in: \$context (node: \$node_id)"
            ;;
    esac
    
    return \$exit_code
}

# Variable management
set_workflow_var() {
    local var_name="\$1"
    local var_value="\$2"
    workflow_vars["\$var_name"]="\$var_value"
    log_debug "Set variable: \$var_name = \$var_value"
}

get_workflow_var() {
    local var_name="\$1"
    local default_value="\${2:-}"
    echo "\${workflow_vars[\$var_name]:-\$default_value}"
}

# State management
set_workflow_state() {
    local state_key="\$1"
    local state_value="\$2"
    workflow_state["\$state_key"]="\$state_value"
    log_debug "Set state: \$state_key = \$state_value"
}

get_workflow_state() {
    local state_key="\$1"
    local default_value="\${2:-}"
    echo "\${workflow_state[\$state_key]:-\$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="\$1"
    local result="\$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ \$result =~ \\{\\{#([^#]+)#\\}\\} ]]; do
        local var_ref="\${BASH_REMATCH[1]}"
        local var_value=\$(get_workflow_var "\$var_ref" "")
        
        if [[ -z "\$var_value" ]]; then
            log_warning "Variable reference '\$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=\$(printf '%s\\n' "\$var_value" | sed 's/[[\\.\\*^\\$()+?{|]/\\\\&/g')
        result=\$(echo "\$result" | sed "s|{{#\${var_ref}#}}|\$escaped_value|g")
    done
    
    echo "\$result"
}`;
}

/**
 * Generates mock functions for testing without actual tools
 */
function generateMockFunctions(): string {
  return `# =============================================================================
# MOCK FUNCTIONS FOR TESTING
# =============================================================================

# Mock opencode command for testing
mock_opencode() {
    local prompt="\$1"
    log_info "Mock opencode called with prompt:"
    echo "---"
    echo "\${prompt:0:200}..." # Show first 200 chars
    echo "---"
    
    # Simulate some processing time
    sleep 2
    
    log_success "Mock agent completed task successfully"
    return 0
}

# Mock LLM call for testing  
mock_llm() {
    local prompt="\$1"
    local model="\${2:-gpt-4}"
    
    log_info "Mock LLM (\$model) called with prompt:"
    echo "---"
    echo "\${prompt:0:200}..." # Show first 200 chars
    echo "---"
    
    # Simulate processing time based on model
    case "\$model" in
        *"gpt-4"*) sleep 3 ;;
        *"claude"*) sleep 2 ;;
        *) sleep 1 ;;
    esac
    
    log_success "Mock LLM response generated"
    echo "This is a mock response from \$model. In a real implementation, this would be the actual LLM output."
    return 0
}

# Mock command execution
mock_command() {
    local command="\$1"
    shift
    local args=("\$@")
    
    log_info "Mock command: \$command \${args[*]}"
    
    case "\$command" in
        "make")
            case "\${args[0]:-}" in
                "test")
                    log_info "Running tests..."
                    sleep 1
                    log_success "All tests passed"
                    return 0
                    ;;
                "build")
                    log_info "Building project..."
                    sleep 2
                    log_success "Build completed"
                    return 0
                    ;;
                *)
                    log_error "Unknown make target: \${args[0]:-}"
                    return 1
                    ;;
            esac
            ;;
        "npm"|"yarn"|"pnpm")
            log_info "Running package manager command..."
            sleep 1
            log_success "Package manager command completed"
            return 0
            ;;
        "git")
            log_info "Running git command..."
            sleep 1
            log_success "Git command completed"
            return 0
            ;;
        *)
            log_info "Running generic command: \$command"
            sleep 1
            log_success "Command completed"
            return 0
            ;;
    esac
}`;
}

/**
 * Generates template system functions
 */
function generateTemplateSystem(workflow: FlowshWorkflow): string {
  const dependencies =
    workflow.workflow?.template_dependencies || workflow.spec?.template_dependencies || [];

  let templateCases = '';
  for (const dep of dependencies) {
    templateCases += `        "${dep.template_id}")
            cat <<'TEMPLATE'
# Template: ${dep.template_id}
# Source: ${dep.source}
# Version: ${dep.version || 'latest'}
You are an AI assistant. Please process this request: {{task_description}}

Be helpful, accurate, and concise in your response.
TEMPLATE
            ;;
`;
  }

  return `# =============================================================================
# TEMPLATE SYSTEM
# =============================================================================

# Template resolution with fallback system
resolve_template() {
    local template_id="\$1"
    local source="\${2:-library}"
    
    log_debug "Resolving template: \$template_id from \$source"
    
    case "\$template_id" in
${templateCases}        "task-planner")
            cat <<'TEMPLATE'
You are a task planner. Break down this task: {{task_description}}

Create actionable steps and implement them systematically.
Focus on:
1. Understanding requirements
2. Breaking down into subtasks  
3. Implementation planning
4. Testing strategy

Keep your response concise and actionable.
TEMPLATE
            ;;
        "code-reviewer")
            cat <<'TEMPLATE'
Review and analyze this task: {{task_description}}

Provide feedback on:
1. Code quality and best practices
2. Potential security issues
3. Performance considerations
4. Testing coverage
TEMPLATE
            ;;
        *)
            log_error "Unknown template '\$template_id'"
            return 1
            ;;
    esac
}

# Template rendering with variable substitution
render_template() {
    local template="\$1"
    local task_description="\$2"
    
    # Validate inputs
    [[ -z "\$template" ]] && {
        log_error "Template content is empty"
        return 1
    }
    [[ -z "\$task_description" ]] && {
        log_error "Task description is empty"
        return 1
    }
    
    # Use the variable substitution function
    local rendered_template="\$(substitute_variables "\$template")"
    
    # Handle specific variable substitutions for backward compatibility
    rendered_template=\$(echo "\$rendered_template" | sed "s|{{task_description}}|\$task_description|g")
    
    echo "\$rendered_template"
}`;
}

/**
 * Generates node execution functions
 */
function generateNodeFunctions(nodes: WorkflowNode[]): string {
  const functions: string[] = [];

  functions.push('# =============================================================================');
  functions.push('# NODE EXECUTION FUNCTIONS');
  functions.push('# =============================================================================');

  for (const node of nodes) {
    const functionName = `execute_node_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}`;

    if (isStartNode(node)) {
      functions.push(generateStartNodeFunction(node, functionName));
    } else if (isAgentNode(node)) {
      functions.push(generateAgentNodeFunction(node, functionName));
    } else if (isCodeNode(node)) {
      functions.push(generateCodeNodeFunction(node, functionName));
    } else if (isLLMNode(node)) {
      functions.push(generateLLMNodeFunction(node, functionName));
    } else if (isIfElseNode(node)) {
      functions.push(generateIfElseNodeFunction(node, functionName));
    } else if (isAnswerNode(node)) {
      functions.push(generateAnswerNodeFunction(node, functionName));
    } else if (isVariableAssignmentNode(node)) {
      functions.push(generateVariableAssignmentNodeFunction(node, functionName));
    } else {
      functions.push(generateGenericNodeFunction(node, functionName));
    }
  }

  return functions.join('\n\n');
}

function generateStartNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;
  const variables = data.variables || [];

  let variableValidation = '';
  for (const variable of variables) {
    if (variable.required) {
      variableValidation += `    [[ -z "\${workflow_vars["${variable.variable}"]:-}" ]] && {
        log_error "${variable.variable} is required"
        show_usage
        exit 1
    }
`;
    }
  }

  return `# Execute start node: ${node.id}
${functionName}() {
    log_step "Starting workflow: ${data.title || node.id}"
    
    # Validate required variables
${variableValidation}    
    log_success "Workflow initialized successfully"
    set_workflow_state "current_node" "${node.id}"
}`;
}

function generateAgentNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;

  return `# Execute agent node: ${node.id}
${functionName}() {
    log_step "🤖 Running Agent: ${data.title || node.id}"
    
    local agent_exit_code=0
    local command="${data.command || 'opencode'}"
    
    # Resolve and render template if provided
    local prompt=""
    if [[ -n "${data.prompt_template?.template_id || ''}" ]]; then
        local template_content
        if ! template_content=\$(resolve_template "${data.prompt_template?.template_id || ''}" "${data.prompt_template?.source || 'library'}"); then
            log_error "Failed to resolve template '${data.prompt_template?.template_id || ''}'"
            return 1
        fi
        
        if ! prompt=\$(render_template "\$template_content" "\$(get_workflow_var 'task_description' '')"); then
            log_error "Failed to render template"
            return 1
        fi
    else
        prompt="\$(get_workflow_var 'task_description' 'Default task')"
    fi
    
    log_debug "Generated prompt length: \${#prompt} characters"
    
    # Execute agent command with proper error handling
    if [[ "\$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock \$command"
        mock_opencode "\$prompt" || agent_exit_code=\$?
    elif command -v "\$command" >/dev/null 2>&1; then
        log_debug "Using real \$command with timeout \${AGENT_TIMEOUT}s"
        ${data.working_directory ? `cd "${data.working_directory}"` : ''}
        timeout "\$AGENT_TIMEOUT" "\$command" ${(data.args || []).map((arg: any) => `"${arg}"`).join(' ')} "\$prompt" || agent_exit_code=\$?
        
        # Handle timeout gracefully
        if [[ \$agent_exit_code -eq 124 ]]; then
            log_error "\$command timed out after \${AGENT_TIMEOUT}s, falling back to mock"
            mock_opencode "\$prompt" || agent_exit_code=\$?
        fi
    else
        log_info "\$command not found, falling back to mock"
        mock_opencode "\$prompt" || agent_exit_code=\$?
    fi
    
    if [[ \$agent_exit_code -ne 0 ]]; then
        handle_error \$agent_exit_code "Agent execution" "${node.id}"
        return \$agent_exit_code
    fi
    
    log_success "Agent completed successfully"
    set_workflow_state "current_node" "${node.id}"
}`;
}

function generateCodeNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;

  return `# Execute code node: ${node.id}
${functionName}() {
    log_step "🔧 Running Code: ${data.title || node.id}"
    
    local exit_code=0
    local command="${data.command}"
    
    # Change to working directory if specified
    ${
      data.working_directory
        ? `
    local original_dir
    original_dir=\$(pwd)
    
    if ! cd "${data.working_directory}"; then
        log_error "Failed to change to directory: ${data.working_directory}"
        return 1
    fi
    
    log_debug "Changed to directory: \$(pwd)"`
        : ''
    }
    
    # Execute command with fallback options
    if [[ "\$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock command"
        mock_command "\$command" ${(data.args || []).map((arg: any) => `"${arg}"`).join(' ')} || exit_code=\$?
    else
        log_debug "Using real command: \$command"
        "\$command" ${(data.args || []).map((arg: any) => `"${arg}"`).join(' ')} || exit_code=\$?
    fi
    
    ${
      data.working_directory
        ? `
    # Return to original directory
    cd "\$original_dir" || {
        log_error "Failed to return to original directory"
        return 1
    }`
        : ''
    }
    
    # Handle success/failure routing
    if [[ \$exit_code -eq 0 ]]; then
        log_success "Code execution completed successfully"
        ${data.on_success ? `execute_node_${data.on_success.replace(/[^a-zA-Z0-9]/g, '_')}` : ''}
    else
        log_error "Code execution failed with exit code: \$exit_code"
        ${data.on_failure ? `execute_node_${data.on_failure.replace(/[^a-zA-Z0-9]/g, '_')}` : `return \$exit_code`}
    fi
    
    set_workflow_state "current_node" "${node.id}"
}`;
}

function generateLLMNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;

  return `# Execute LLM node: ${node.id}
${functionName}() {
    log_step "🧠 Running LLM: ${data.title || node.id}"
    
    local model_name="${data.model?.name || 'gpt-4'}"
    local provider="${data.model?.provider || 'openai'}"
    
    # Prepare prompt
    local prompt=""
    if [[ -n "${data.prompt_template?.template_id || ''}" ]]; then
        local template_content
        if ! template_content=\$(resolve_template "${data.prompt_template?.template_id || ''}" "${data.prompt_template?.source || 'library'}"); then
            log_error "Failed to resolve template '${data.prompt_template?.template_id || ''}'"
            return 1
        fi
        
        if ! prompt=\$(render_template "\$template_content" "\$(get_workflow_var 'task_description' '')"); then
            log_error "Failed to render template"
            return 1
        fi
    else
        prompt="\$(get_workflow_var 'task_description' 'Default LLM prompt')"
    fi
    
    # Execute LLM call
    local llm_exit_code=0
    if [[ "\$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock LLM"
        local response
        response=\$(mock_llm "\$prompt" "\$model_name") || llm_exit_code=\$?
        
        if [[ \$llm_exit_code -eq 0 ]]; then
            set_workflow_var "${node.id}_response" "\$response"
        fi
    else
        log_warning "Real LLM integration not implemented yet, using mock"
        local response
        response=\$(mock_llm "\$prompt" "\$model_name") || llm_exit_code=\$?
        
        if [[ \$llm_exit_code -eq 0 ]]; then
            set_workflow_var "${node.id}_response" "\$response"
        fi
    fi
    
    if [[ \$llm_exit_code -ne 0 ]]; then
        handle_error \$llm_exit_code "LLM execution" "${node.id}"
        return \$llm_exit_code
    fi
    
    log_success "LLM execution completed"
    set_workflow_state "current_node" "${node.id}"
}`;
}

function generateIfElseNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;

  return `# Execute if-else node: ${node.id}
${functionName}() {
    log_step "🔀 Evaluating Conditions: ${data.title || node.id}"
    
    local condition_result=false
    
    # TODO: Implement condition evaluation logic
    # For now, this is a placeholder
    log_warning "If-else condition evaluation not fully implemented"
    
    if [[ "\$condition_result" == "true" ]]; then
        log_info "Condition(s) evaluated to true"
        set_workflow_state "branch_taken" "true"
    else
        log_info "Condition(s) evaluated to false"
        set_workflow_state "branch_taken" "false"
    fi
    
    set_workflow_state "current_node" "${node.id}"
}`;
}

function generateAnswerNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;

  return `# Execute answer node: ${node.id}
${functionName}() {
    log_step "📤 Providing Answer: ${data.title || node.id}"
    
    local answer_text="${data.answer || 'Workflow completed'}"
    local final_answer
    final_answer=\$(substitute_variables "\$answer_text")
    
    echo "=========================="
    echo "WORKFLOW RESULT"
    echo "=========================="
    echo "\$final_answer"
    echo "=========================="
    
    log_success "Workflow completed successfully"
    set_workflow_state "current_node" "${node.id}"
    set_workflow_state "completed" "true"
}`;
}

function generateVariableAssignmentNodeFunction(node: WorkflowNode, functionName: string): string {
  const data = node.data as any;

  return `# Execute variable assignment node: ${node.id}
${functionName}() {
    log_step "📝 Variable Assignment: ${data.title || node.id}"
    
    local variable_name="${data.variable}"
    local assignment_type="${data.assignment_type || 'constant'}"
    
    case "\$assignment_type" in
        "constant")
            set_workflow_var "\$variable_name" "${data.value || ''}"
            ;;
        "variable")
            local source_value=\$(get_workflow_var "${data.source_variable || ''}" "")
            set_workflow_var "\$variable_name" "\$source_value"
            ;;
        "expression")
            log_warning "Expression evaluation not implemented, using constant value"
            set_workflow_var "\$variable_name" "${data.value || ''}"
            ;;
    esac
    
    log_success "Variable '\$variable_name' assigned"
    set_workflow_state "current_node" "${node.id}"
}`;
}

function generateGenericNodeFunction(node: WorkflowNode, functionName: string): string {
  return `# Execute generic node: ${node.id}
${functionName}() {
    log_step "⚙️  Executing Node: ${node.data.title || node.id} (${node.type})"
    
    log_warning "Node type '${node.type}' not fully implemented"
    
    # Placeholder implementation
    sleep 1
    log_info "Node execution completed (placeholder)"
    
    set_workflow_state "current_node" "${node.id}"
}`;
}

/**
 * Generates the main execution flow
 */
function generateMainFlow(nodes: WorkflowNode[], edges: WorkflowEdge[]): string {
  // Find start node
  const startNodes = nodes.filter(isStartNode);
  const startNodeId = startNodes.length > 0 ? startNodes[0]!.id : nodes[0]?.id;

  // Build execution order (simplified linear execution for now)
  let executionOrder = '';
  if (startNodeId) {
    executionOrder = `    execute_node_${startNodeId.replace(/[^a-zA-Z0-9]/g, '_')}\n`;

    // Add other nodes in order (simplified approach)
    const remainingNodes = nodes.filter(
      node => node.id !== startNodeId && !isEndNode(node) && !isAnswerNode(node)
    );
    for (const node of remainingNodes) {
      executionOrder += `    execute_node_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}\n`;
    }

    // Add end/answer nodes last
    const endNodes = nodes.filter(node => isEndNode(node) || isAnswerNode(node));
    for (const node of endNodes) {
      executionOrder += `    execute_node_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}\n`;
    }
  }

  return `# =============================================================================
# MAIN EXECUTION FLOW
# =============================================================================

# Execute the workflow
execute_workflow() {
    log_info "Starting workflow execution: \$WORKFLOW_NAME"
    log_info "Nodes: ${nodes.length}, Edges: ${edges.length}"
    
${executionOrder}
    
    local completion_status=\$(get_workflow_state "completed" "false")
    if [[ "\$completion_status" == "true" ]]; then
        log_success "Workflow completed successfully"
    else
        log_warning "Workflow execution finished but completion status unclear"
    fi
}`;
}

/**
 * Generates argument parsing logic
 */
function generateArgumentParsing(workflow: FlowshWorkflow): string {
  const envVars = workflow.environment_variables || workflow.spec?.environment_variables || [];

  let argumentHandling = '';
  let usageText = '';

  for (let i = 0; i < envVars.length; i++) {
    const envVar = envVars[i];
    if (envVar) {
      argumentHandling += `    workflow_vars["${envVar.variable}"]="\${${i + 1}:-}"\n`;
      usageText += `  arg${i + 1}    ${envVar.name || envVar.variable}${envVar.description ? ` - ${envVar.description}` : ''}\n`;
    }
  }

  return `# =============================================================================
# ARGUMENT PARSING AND INITIALIZATION
# =============================================================================

# Usage help
show_usage() {
    cat <<EOF
\$WORKFLOW_NAME v\$WORKFLOW_VERSION

Usage: \$0 [OPTIONS] ${envVars.map((_, i) => `<arg${i + 1}>`).join(' ')}

Arguments:
${usageText}Options:
  --no-mock         Use real tools instead of mocks
  --timeout SECS    Set agent timeout in seconds (default: \$AGENT_TIMEOUT)
  --verbose         Enable verbose debug output
  --help            Show this help message

Environment Variables:
  USE_MOCK_TOOLS    Set to 'false' to use real tools (default: true)
  AGENT_TIMEOUT     Agent timeout in seconds (default: 60)
  VERBOSE           Set to 'true' for debug output (default: false)

Examples:
  \$0 "Implement user auth" /path/to/project
  \$0 --no-mock --verbose "Fix bug in API" /path/to/project
EOF
}

# Initialize workflow with arguments
init_workflow() {
${argumentHandling}
    
    # Validate required arguments
    ${envVars
      .map(
        (envVar, i) =>
          `[[ -z "\${workflow_vars["${envVar?.variable || `arg${i}`}"]}" ]] && {
        log_error "${envVar?.variable || `arg${i}`} is required"
        show_usage
        exit 1
    }`
      )
      .join('\n    ')}
    
    log_success "Workflow initialized with provided arguments"
    ${envVars
      .map(
        envVar =>
          `log_debug "${envVar?.variable || 'unknown'}: \${workflow_vars["${envVar?.variable || 'unknown'}"]}"`
      )
      .join('\n    ')}
}

# Parse command line arguments
while [[ \$# -gt 0 ]]; do
    case \$1 in
        --no-mock)
            USE_MOCK_TOOLS=false
            shift
            ;;
        --timeout)
            [[ -n "\${2:-}" ]] || {
                log_error "--timeout requires a value"
                exit 1
            }
            [[ "\$2" =~ ^[0-9]+\$ ]] || {
                log_error "Timeout must be a positive integer"
                exit 1
            }
            AGENT_TIMEOUT="\$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        -*)
            log_error "Unknown option: \$1"
            show_usage >&2
            exit 1
            ;;
        *)
            break
            ;;
    esac
done`;
}

/**
 * Generates the script footer with main execution
 */
function generateScriptFooter(): string {
  return `# =============================================================================
# MAIN EXECUTION
# =============================================================================

# Health check function
health_check() {
    log_info "Running system health check..."
    
    # Check required commands based on mode
    if [[ "\$USE_MOCK_TOOLS" != "true" ]]; then
        local missing_tools=()
        
        command -v opencode >/dev/null 2>&1 || missing_tools+=("opencode")
        
        if [[ \${#missing_tools[@]} -gt 0 ]]; then
            log_info "Missing tools (will use mocks): \${missing_tools[*]}"
        else
            log_success "All required tools available"
        fi
    else
        log_info "Running in mock mode - no external tools required"
    fi
}

# Main function
main() {
    health_check
    init_workflow "\$@"
    execute_workflow
}

# Run if called directly
if [[ "\${BASH_SOURCE[0]}" == "\${0}" ]]; then
    main "\$@"
fi`;
}

// =============================================================================
// Analysis Functions
// =============================================================================

/**
 * Analyzes workflow complexity and characteristics
 */
function analyzeWorkflow(
  nodes: WorkflowNode[],
  edges: WorkflowEdge[]
): GenerationResult['metadata'] {
  const nodeCount = nodes.length;
  const edgeCount = edges.length;

  const hasAgentNodes = nodes.some(isAgentNode);
  const hasLLMNodes = nodes.some(isLLMNode);
  const hasLoopNodes = nodes.some(isLoopNode);
  const hasIterationNodes = nodes.some(isIterationNode);
  const hasIfElseNodes = nodes.some(isIfElseNode);

  let estimatedComplexity: 'low' | 'medium' | 'high' = 'low';

  if (nodeCount > 10 || hasLoopNodes || hasIterationNodes) {
    estimatedComplexity = 'high';
  } else if (nodeCount > 5 || hasIfElseNodes || (hasAgentNodes && hasLLMNodes)) {
    estimatedComplexity = 'medium';
  }

  return {
    nodeCount,
    edgeCount,
    hasAgentNodes,
    hasLLMNodes,
    estimatedComplexity,
  };
}
