/**
 * Simple Shell Script Generator for flowsh
 *
 * Generates clean, readable shell scripts from workflows.
 * Focus: Simplicity, readability, and scripts under 100 lines.
 */

import { FlowshWorkflow, WorkflowNode, WorkflowEdge } from '../dsl/types.js';

export interface GenerationOptions {
  /** Include mock implementations for testing */
  includeMocks?: boolean;
  /** Shell type to target */
  shell?: 'bash' | 'zsh';
  /** Include verbose debugging output */
  verbose?: boolean;
  /** Default timeout for agent calls */
  defaultTimeout?: number;
}

export interface GenerationResult {
  /** Generated shell script content */
  script: string;
  /** Generation success status */
  success: boolean;
  /** Any warnings during generation */
  warnings: string[];
  /** Metadata about the generated script */
  metadata: {
    nodeCount: number;
    edgeCount: number;
    hasAgentNodes: boolean;
    hasLLMNodes: boolean;
    estimatedComplexity: 'low' | 'medium' | 'high';
  };
}

/**
 * Generate a simple, clean shell script from workflow
 */
export function generateShellScript(
  workflow: FlowshWorkflow,
  options: GenerationOptions = {}
): GenerationResult {
  const warnings: string[] = [];

  // Get workflow graph
  const graph = workflow.graph ?? workflow.spec?.graph;
  if (!graph || !graph.nodes || graph.nodes.length === 0) {
    return {
      script: '',
      success: false,
      warnings: ['No workflow graph found or graph is empty'],
      metadata: {
        nodeCount: 0,
        edgeCount: 0,
        hasAgentNodes: false,
        hasLLMNodes: false,
        estimatedComplexity: 'low',
      },
    };
  }

  const nodes = graph.nodes;
  const edges = graph.edges || [];

  // Analyze workflow
  const hasAgentNodes = nodes.some(n => n.type === 'agent');
  const hasLLMNodes = nodes.some(n => n.type === 'llm');

  // Generate script parts
  const scriptParts: string[] = [];

  // Header
  scriptParts.push(generateHeader(workflow, options));

  // Variable setup
  scriptParts.push(generateVariableSetup(nodes));

  // Main execution
  scriptParts.push(generateMainExecution(nodes, edges, options));

  // Footer
  scriptParts.push(generateFooter());

  const script = scriptParts.join('\n\n');

  return {
    script,
    success: true,
    warnings,
    metadata: {
      nodeCount: nodes.length,
      edgeCount: edges.length,
      hasAgentNodes,
      hasLLMNodes,
      estimatedComplexity: nodes.length > 10 ? 'high' : nodes.length > 5 ? 'medium' : 'low',
    },
  };
}

/**
 * Generate clean script header
 */
function generateHeader(workflow: FlowshWorkflow, options: GenerationOptions): string {
  const name = workflow.metadata?.name || 'workflow';
  const shell = options.shell === 'zsh' ? 'zsh' : 'bash';

  return `#!/bin/${shell}
set -euo pipefail

# ${name} - Generated by flowsh
# Simple workflow execution script

echo "Starting workflow: ${name}"`;
}

/**
 * Generate variable setup section
 */
function generateVariableSetup(nodes: WorkflowNode[]): string {
  const variables: string[] = [];

  // Extract variables from nodes
  for (const node of nodes) {
    if (node.type === 'variable-assignment' && 'variable' in node.data) {
      const varName = node.data.variable.toUpperCase();
      const defaultValue = 'value' in node.data ? String(node.data.value) || '' : '';
      variables.push(`${varName}=\${${varName}:-"${defaultValue}"}`);
    }

    // Extract template variables from command strings
    if ('command' in node.data && node.data.command) {
      const matches = node.data.command.match(/\{\{(\w+)\}\}/g);
      if (matches) {
        for (const match of matches) {
          const varName = match.replace(/\{\{|\}\}/g, '').toUpperCase();
          if (!variables.some(v => v.startsWith(varName))) {
            variables.push(`${varName}=\${${varName}:-""}`);
          }
        }
      }
    }
  }

  if (variables.length === 0) {
    return '';
  }

  return `# Environment Variables\n${variables.join('\n')}`;
}

/**
 * Generate main execution logic
 */
function generateMainExecution(
  nodes: WorkflowNode[],
  _edges: WorkflowEdge[],
  options: GenerationOptions
): string {
  const executionSteps: string[] = [];

  // Simple linear execution for now (ignore complex control flow)
  const executableNodes = nodes.filter(n => n.type !== 'start' && n.type !== 'end');

  executionSteps.push('# Workflow Execution');

  for (const node of executableNodes) {
    const step = generateNodeExecution(node, options);
    if (step) {
      executionSteps.push('');
      executionSteps.push(`# Node: ${node.id}`);
      executionSteps.push(step);
    }
  }

  return executionSteps.join('\n');
}

/**
 * Generate execution for a single node
 */
function generateNodeExecution(node: WorkflowNode, _options: GenerationOptions): string {
  switch (node.type) {
    case 'code':
      return generateCodeNode(node);
    case 'agent':
      return generateAgentNode(node, _options);
    case 'llm':
      return generateLLMNode(node, _options);
    case 'variable-assignment':
      return generateVariableNode(node);
    case 'if-else':
      return generateIfElseNode(node);
    default:
      return `echo "Executing ${node.type} node: ${node.id}"`;
  }
}

/**
 * Generate code node execution
 */
function generateCodeNode(node: WorkflowNode): string {
  const command =
    'command' in node.data && node.data.command ? node.data.command : 'echo "No command specified"';

  // Replace template variables
  const processedCommand = command.replace(/\{\{(\w+)\}\}/g, (_: string, varName: string) => {
    return `$${varName.toUpperCase()}`;
  });

  return processedCommand;
}

/**
 * Generate agent node execution
 */
function generateAgentNode(node: WorkflowNode, options: GenerationOptions): string {
  const command =
    'command' in node.data && node.data.command ? node.data.command : 'echo "No command"';

  if (options.includeMocks) {
    return `echo "Mock agent: ${command}"`;
  }

  // Simple agent execution
  return command;
}

/**
 * Generate LLM node execution
 */
function generateLLMNode(node: WorkflowNode, options: GenerationOptions): string {
  const model = 'model' in node.data && node.data.model ? String(node.data.model) : 'gpt-4';
  const prompt = 'prompt' in node.data && node.data.prompt ? String(node.data.prompt) : 'Hello';

  if (options.includeMocks) {
    return `echo "Mock LLM Response for: ${prompt}"`;
  }

  // Simple curl-based LLM call
  return `curl -s -X POST "https://api.openai.com/v1/chat/completions" \\
  -H "Authorization: Bearer $OPENAI_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"model": "${model}", "messages": [{"role": "user", "content": "${prompt}"}]}'`;
}

/**
 * Generate variable assignment
 */
function generateVariableNode(node: WorkflowNode): string {
  const variable = 'variable' in node.data && node.data.variable ? node.data.variable : 'TEMP_VAR';
  const value = 'value' in node.data && node.data.value ? String(node.data.value) : '';

  return `${variable.toUpperCase()}="${value}"`;
}

/**
 * Generate if-else logic
 */
function generateIfElseNode(_node: WorkflowNode): string {
  // Simple condition for now
  const condition = 'true';

  return `if ${condition}; then
  echo "Condition passed"
else
  echo "Condition failed"
fi`;
}

/**
 * Generate script footer
 */
function generateFooter(): string {
  return `echo "Workflow completed successfully"
exit 0`;
}
