#!/bin/bash
set -euo pipefail

# Multi-Format Content Distribution - Cross-Channel Syndication - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: Multi-Format Content Distribution - Cross-Channel Syndication"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
CONTENT_TITLE=${CONTENT_TITLE:-""}
CONTENT_BODY=${CONTENT_BODY:-""}
EMAIL_CONTENT=${EMAIL_CONTENT:-""}
TELEGRAM_CONTENT=${TELEGRAM_CONTENT:-""}
WEBHOOK_CONTENT=${WEBHOOK_CONTENT:-""}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-""}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-""}
TELEGRAM_SUCCESS=${TELEGRAM_SUCCESS:-""}
TELEGRAM_HTTP_CODE=${TELEGRAM_HTTP_CODE:-""}
TELEGRAM_RESPONSE=${TELEGRAM_RESPONSE:-""}
TELEGRAM_MESSAGE_SENT=${TELEGRAM_MESSAGE_SENT:-""}
TELEGRAM_ERROR=${TELEGRAM_ERROR:-""}
WEBHOOK_URL=${WEBHOOK_URL:-""}
HTTP_STATUS_CODE=${HTTP_STATUS_CODE:-""}
HTTP_RESPONSE_BODY=${HTTP_RESPONSE_BODY:-""}
HTTP_RESPONSE_TIME=${HTTP_RESPONSE_TIME:-""}
HTTP_RESPONSE_SIZE=${HTTP_RESPONSE_SIZE:-""}
HTTP_EFFECTIVE_URL=${HTTP_EFFECTIVE_URL:-""}
HTTP_REQUEST_METHOD=${HTTP_REQUEST_METHOD:-""}
HTTP_SUCCESS=${HTTP_SUCCESS:-""}
HTTP_ERROR=${HTTP_ERROR:-""}
SUCCESS_RATE=${SUCCESS_RATE:-""}
CONTENT_PRIORITY=${CONTENT_PRIORITY:-""}
TARGET_PLATFORMS=${TARGET_PLATFORMS:-""}
ENABLE_TRACKING=${ENABLE_TRACKING:-""}
DISTRIBUTION_REPORT=${DISTRIBUTION_REPORT:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    
    # First check workflow_vars array
    local workflow_value="${workflow_vars[$var_name]:-}"
    if [[ -n "$workflow_value" ]]; then
        echo "$workflow_value"
        return
    fi
    
    # Fallback to environment variable (uppercase version)
    local env_var_name="${var_name^^}"  # Convert to uppercase
    local env_value="${!env_var_name:-}"
    if [[ -n "$env_value" ]]; then
        echo "$env_value"
        return
    fi
    
    # Finally use default value
    echo "$default_value"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Temporary file management
declare -a FLOWSH_TEMP_FILES=()

register_temp_file() {
    local temp_path="$1"
    FLOWSH_TEMP_FILES+=("$temp_path")
    log_debug "Registered temp file: $temp_path"
}

cleanup_temp_files() {
    local cleaned_count=0
    local failed_count=0
    
    for temp_file in "${FLOWSH_TEMP_FILES[@]}"; do
        if [[ -e "$temp_file" ]]; then
            if rm -rf "$temp_file" 2>/dev/null; then
                ((cleaned_count++))
                log_debug "Cleaned up temp file: $temp_file"
            else
                ((failed_count++))
                log_warning "Failed to clean up temp file: $temp_file"
            fi
        fi
    done
    
    # Clear the temp files array
    FLOWSH_TEMP_FILES=()
    
    if [[ $cleaned_count -gt 0 ]]; then
        log_info "Cleaned up $cleaned_count temporary files"
    fi
    
    if [[ $failed_count -gt 0 ]]; then
        log_warning "Failed to clean up $failed_count temporary files"
    fi
    
    return 0
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Process tracking for parallel execution
declare -a FLOWSH_ACTIVE_PIDS=()

register_process() {
    local pid="$1"
    local description="${2:-unknown}"
     
     # Use case statement instead of regex for PID validation
     case "$pid" in
         ''|*[!0-9]*) log_warning "Invalid PID for registration: $pid" ;;
         *)
             FLOWSH_ACTIVE_PIDS+=("$pid")
             log_debug "Registered process $pid: $description"
             ;;
     esac
}

unregister_process() {
    local pid="$1"
    local new_pids=()
    
    for active_pid in "${FLOWSH_ACTIVE_PIDS[@]}"; do
        if [[ "$active_pid" != "$pid" ]]; then
            new_pids+=("$active_pid")
        fi
    done
    
    FLOWSH_ACTIVE_PIDS=("${new_pids[@]}")
    log_debug "Unregistered process $pid"
}

# Mock circuit breaker operation for testing
execute_circuit_breaker_operation() {
    local timeout_seconds="${1:-30}"
    local failure_threshold="${2:-3}"
    log_info "Mock circuit breaker operation (timeout: ${timeout_seconds}s, threshold: ${failure_threshold})"
    
    # Simulate circuit breaker with 25% failure rate
    if [[ $((RANDOM % 4)) -eq 0 ]]; then
        log_warning "Mock circuit breaker: operation failed (simulated failure)"
        return 1
    else
        sleep 2
        log_success "Mock circuit breaker: operation succeeded"
        return 0
    fi
}

# Mock retry command execution
execute_retry_command() {
    local attempt_number="${1:-1}"
    local max_attempts="${2:-3}"
    log_info "Mock retry command execution (attempt $attempt_number/$max_attempts)"
    
    # Simulate work
    sleep 1
    
    # Simulate success after 2 attempts for realistic retry testing
    if [[ $attempt_number -ge 2 ]]; then
        log_success "Mock retry command: succeeded after $attempt_number attempts"
        return 0
    else
        log_warning "Mock retry command: failed on attempt $attempt_number"
        return 1
    fi
}

# Mock sequential iteration processing
execute_iteration_iterate_files_sequential() {
    local pattern="${1:-*}"
    log_info "Mock sequential iteration: processing files matching '$pattern'"
    
    # Simulate file processing
    sleep 0.5
    local files=("file1.txt" "file2.txt" "file3.txt")
    
    for file in "${files[@]}"; do
        log_info "Processing file: $file"
        sleep 0.5
    done
    
    log_success "Sequential iteration completed: processed ${#files[@]} files"
    return 0
}

# Mock fallback path execution for testing
execute_fallback_path() {
    local path_id="${1}"
    log_info "Mock fallback path execution: $path_id"
    
    # Simulate work
    sleep 1
    
    # Simulate success for primary_service_call, failure for others to test fallback behavior
    case "$path_id" in
        "primary_service_call")
            log_success "Primary service call succeeded"
            return 0
            ;;
        "secondary_service_call") 
            log_warning "Secondary service call failed"
            return 1
            ;;
        "cache_fallback_call")
            log_warning "Cache fallback failed"
            return 1
            ;;
        "default_response_call")
            log_success "Default response call succeeded"
            return 0
            ;;
        *)
            log_info "Unknown fallback path succeeded: $path_id"
            return 0
            ;;
    esac
}

# Workflow Execution

# Node: initialize_distribution
/bin/bash -c "set -euo pipefail
echo \"📡 Initializing Multi-Format Content Distribution...\"

# Configuration validation
TITLE=\"\$(get_var "CONTENT_TITLE" "initialize_distribution")\"
BODY=\"\$(get_var "CONTENT_BODY" "initialize_distribution")\"
PLATFORMS=\"\${TARGET_PLATFORMS:-email,telegram,webhook}\"
PRIORITY=\"\${CONTENT_PRIORITY:-medium}\"
TRACKING=\"\${ENABLE_TRACKING:-true}\"

echo \"🔧 Distribution Configuration:\"
echo \"  Title: \${TITLE:0:50}\${TITLE:50:+...}\"
echo \"  Content Length: \${#BODY} characters\"
echo \"  Target Platforms: \\\$PLATFORMS\"
echo \"  Priority Level: \\\$PRIORITY\"
echo \"  Delivery Tracking: \\\$TRACKING\"

# Create distribution workspace
mkdir -p /tmp/content_distribution
mkdir -p /tmp/content_distribution/formats
mkdir -p /tmp/content_distribution/delivery
mkdir -p /tmp/content_distribution/tracking

# Initialize content files
echo \"\\\$TITLE\" > /tmp/content_distribution/title.txt
echo \"\\\$BODY\" > /tmp/content_distribution/body.txt

# Parse target platforms
echo \"\\\$PLATFORMS\" | tr ',' '\\n' > /tmp/content_distribution/target_platforms.txt

# Initialize tracking
echo '{\"distribution_id\":\"'\$(date +%s)'\",\"platforms\":{},\"started\":\"'\$(date -Iseconds)'\"}' > /tmp/content_distribution/tracking/distribution_log.json

# Set priority-based delivery settings
case \"\\\$PRIORITY\" in
  \"urgent\")
    echo '{\"timeout\":5,\"retry_attempts\":3,\"parallel_delivery\":true}' > /tmp/content_distribution/delivery_config.json
    ;;
  \"high\")
    echo '{\"timeout\":10,\"retry_attempts\":2,\"parallel_delivery\":true}' > /tmp/content_distribution/delivery_config.json
    ;;
  \"medium\")
    echo '{\"timeout\":15,\"retry_attempts\":1,\"parallel_delivery\":false}' > /tmp/content_distribution/delivery_config.json
    ;;
  \"low\")
    echo '{\"timeout\":30,\"retry_attempts\":1,\"parallel_delivery\":false}' > /tmp/content_distribution/delivery_config.json
    ;;
  *)
    echo '{\"timeout\":15,\"retry_attempts\":1,\"parallel_delivery\":false}' > /tmp/content_distribution/delivery_config.json
    ;;
esac

echo \"✅ Distribution system initialized successfully\"
"

# Node: format_for_email

# Node: format_for_email (Format Content for Email)
execute_template_transform_format_for_email() {
    log_step "🔧 Template Transform: Format Content for Email"

    local output_var="email_content"
    local template_content=""

    # Inline template content
    template_content=''
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # No template parameters configured
    log_debug "No template parameters to process"

    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node format_for_email
process_template_functions_format_for_email() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_format_for_email "$1"
}
execute_template_transform_format_for_email

# Node: format_for_telegram

# Node: format_for_telegram (Format Content for Telegram)
execute_template_transform_format_for_telegram() {
    log_step "🔧 Template Transform: Format Content for Telegram"

    local output_var="telegram_content"
    local template_content=""

    # Inline template content
    template_content=''
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # No template parameters configured
    log_debug "No template parameters to process"

    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node format_for_telegram
process_template_functions_format_for_telegram() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_format_for_telegram "$1"
}
execute_template_transform_format_for_telegram

# Node: format_for_webhook

# Node: format_for_webhook (Format Content for Webhook)
execute_template_transform_format_for_webhook() {
    log_step "🔧 Template Transform: Format Content for Webhook"

    local output_var="webhook_content"
    local template_content=""

    # Inline template content
    template_content=''
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # No template parameters configured
    log_debug "No template parameters to process"

    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node format_for_webhook
process_template_functions_format_for_webhook() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_format_for_webhook "$1"
}
execute_template_transform_format_for_webhook

# Node: save_formatted_content
/bin/bash -c "set -euo pipefail
echo \"💾 Saving formatted content for all platforms...\"

FORMATS_DIR=\"/tmp/content_distribution/formats\"

# Save formatted content for each platform
echo \"\$(get_var "EMAIL_CONTENT" "save_formatted_content")\" > \"\\\$FORMATS_DIR/email_format.txt\"
echo \"\$(get_var "TELEGRAM_CONTENT" "save_formatted_content")\" > \"\\\$FORMATS_DIR/telegram_format.txt\"
echo \"\$(get_var "WEBHOOK_CONTENT" "save_formatted_content")\" > \"\\\$FORMATS_DIR/webhook_format.json\"

# Validate JSON format for webhook
if ! jq . \"\\\$FORMATS_DIR/webhook_format.json\" >/dev/null 2>&1; then
  echo \"❌ Invalid JSON format for webhook\"
  echo '{\"error\":\"invalid_json_format\",\"title\":\"'\$(get_var "CONTENT_TITLE" "save_formatted_content")'\",\"content\":\"'\$(get_var "CONTENT_BODY" "save_formatted_content")'\"}' > \"\\\$FORMATS_DIR/webhook_format.json\"
fi

echo \"📊 Formatted Content Summary:\"
echo \"  Email format: \$(wc -l < \"\\\$FORMATS_DIR/email_format.txt\") lines\"
echo \"  Telegram format: \$(wc -c < \"\\\$FORMATS_DIR/telegram_format.txt\") characters\"
echo \"  Webhook format: \$(jq -c . \"\\\$FORMATS_DIR/webhook_format.json\" | wc -c) bytes\"

echo \"✅ All content formats saved successfully\"
"

# Node: deliver_to_email
/bin/bash -c "set -euo pipefail
echo \"📧 Delivering content via email...\"

EMAIL_RECIPIENT=\"\${EMAIL_RECIPIENT:-}\"
PLATFORMS_FILE=\"/tmp/content_distribution/target_platforms.txt\"

# Check if email is in target platforms
if ! grep -q \"email\" \"\\\$PLATFORMS_FILE\"; then
  echo \"ℹ️ Email not in target platforms - skipping\"
  echo '{\"platform\":\"email\",\"status\":\"skipped\",\"reason\":\"not_in_targets\"}' > /tmp/content_distribution/delivery/email_result.json
  exit 0
fi

if [ -z \"\\\$EMAIL_RECIPIENT\" ]; then
  echo \"⚠️ No email recipient configured\"
  echo '{\"platform\":\"email\",\"status\":\"failed\",\"reason\":\"no_recipient\"}' > /tmp/content_distribution/delivery/email_result.json
  exit 0
fi

EMAIL_CONTENT=\$(cat /tmp/content_distribution/formats/email_format.txt)
SUBJECT=\"\$(get_var "CONTENT_TITLE" "deliver_to_email")\"

echo \"📤 Sending email to: \\\$EMAIL_RECIPIENT\"
echo \"📋 Subject: \\\$SUBJECT\"

# Simulate email delivery (in production, use actual email service)
# This would typically use sendmail, mail command, or email service API
DELIVERY_TIME=\$(date -Iseconds)

# Mock email delivery success/failure
if [[ \"\\\$EMAIL_RECIPIENT\" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\\$ ]]; then
  echo \"✅ Email delivered successfully\"
  EMAIL_STATUS=\"delivered\"
  EMAIL_ERROR=\"\"
else
  echo \"❌ Email delivery failed - invalid email format\"
  EMAIL_STATUS=\"failed\"
  EMAIL_ERROR=\"invalid_email_format\"
fi

# Save delivery result
cat > /tmp/content_distribution/delivery/email_result.json <<EOF
{
  \"platform\": \"email\",
  \"status\": \"\\\$EMAIL_STATUS\",
  \"recipient\": \"\\\$EMAIL_RECIPIENT\",
  \"subject\": \"\\\$SUBJECT\",
  \"delivery_time\": \"\\\$DELIVERY_TIME\",
  \"error\": \"\\\$EMAIL_ERROR\",
  \"content_length\": \${#EMAIL_CONTENT}
}
EOF

echo \"📬 Email delivery process complete\"
"

# Node: deliver_to_telegram

# Node: deliver_to_telegram (Deliver Content via Telegram)
execute_telegram_deliver_to_telegram() {
    log_step "📱 Sending Telegram message: Deliver Content via Telegram"

    local message="$(get_var "TELEGRAM_CONTENT" "deliver_to_telegram")"
    local parse_mode="Markdown"
    local max_retries=3
    local disable_notification=false
    local error_handling="fail"
    

    # Validate message is not empty
    if [[ -z "$message" ]]; then
        log_error "Telegram message content is empty"
        case "$error_handling" in
            "ignore")
                log_info "Ignoring Telegram error as configured"
                return 0
                ;;
            "continue")
                log_warning "Continuing despite Telegram error"
                return 0
                ;;
            *)
                return 1
                ;;
        esac
    fi

    # Use chat_id from node configuration
    local chat_id="$(get_var "TELEGRAM_CHAT_ID" "deliver_to_telegram")"

    # Use bot_token from node configuration
    local bot_token="$(get_var "TELEGRAM_BOT_TOKEN" "deliver_to_telegram")"

    # Character escaping functions for Telegram
    escape_json() {
        local text="$1"
        # Escape characters that would break JSON payload
        text="${text//\\/\\\\}"  # Escape backslashes first
        text="${text//"/\\"}"      # Escape double quotes
        text="${text//$'\n'/\\n}"  # Escape newlines
        text="${text//$'\r'/\\r}"  # Escape carriage returns
        text="${text//$'\t'/\\t}"  # Escape tabs
        echo "$text"
    }

    escape_markdown() {
        local text="$1"
        # Escape special MarkdownV2 characters
        text="${text//_/\_}"
        text="${text//*/\*}"
        text="${text//[/\[}"
        text="${text//]/\]}"
        text="${text//(/\(}"
        text="${text//)/\)}"
        text="${text//~/\~}"
        text="${text//\`/\\\`}"
        text="${text//>/\>}"
        text="${text//#/\#}"
        text="${text//+/\+}"
        text="${text//-/\-}"
        text="${text//=/\=}"
        text="${text//|/\|}"
        text="${text//\{/\\{}"
        text="${text//\}/\\}}"
        text="${text//./\.}"
        text="${text//!/\!}"
        echo "$text"
     }

    # Escape message content for JSON payload (but preserve formatting tags)
    local escaped_message
    case "$parse_mode" in
        "HTML")
            # For HTML mode, only escape JSON special characters, not HTML formatting tags
            escaped_message=$(escape_json "$message")
            ;;
        "Markdown"|"MarkdownV2")
            # For Markdown modes, escape markdown then JSON
            local markdown_escaped
            markdown_escaped=$(escape_markdown "$message")
            escaped_message=$(escape_json "$markdown_escaped")
            ;;
        *)
            escaped_message=$(escape_json "$message")
            ;;
    esac

    # Prepare API request payload
    local api_url="https://api.telegram.org/bot$bot_token/sendMessage"
    local payload
    payload=$(cat <<EOF
{
    "chat_id": "$chat_id",
    "text": "$escaped_message",
    "parse_mode": "$parse_mode"
}
EOF
)

    log_debug "Sending message to Telegram API: $api_url"
    log_debug "Payload length: ${#payload} characters"

    # Retry logic with exponential backoff
    local attempt=1
    local delay=1
    
    while [[ $attempt -le $max_retries ]]; do
        log_debug "Telegram API attempt $attempt of $max_retries"
        
        # Make API request
        local response_file=$(mktemp)
        local http_code
        
        http_code=$(curl -s -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            --connect-timeout 10 \
            --max-time 30 \
            "$api_url" \
            -o "$response_file" 2>/dev/null)
        
        local curl_exit_code=$?
        local response_body=$(cat "$response_file" 2>/dev/null)
        
        # Clean up temp file
        rm -f "$response_file" 2>/dev/null
        
        # Check if request was successful
        if [[ $curl_exit_code -eq 0 && "$http_code" =~ ^2[0-9][0-9]$ ]]; then
            log_success "Telegram message sent successfully (HTTP $http_code)"
            
            # Set success variables
            set_workflow_var "telegram_success" "true"
            set_workflow_var "telegram_http_code" "$http_code"
            set_workflow_var "telegram_response" "$response_body"
            set_workflow_var "telegram_message_sent" "true"
            
            log_debug "Telegram API response: $response_body"
            return 0
        else
            # Log the failure
            if [[ $curl_exit_code -ne 0 ]]; then
                log_warning "Telegram API request failed (curl exit code: $curl_exit_code) - attempt $attempt/$max_retries"
            else
                log_warning "Telegram API returned HTTP $http_code - attempt $attempt/$max_retries"
                if [[ -n "$response_body" ]]; then
                    log_warning "API error response: $response_body"
                fi
            fi
            
            # Check if we should retry
            if [[ $attempt -lt $max_retries ]]; then
                log_info "Retrying in ${delay}s..."
                sleep $delay
                delay=$((delay * 2))  # Exponential backoff
                attempt=$((attempt + 1))
            else
                # Final failure - handle based on error_handling setting
                log_error "Telegram message failed after $max_retries attempts"
                
                # Set failure variables
                set_workflow_var "telegram_success" "false"
                set_workflow_var "telegram_http_code" "${http_code:-0}"
                set_workflow_var "telegram_response" "$response_body"
                set_workflow_var "telegram_message_sent" "false"
                set_workflow_var "telegram_error" "MAX_RETRIES_EXCEEDED"
                
                case "$error_handling" in
                    "ignore")
                        log_info "Ignoring Telegram failure as configured"
                        return 0
                        ;;
                    "continue")
                        log_warning "Continuing despite Telegram failure"
                        return 0
                        ;;
                    *)
                        return 1
                        ;;
                esac
            fi
        fi
    done
}
execute_telegram_deliver_to_telegram

# Node: deliver_to_webhook (ERROR)
echo "Error generating node deliver_to_webhook: Failed to generate code for node 'deliver_to_webhook': headers.trim is not a function"

# Node: collect_delivery_results
/bin/bash -c "set -euo pipefail
echo \"📊 Collecting delivery results from all platforms...\"

DELIVERY_DIR=\"/tmp/content_distribution/delivery\"
TRACKING_DIR=\"/tmp/content_distribution/tracking\"

# Initialize results summary
TOTAL_PLATFORMS=0
SUCCESSFUL_DELIVERIES=0
FAILED_DELIVERIES=0
SKIPPED_DELIVERIES=0

# Collect email results
if [ -f \"\\\$DELIVERY_DIR/email_result.json\" ]; then
  EMAIL_STATUS=\$(jq -r '.status' \"\\\$DELIVERY_DIR/email_result.json\")
  case \"\\\$EMAIL_STATUS\" in
    \"delivered\") SUCCESSFUL_DELIVERIES=\$((SUCCESSFUL_DELIVERIES + 1)) ;;
    \"failed\") FAILED_DELIVERIES=\$((FAILED_DELIVERIES + 1)) ;;
    \"skipped\") SKIPPED_DELIVERIES=\$((SKIPPED_DELIVERIES + 1)) ;;
  esac
  TOTAL_PLATFORMS=\$((TOTAL_PLATFORMS + 1))
  echo \"📧 Email: \\\$EMAIL_STATUS\"
fi

# Collect Telegram results
if grep -q \"telegram\" /tmp/content_distribution/target_platforms.txt; then
  if [ \"\${TELEGRAM_SUCCESS:-false}\" = \"true\" ]; then
    TELEGRAM_STATUS=\"delivered\"
    SUCCESSFUL_DELIVERIES=\$((SUCCESSFUL_DELIVERIES + 1))
  elif [ -n \"\${TELEGRAM_BOT_TOKEN:-}\" ] && [ -n \"\${TELEGRAM_CHAT_ID:-}\" ]; then
    TELEGRAM_STATUS=\"failed\"
    FAILED_DELIVERIES=\$((FAILED_DELIVERIES + 1))
  else
    TELEGRAM_STATUS=\"skipped\"
    SKIPPED_DELIVERIES=\$((SKIPPED_DELIVERIES + 1))
  fi
  TOTAL_PLATFORMS=\$((TOTAL_PLATFORMS + 1))
  echo \"💬 Telegram: \\\$TELEGRAM_STATUS\"
fi

# Collect Webhook results
if grep -q \"webhook\" /tmp/content_distribution/target_platforms.txt; then
  if [ \"\${http_response_code:-0}\" -ge 200 ] && [ \"\${http_response_code:-0}\" -lt 300 ]; then
    WEBHOOK_STATUS=\"delivered\"
    SUCCESSFUL_DELIVERIES=\$((SUCCESSFUL_DELIVERIES + 1))
  elif [ -n \"\${WEBHOOK_URL:-}\" ]; then
    WEBHOOK_STATUS=\"failed\"
    FAILED_DELIVERIES=\$((FAILED_DELIVERIES + 1))
  else
    WEBHOOK_STATUS=\"skipped\"
    SKIPPED_DELIVERIES=\$((SKIPPED_DELIVERIES + 1))
  fi
  TOTAL_PLATFORMS=\$((TOTAL_PLATFORMS + 1))
  echo \"🔗 Webhook: \\\$WEBHOOK_STATUS\"
fi

# Calculate success rate
if [ \"\\\$TOTAL_PLATFORMS\" -gt 0 ]; then
  SUCCESS_RATE=\$(echo \"scale=1; \\\$SUCCESSFUL_DELIVERIES * 100 / \\\$TOTAL_PLATFORMS\" | bc -l || echo \"0.0\")
else
  SUCCESS_RATE=\"0.0\"
fi

echo \"📈 Delivery Summary:\"
echo \"  Total Platforms: \\\$TOTAL_PLATFORMS\"
echo \"  Successful: \\\$SUCCESSFUL_DELIVERIES\"
echo \"  Failed: \\\$FAILED_DELIVERIES\"
echo \"  Skipped: \\\$SKIPPED_DELIVERIES\"
echo \"  Success Rate: \$(get_var "SUCCESS_RATE" "collect_delivery_results")%\"

# Update tracking log
cat > \"\\\$TRACKING_DIR/final_report.json\" <<EOF
{
  \"distribution_id\": \"\$(jq -r '.distribution_id' \"\\\$TRACKING_DIR/distribution_log.json\")\",
  \"content_title\": \"\$(get_var "CONTENT_TITLE" "collect_delivery_results")\",
  \"priority\": \"\$(get_var "CONTENT_PRIORITY" "collect_delivery_results")\",
  \"target_platforms\": \"\$(get_var "TARGET_PLATFORMS" "collect_delivery_results")\",
  \"delivery_summary\": {
    \"total_platforms\": \\\$TOTAL_PLATFORMS,
    \"successful_deliveries\": \\\$SUCCESSFUL_DELIVERIES,
    \"failed_deliveries\": \\\$FAILED_DELIVERIES,
    \"skipped_deliveries\": \\\$SKIPPED_DELIVERIES,
    \"success_rate\": \\\$SUCCESS_RATE
  },
  \"platform_results\": {
    \"email\": \"\$(jq -r '.status // \"not_attempted\"' \"\\\$DELIVERY_DIR/email_result.json\" 2>/dev/null || echo \"not_attempted\")\",
    \"telegram\": \"\${TELEGRAM_STATUS:-not_attempted}\",
    \"webhook\": \"\${WEBHOOK_STATUS:-not_attempted}\"
  },
  \"completed_at\": \"\$(date -Iseconds)\",
  \"tracking_enabled\": \$(get_var "ENABLE_TRACKING" "collect_delivery_results")
}
EOF

echo \"✅ Delivery results collected and tracking updated\"
"

# Node: generate_distribution_report

# Node: generate_distribution_report (Generate Distribution Report)
execute_template_transform_generate_distribution_report() {
    log_step "🔧 Template Transform: Generate Distribution Report"

    local output_var="distribution_report"
    local template_content=""

    # Inline template content
    template_content=''
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # No template parameters configured
    log_debug "No template parameters to process"

    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node generate_distribution_report
process_template_functions_generate_distribution_report() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_generate_distribution_report "$1"
}
execute_template_transform_generate_distribution_report

# Node: final_distribution_summary
echo "# 📡 Multi-Format Content Distribution - DISTRIBUTION COMPLETE!

## 🚀 Distribution Overview
Successfully processed content through multi-format distribution pipeline:
- **Content Formatting**: Adapted content for email, Telegram, and webhook formats
- **Platform Delivery**: Distributed across $(jq -r '.delivery_summary.total_platforms' /tmp/content_distribution/tracking/final_report.json) target platforms
- **Delivery Tracking**: Monitored success/failure rates with comprehensive reporting
- **Format Optimization**: Platform-specific content adaptation and formatting

## 📊 Distribution Results
**Overall Success Rate**: $(jq -r '.delivery_summary.success_rate' /tmp/content_distribution/tracking/final_report.json)%
**Total Deliveries**: $(jq -r '.delivery_summary.successful_deliveries' /tmp/content_distribution/tracking/final_report.json) successful, $(jq -r '.delivery_summary.failed_deliveries' /tmp/content_distribution/tracking/final_report.json) failed, $(jq -r '.delivery_summary.skipped_deliveries' /tmp/content_distribution/tracking/final_report.json) skipped

## 📈 Platform Performance
- **📧 Email Distribution**: $(jq -r '.platform_results.email' /tmp/content_distribution/tracking/final_report.json | tr '[:lower:]' '[:upper:]')
- **💬 Telegram Messaging**: $(jq -r '.platform_results.telegram' /tmp/content_distribution/tracking/final_report.json | tr '[:lower:]' '[:upper:]')
- **🔗 Webhook Integration**: $(jq -r '.platform_results.webhook' /tmp/content_distribution/tracking/final_report.json | tr '[:lower:]' '[:upper:]')

## 📋 Detailed Distribution Report
$(get_var "DISTRIBUTION_REPORT" "final_distribution_summary")

## ⚡ Advanced Features Demonstrated
- **Multi-Format Adaptation**: Intelligent content formatting for each platform
- **Priority-Based Delivery**: Configurable timeouts and retry logic based on content priority
- **Real-time Tracking**: Comprehensive delivery monitoring and success rate calculation
- **Platform Integration**: Native support for email, Telegram, and webhook distribution
- **Error Handling**: Graceful failure handling with detailed error reporting
- **Conditional Delivery**: Smart platform selection based on configuration and availability

## 🔧 Production Capabilities
- **Scalable Architecture**: Handles multiple platforms and high-volume content distribution
- **Flexible Configuration**: Environment-driven platform selection and priority settings
- **Comprehensive Logging**: Detailed audit trail for compliance and troubleshooting
- **Format Extensibility**: Easy addition of new platforms and content formats
- **Delivery Reliability**: Retry mechanisms and failure recovery for critical content
- **Performance Monitoring**: Success rates and delivery time tracking across platforms

## 🎯 Cross-Channel Features
- **Unified Content Management**: Single source content adapted for multiple channels
- **Platform-Specific Optimization**: Format customization for optimal platform experience
- **Centralized Tracking**: Consolidated delivery monitoring across all channels
- **Conditional Distribution**: Smart routing based on platform availability and configuration
- **Priority Handling**: Urgent content gets faster delivery and more retry attempts
- **Compliance Ready**: Audit trails and delivery confirmations for regulatory requirements

## ✅ Template Validation Status
- **Multi-Platform Integration**: ✅ Email, Telegram, and Webhook distribution
- **Content Formatting**: ✅ Platform-specific content adaptation
- **Delivery Tracking**: ✅ Comprehensive success/failure monitoring
- **Production Ready**: ✅ Enterprise-grade distribution pipeline
- **Error Resilience**: ✅ Graceful handling of platform failures and configuration issues

**Final Status**: 🎯 **ADVANCED DISTRIBUTION PIPELINE COMPLETE** - Production-ready cross-channel content syndication deployed
"

echo "Workflow completed successfully"
exit 0
