#!/bin/bash
# Test Script v4 - Production Ready
# Generated by flowsh v1.0.0 
# Source: Agent Workflow Example

set -euo pipefail

# Workflow variables
declare -A workflow_vars

# Control flags for testing
USE_MOCK_TOOLS=${USE_MOCK_TOOLS:-true}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}
VERBOSE=${VERBOSE:-false}

# Logging functions
log_info() {
    echo "ℹ️  $*"
}

log_success() {
    echo "✅ $*"
}

log_error() {
    echo "❌ $*" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo "🔍 DEBUG: $*" >&2
}

# Mock opencode command for testing
mock_opencode() {
    log_info "Mock opencode called with prompt:"
    echo "---"
    local prompt="$1"
    echo "${prompt:0:100}..." # Show first 100 chars
    echo "---"
    
    # Simulate some processing time
    sleep 2
    
    log_success "Mock agent completed task successfully"
    return 0
}

# Mock make command for testing  
mock_make() {
    local target="$1"
    case "$target" in
        "test")
            log_info "Running tests..."
            sleep 1
            
            # Simulate random test results for demo
            if [[ $((RANDOM % 10)) -gt 7 ]]; then
                log_error "Some tests failed"
                return 1
            else
                log_success "All tests passed"
                return 0
            fi
            ;;
        "build")
            log_info "Building project..."
            sleep 2
            log_success "Build completed"
            return 0
            ;;
        *)
            log_error "Unknown make target: $target"
            return 1
            ;;
    esac
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s"
            ;;
        127)
            log_error "Command not found in: $context"
            ;;
        1)
            log_error "General error in: $context"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context"
            ;;
    esac
    
    return $exit_code
}

# Initialize workflow
init_workflow() {
    workflow_vars["task_description"]="${1:-}"
    workflow_vars["project_path"]="${2:-}"
    
    [[ -z "${workflow_vars["task_description"]}" ]] && {
        log_error "task_description is required"
        echo "Usage: $0 'task description' /path/to/project" >&2
        exit 1
    }
    [[ -z "${workflow_vars["project_path"]}" ]] && {
        log_error "project_path is required"
        echo "Usage: $0 'task description' /path/to/project" >&2
        exit 1
    }
    
    # Validate project path exists
    [[ ! -d "${workflow_vars["project_path"]}" ]] && {
        log_error "project_path '${workflow_vars["project_path"]}' does not exist"
        exit 1
    }
    
    # Ensure project path is readable
    [[ ! -r "${workflow_vars["project_path"]}" ]] && {
        log_error "project_path '${workflow_vars["project_path"]}' is not readable"
        exit 1
    }
    
    log_success "Workflow initialized successfully"
    log_info "Task: ${workflow_vars["task_description"]}"
    log_info "Project: ${workflow_vars["project_path"]}"
    log_info "Mock mode: $USE_MOCK_TOOLS"
    log_debug "Agent timeout: ${AGENT_TIMEOUT}s"
}

# Execute agent node: code_agent
execute_agent_node_code_agent() {
    log_info "🚀 Running Code Agent..."
    
    # Resolve template from registry
    local template_content
    if ! template_content=$(resolve_template "task-planner" "library"); then
        log_error "Failed to resolve template 'task-planner'"
        return 1
    fi
    
    local prompt
    if ! prompt=$(render_template "$template_content" "${workflow_vars["task_description"]}"); then
        log_error "Failed to render template"
        return 1
    fi
    
    log_debug "Generated prompt length: ${#prompt} characters"
    
    # Call agent CLI tool with proper error handling
    local agent_exit_code=0
    if [[ "$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock opencode"
        mock_opencode "$prompt" || agent_exit_code=$?
    elif command -v opencode >/dev/null 2>&1; then
        log_debug "Using real opencode with timeout ${AGENT_TIMEOUT}s"
        timeout "$AGENT_TIMEOUT" opencode run "$prompt" || agent_exit_code=$?
        
        # Handle timeout gracefully
        if [[ $agent_exit_code -eq 124 ]]; then
            log_error "opencode timed out after ${AGENT_TIMEOUT}s, falling back to mock"
            mock_opencode "$prompt" || agent_exit_code=$?
        fi
    else
        log_info "opencode not found, falling back to mock"
        mock_opencode "$prompt" || agent_exit_code=$?
    fi
    
    if [[ $agent_exit_code -ne 0 ]]; then
        handle_error $agent_exit_code "Code Agent execution"
        return $agent_exit_code
    fi
    
    log_success "Code agent completed successfully"
}

# Execute code node: validate_code
execute_code_node_validate_code() {
    log_info "🔍 Running validation..."
    
    # Change to project directory safely
    local original_dir
    original_dir=$(pwd)
    
    if ! cd "${workflow_vars["project_path"]}"; then
        log_error "Failed to change to project directory"
        return 1
    fi
    
    log_debug "Changed to directory: $(pwd)"
    
    # Execute validation command
    local exit_code=0
    if [[ "$USE_MOCK_TOOLS" == "true" ]]; then
        log_debug "Using mock make"
        mock_make "test" || exit_code=$?
    elif command -v make >/dev/null 2>&1 && [[ -f "Makefile" ]]; then
        log_debug "Using real make"
        make test || exit_code=$?
    elif command -v npm >/dev/null 2>&1 && [[ -f "package.json" ]]; then
        log_debug "Using npm test as fallback"
        npm test || exit_code=$?
    else
        log_info "No make/npm found or no Makefile/package.json, using mock"
        mock_make "test" || exit_code=$?
    fi
    
    # Return to original directory
    cd "$original_dir" || {
        log_error "Failed to return to original directory"
        return 1
    }
    
    # Handle success/failure routing
    if [[ $exit_code -eq 0 ]]; then
        log_success "Validation passed - proceeding to deploy"
        execute_node_deploy
    else
        log_error "Validation failed - proceeding to fix issues"
        execute_node_fix_issues
    fi
}

# Deploy node implementation
execute_node_deploy() {
    log_info "🚀 Deploying application..."
    log_info "   - Building production assets..."
    sleep 1
    log_info "   - Uploading to server..."
    sleep 1
    log_info "   - Running health checks..."
    sleep 1
    log_success "Deployment completed successfully"
}

# Fix issues node implementation
execute_node_fix_issues() {
    log_info "🔧 Fixing issues..."
    log_info "   - Analyzing test failures..."
    sleep 1
    log_info "   - Applying automated fixes..."
    sleep 1
    log_info "   - Running validation again..."
    sleep 1
    log_success "Issues fixed, ready for re-validation"
    
    # Optionally re-run validation
    if [[ "${AUTO_RETRY:-false}" == "true" ]]; then
        log_info "Auto-retry enabled, re-running validation..."
        execute_code_node_validate_code
    fi
}

# Template resolution helper with better error handling
resolve_template() {
    local template_id="$1"
    local source="${2:-library}"
    
    log_debug "Resolving template: $template_id from $source"
    
    case "$template_id" in
        "task-planner")
            cat <<'TEMPLATE'
You are a task planner. Break down this task: {{task_description}}

Create actionable steps and implement them systematically.
Focus on:
1. Understanding requirements
2. Breaking down into subtasks  
3. Implementation planning
4. Testing strategy

Keep your response concise and actionable.
TEMPLATE
            ;;
        "code-reviewer")
            cat <<'TEMPLATE'
Review and analyze this task: {{task_description}}

Provide feedback on:
1. Code quality and best practices
2. Potential security issues
3. Performance considerations
4. Testing coverage
TEMPLATE
            ;;
        *)
            log_error "Unknown template '$template_id'"
            return 1
            ;;
    esac
}

# Template rendering helper with validation
render_template() {
    local template="$1"
    local task_description="$2"
    
    # Validate inputs
    [[ -z "$template" ]] && {
        log_error "Template content is empty"
        return 1
    }
    [[ -z "$task_description" ]] && {
        log_error "Task description is empty"
        return 1
    }
    
    # Escape special characters in task_description for sed
    local escaped_task
    escaped_task=$(printf '%s\n' "$task_description" | sed 's/[[\.*^$()+?{|]/\\&/g')
    
    echo "$template" | sed "s|{{task_description}}|$escaped_task|g"
}

# Health check function
health_check() {
    log_info "Running system health check..."
    
    # Check required commands based on mode
    if [[ "$USE_MOCK_TOOLS" != "true" ]]; then
        local missing_tools=()
        
        command -v opencode >/dev/null 2>&1 || missing_tools+=("opencode")
        command -v make >/dev/null 2>&1 || missing_tools+=("make")
        
        if [[ ${#missing_tools[@]} -gt 0 ]]; then
            log_info "Missing tools (will use mocks): ${missing_tools[*]}"
        else
            log_success "All required tools available"
        fi
    fi
    
    # Check system resources
    local available_memory
    if command -v free >/dev/null 2>&1; then
        available_memory=$(free -m | awk 'NR==2{printf "%.1f%%\n", $3*100/$2}')
        log_debug "Memory usage: $available_memory"
    fi
}

# Main execution
main() {
    health_check
    init_workflow "$@"
    execute_agent_node_code_agent
    execute_code_node_validate_code
}

# Usage help
show_usage() {
    cat <<EOF
flowsh Agent Workflow Script v4

Usage: $0 [OPTIONS] 'task description' /path/to/project

Options:
  --no-mock         Use real tools instead of mocks
  --timeout SECS    Set agent timeout in seconds (default: 60)
  --verbose         Enable verbose debug output
  --auto-retry      Auto-retry validation after fixing issues
  --help            Show this help message

Environment Variables:
  USE_MOCK_TOOLS    Set to 'false' to use real tools (default: true)
  AGENT_TIMEOUT     Agent timeout in seconds (default: 60)
  VERBOSE           Set to 'true' for debug output (default: false)
  AUTO_RETRY        Set to 'true' to auto-retry validation (default: false)

Examples:
  $0 "Implement user auth" /path/to/project
  $0 --no-mock --verbose "Fix bug in API" /path/to/project
  USE_MOCK_TOOLS=false VERBOSE=true $0 "Add tests" /path/to/project
EOF
}

# Parse arguments with better error handling
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-mock)
            USE_MOCK_TOOLS=false
            shift
            ;;
        --timeout)
            [[ -n "${2:-}" ]] || {
                log_error "--timeout requires a value"
                exit 1
            }
            [[ "$2" =~ ^[0-9]+$ ]] || {
                log_error "Timeout must be a positive integer"
                exit 1
            }
            AGENT_TIMEOUT="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --auto-retry)
            AUTO_RETRY=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        -*)
            log_error "Unknown option: $1"
            show_usage >&2
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

# Run if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi