#!/bin/bash
set -euo pipefail

# agent-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: agent-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
TASK_DESCRIPTION=${TASK_DESCRIPTION:-"Create a simple text file with current system information"}
OUTPUT_FORMAT=${OUTPUT_FORMAT:-"detailed"}
SAFETY_MODE=${SAFETY_MODE:-"true"}
AGENT_INSTRUCTIONS=${AGENT_INSTRUCTIONS:-""}
AGENT_SYSTEM_INFO_AGENT_OUTPUT=${AGENT_SYSTEM_INFO_AGENT_OUTPUT:-""}
AGENT_SYSTEM_INFO_AGENT_EXIT_CODE=${AGENT_SYSTEM_INFO_AGENT_EXIT_CODE:-""}
AGENT_SYSTEM_INFO_AGENT_SUCCESS=${AGENT_SYSTEM_INFO_AGENT_SUCCESS:-""}
AGENT_FILE_OPERATIONS_AGENT_OUTPUT=${AGENT_FILE_OPERATIONS_AGENT_OUTPUT:-""}
AGENT_FILE_OPERATIONS_AGENT_EXIT_CODE=${AGENT_FILE_OPERATIONS_AGENT_EXIT_CODE:-""}
AGENT_FILE_OPERATIONS_AGENT_SUCCESS=${AGENT_FILE_OPERATIONS_AGENT_SUCCESS:-""}
AGENT_VALIDATION_AGENT_OUTPUT=${AGENT_VALIDATION_AGENT_OUTPUT:-""}
AGENT_VALIDATION_AGENT_EXIT_CODE=${AGENT_VALIDATION_AGENT_EXIT_CODE:-""}
AGENT_VALIDATION_AGENT_SUCCESS=${AGENT_VALIDATION_AGENT_SUCCESS:-""}
AGENT_CLEANUP_AGENT_OUTPUT=${AGENT_CLEANUP_AGENT_OUTPUT:-""}
AGENT_CLEANUP_AGENT_EXIT_CODE=${AGENT_CLEANUP_AGENT_EXIT_CODE:-""}
AGENT_CLEANUP_AGENT_SUCCESS=${AGENT_CLEANUP_AGENT_SUCCESS:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    
    # First check workflow_vars array
    local workflow_value="${workflow_vars[$var_name]:-}"
    if [[ -n "$workflow_value" ]]; then
        echo "$workflow_value"
        return
    fi
    
    # Fallback to environment variable (uppercase version)
    local env_var_name="${var_name^^}"  # Convert to uppercase
    local env_value="${!env_var_name:-}"
    if [[ -n "$env_value" ]]; then
        echo "$env_value"
        return
    fi
    
    # Finally use default value
    echo "$default_value"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Temporary file management
declare -a FLOWSH_TEMP_FILES=()

register_temp_file() {
    local temp_path="$1"
    FLOWSH_TEMP_FILES+=("$temp_path")
    log_debug "Registered temp file: $temp_path"
}

cleanup_temp_files() {
    local cleaned_count=0
    local failed_count=0
    
    for temp_file in "${FLOWSH_TEMP_FILES[@]}"; do
        if [[ -e "$temp_file" ]]; then
            if rm -rf "$temp_file" 2>/dev/null; then
                ((cleaned_count++))
                log_debug "Cleaned up temp file: $temp_file"
            else
                ((failed_count++))
                log_warning "Failed to clean up temp file: $temp_file"
            fi
        fi
    done
    
    # Clear the temp files array
    FLOWSH_TEMP_FILES=()
    
    if [[ $cleaned_count -gt 0 ]]; then
        log_info "Cleaned up $cleaned_count temporary files"
    fi
    
    if [[ $failed_count -gt 0 ]]; then
        log_warning "Failed to clean up $failed_count temporary files"
    fi
    
    return 0
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Process tracking for parallel execution
declare -a FLOWSH_ACTIVE_PIDS=()

register_process() {
    local pid="$1"
    local description="${2:-unknown}"
     
     # Use case statement instead of regex for PID validation
     case "$pid" in
         ''|*[!0-9]*) log_warning "Invalid PID for registration: $pid" ;;
         *)
             FLOWSH_ACTIVE_PIDS+=("$pid")
             log_debug "Registered process $pid: $description"
             ;;
     esac
}

unregister_process() {
    local pid="$1"
    local new_pids=()
    
    for active_pid in "${FLOWSH_ACTIVE_PIDS[@]}"; do
        if [[ "$active_pid" != "$pid" ]]; then
            new_pids+=("$active_pid")
        fi
    done
    
    FLOWSH_ACTIVE_PIDS=("${new_pids[@]}")
    log_debug "Unregistered process $pid"
}

# Mock circuit breaker operation for testing
execute_circuit_breaker_operation() {
    local timeout_seconds="${1:-30}"
    local failure_threshold="${2:-3}"
    log_info "Mock circuit breaker operation (timeout: ${timeout_seconds}s, threshold: ${failure_threshold})"
    
    # Simulate circuit breaker with 25% failure rate
    if [[ $((RANDOM % 4)) -eq 0 ]]; then
        log_warning "Mock circuit breaker: operation failed (simulated failure)"
        return 1
    else
        sleep 2
        log_success "Mock circuit breaker: operation succeeded"
        return 0
    fi
}

# Mock retry command execution
execute_retry_command() {
    local attempt_number="${1:-1}"
    local max_attempts="${2:-3}"
    log_info "Mock retry command execution (attempt $attempt_number/$max_attempts)"
    
    # Simulate work
    sleep 1
    
    # Simulate success after 2 attempts for realistic retry testing
    if [[ $attempt_number -ge 2 ]]; then
        log_success "Mock retry command: succeeded after $attempt_number attempts"
        return 0
    else
        log_warning "Mock retry command: failed on attempt $attempt_number"
        return 1
    fi
}

# Mock sequential iteration processing
execute_iteration_iterate_files_sequential() {
    local pattern="${1:-*}"
    log_info "Mock sequential iteration: processing files matching '$pattern'"
    
    # Simulate file processing
    sleep 0.5
    local files=("file1.txt" "file2.txt" "file3.txt")
    
    for file in "${files[@]}"; do
        log_info "Processing file: $file"
        sleep 0.5
    done
    
    log_success "Sequential iteration completed: processed ${#files[@]} files"
    return 0
}

# Mock fallback path execution for testing
execute_fallback_path() {
    local path_id="${1}"
    log_info "Mock fallback path execution: $path_id"
    
    # Simulate work
    sleep 1
    
    # Simulate success for primary_service_call, failure for others to test fallback behavior
    case "$path_id" in
        "primary_service_call")
            log_success "Primary service call succeeded"
            return 0
            ;;
        "secondary_service_call") 
            log_warning "Secondary service call failed"
            return 1
            ;;
        "cache_fallback_call")
            log_warning "Cache fallback failed"
            return 1
            ;;
        "default_response_call")
            log_success "Default response call succeeded"
            return 0
            ;;
        *)
            log_info "Unknown fallback path succeeded: $path_id"
            return 0
            ;;
    esac
}

# Workflow Execution

# Node: prepare_agent_prompt
# Node: prepare_agent_prompt
AGENT_INSTRUCTIONS=$(echo 'Task: $(get_workflow_var "TASK_DESCRIPTION" "default"). Format: $(get_workflow_var "OUTPUT_FORMAT" "default"). Safety: $(get_workflow_var "SAFETY_MODE" "default"). Generate safe shell commands only.')
set_var "AGENT_INSTRUCTIONS" "$AGENT_INSTRUCTIONS" "prepare_agent_prompt"

# Node: system_info_agent
# Node: system_info_agent (System Information Agent)
execute_agent_system_info_agent() {
    log_step "🤖 Executing agent: System Information Agent"

    local original_dir="$PWD"
    local working_dir="/tmp"
    if [[ -d "$working_dir" ]]; then
        cd "$working_dir" || { log_error "Failed to change to directory: $working_dir"; return 1; }
        log_debug "Changed to working directory: $working_dir"
    else
        log_warning "Working directory does not exist, using current: $working_dir"
    fi

    # Set up environment variables
    export AGENT_TASK="$(get_var "TASK_DESCRIPTION" "system_info_agent")"
    export OUTPUT_FORMAT="$(get_var "OUTPUT_FORMAT" "system_info_agent")"
    export SAFETY_MODE="$(get_var "SAFETY_MODE" "system_info_agent")"

    # Prepare agent prompt
    local prompt_content
    read -r -d '' prompt_content << AGENT_PROMPT_EOF || true
You are a helpful system administrator agent. Your task is to generate safe shell commands to complete the user's request.

User Request: $(get_var "TASK_DESCRIPTION" "system_info_agent")
Output Format: $(get_var "OUTPUT_FORMAT" "system_info_agent")
Safety Mode: $(get_var "SAFETY_MODE" "system_info_agent")

Guidelines:
- Only use safe, read-only commands if safety_mode is true
- Generate commands that gather system information
- Format output according to the requested format
- Avoid any destructive operations
- Use common Unix/Linux commands (ls, cat, date, whoami, uname, etc.)

Generate a single shell command or pipe chain to complete this task safely.

AGENT_PROMPT_EOF

    # Execute agent command
    local exit_code=0
    local agent_output=""

    # Execute with 30s timeout
    if command -v timeout >/dev/null 2>&1; then
        agent_output=$(timeout 30 sh -c "$prompt_content" 2>&1) || exit_code=$?
    else
        # Fallback for systems without timeout command
        agent_output=$(sh -c "$prompt_content" 2>&1) || exit_code=$?
    fi

    # Store agent execution results
    set_workflow_var "agent_system_info_agent_output" "$agent_output"
    set_workflow_var "agent_system_info_agent_exit_code" "$exit_code"
    set_workflow_var "agent_system_info_agent_success" "false"

    # Handle execution result
    if [[ $exit_code -eq 0 ]]; then
        set_workflow_var "agent_system_info_agent_success" "true"
        log_success "Agent execution completed successfully"
        echo "$agent_output"
    else
        case $exit_code in
            124)
                log_error "Agent execution timed out after 30s"
                ;;
            127)
                log_error "Agent command not found: sh"
                ;;
            *)
                log_error "Agent execution failed with exit code: $exit_code"
                ;;
        esac
        echo "$agent_output" >&2
    fi

    # Restore original directory
    if [[ -n "${original_dir:-}" ]]; then
        cd "$original_dir" || log_warning "Failed to restore original directory"
    fi

    return $exit_code
}

# Execute agent function
execute_agent_system_info_agent
execute_agent_system_info_agent

# Node: file_operations_agent
# Node: file_operations_agent (File Operations Agent)
execute_agent_file_operations_agent() {
    log_step "🤖 Executing agent: File Operations Agent"

    local original_dir="$PWD"
    local working_dir="/tmp"
    if [[ -d "$working_dir" ]]; then
        cd "$working_dir" || { log_error "Failed to change to directory: $working_dir"; return 1; }
        log_debug "Changed to working directory: $working_dir"
    else
        log_warning "Working directory does not exist, using current: $working_dir"
    fi

    # Prepare agent prompt
    local prompt_content
    read -r -d '' prompt_content << AGENT_PROMPT_EOF || true
You are a file operations specialist agent. Create safe commands for file manipulation.

Context: The previous agent completed: $(get_var "TASK_DESCRIPTION" "file_operations_agent")

Your task: Create a summary file of the system information gathered.
- Create a file at /tmp/agent-example-output.txt
- Include timestamp and basic system info
- Use only safe file operations (echo, cat, date, etc.)
- Make the output $(get_var "OUTPUT_FORMAT" "file_operations_agent") format

Generate the appropriate shell commands to create this summary file.

AGENT_PROMPT_EOF

    # Execute agent command
    local exit_code=0
    local agent_output=""

    # Execute with 20s timeout
    if command -v timeout >/dev/null 2>&1; then
        agent_output=$(timeout 20 sh -c "$prompt_content" 2>&1) || exit_code=$?
    else
        # Fallback for systems without timeout command
        agent_output=$(sh -c "$prompt_content" 2>&1) || exit_code=$?
    fi

    # Store agent execution results
    set_workflow_var "agent_file_operations_agent_output" "$agent_output"
    set_workflow_var "agent_file_operations_agent_exit_code" "$exit_code"
    set_workflow_var "agent_file_operations_agent_success" "false"

    # Handle execution result
    if [[ $exit_code -eq 0 ]]; then
        set_workflow_var "agent_file_operations_agent_success" "true"
        log_success "Agent execution completed successfully"
        echo "$agent_output"
    else
        case $exit_code in
            124)
                log_error "Agent execution timed out after 20s"
                ;;
            127)
                log_error "Agent command not found: sh"
                ;;
            *)
                log_error "Agent execution failed with exit code: $exit_code"
                ;;
        esac
        echo "$agent_output" >&2
    fi

    # Restore original directory
    if [[ -n "${original_dir:-}" ]]; then
        cd "$original_dir" || log_warning "Failed to restore original directory"
    fi

    return $exit_code
}

# Execute agent function
execute_agent_file_operations_agent
execute_agent_file_operations_agent

# Node: validation_agent
# Node: validation_agent (Output Validation Agent)
execute_agent_validation_agent() {
    log_step "🤖 Executing agent: Output Validation Agent"

    local original_dir="$PWD"
    local working_dir="/tmp"
    if [[ -d "$working_dir" ]]; then
        cd "$working_dir" || { log_error "Failed to change to directory: $working_dir"; return 1; }
        log_debug "Changed to working directory: $working_dir"
    else
        log_warning "Working directory does not exist, using current: $working_dir"
    fi

    # Prepare agent prompt
    local prompt_content
    read -r -d '' prompt_content << AGENT_PROMPT_EOF || true
You are a validation agent. Your job is to verify the output file exists and display its contents appropriately.

Task: Check if /tmp/agent-example-output.txt exists and display it
Format: $(get_var "OUTPUT_FORMAT" "validation_agent")

Commands to generate:
1. Check if the file exists
2. Display its contents with appropriate formatting
3. Add a validation timestamp

Use commands like: test -f, cat, echo, date

AGENT_PROMPT_EOF

    # Execute agent command
    local exit_code=0
    local agent_output=""

    # Execute with 10s timeout
    if command -v timeout >/dev/null 2>&1; then
        agent_output=$(timeout 10 sh -c "$prompt_content" 2>&1) || exit_code=$?
    else
        # Fallback for systems without timeout command
        agent_output=$(sh -c "$prompt_content" 2>&1) || exit_code=$?
    fi

    # Store agent execution results
    set_workflow_var "agent_validation_agent_output" "$agent_output"
    set_workflow_var "agent_validation_agent_exit_code" "$exit_code"
    set_workflow_var "agent_validation_agent_success" "false"

    # Handle execution result
    if [[ $exit_code -eq 0 ]]; then
        set_workflow_var "agent_validation_agent_success" "true"
        log_success "Agent execution completed successfully"
        echo "$agent_output"
    else
        case $exit_code in
            124)
                log_error "Agent execution timed out after 10s"
                ;;
            127)
                log_error "Agent command not found: sh"
                ;;
            *)
                log_error "Agent execution failed with exit code: $exit_code"
                ;;
        esac
        echo "$agent_output" >&2
    fi

    # Restore original directory
    if [[ -n "${original_dir:-}" ]]; then
        cd "$original_dir" || log_warning "Failed to restore original directory"
    fi

    return $exit_code
}

# Execute agent function
execute_agent_validation_agent
execute_agent_validation_agent

# Node: cleanup_agent
# Node: cleanup_agent (Cleanup Agent)
execute_agent_cleanup_agent() {
    log_step "🤖 Executing agent: Cleanup Agent"

    local original_dir="$PWD"
    local working_dir="/tmp"
    if [[ -d "$working_dir" ]]; then
        cd "$working_dir" || { log_error "Failed to change to directory: $working_dir"; return 1; }
        log_debug "Changed to working directory: $working_dir"
    else
        log_warning "Working directory does not exist, using current: $working_dir"
    fi

    # Prepare agent prompt
    local prompt_content
    read -r -d '' prompt_content << AGENT_PROMPT_EOF || true
You are a cleanup agent. Generate commands to safely clean up the temporary files created during this workflow.

Files to clean:
- /tmp/agent-example-output.txt
- Any other temporary files created

Safety requirements:
- Only remove files we created in /tmp/agent-example-*
- Use safe removal commands
- Confirm files exist before removing

Generate the appropriate cleanup commands.

AGENT_PROMPT_EOF

    # Execute agent command
    local exit_code=0
    local agent_output=""

    # Execute with 10s timeout
    if command -v timeout >/dev/null 2>&1; then
        agent_output=$(timeout 10 sh -c "$prompt_content" 2>&1) || exit_code=$?
    else
        # Fallback for systems without timeout command
        agent_output=$(sh -c "$prompt_content" 2>&1) || exit_code=$?
    fi

    # Store agent execution results
    set_workflow_var "agent_cleanup_agent_output" "$agent_output"
    set_workflow_var "agent_cleanup_agent_exit_code" "$exit_code"
    set_workflow_var "agent_cleanup_agent_success" "false"

    # Handle execution result
    if [[ $exit_code -eq 0 ]]; then
        set_workflow_var "agent_cleanup_agent_success" "true"
        log_success "Agent execution completed successfully"
        echo "$agent_output"
    else
        case $exit_code in
            124)
                log_error "Agent execution timed out after 10s"
                ;;
            127)
                log_error "Agent command not found: sh"
                ;;
            *)
                log_error "Agent execution failed with exit code: $exit_code"
                ;;
        esac
        echo "$agent_output" >&2
    fi

    # Restore original directory
    if [[ -n "${original_dir:-}" ]]; then
        cd "$original_dir" || log_warning "Failed to restore original directory"
    fi

    return $exit_code
}

# Execute agent function
execute_agent_cleanup_agent
execute_agent_cleanup_agent

# Node: final_report
echo "# 🤖 Agent Node Example Completed!

## Task Executed
**Original Request**: $(get_var "TASK_DESCRIPTION" "final_report")
**Output Format**: $(get_var "OUTPUT_FORMAT" "final_report")
**Safety Mode**: $(get_var "SAFETY_MODE" "final_report")

## Agent Operations Performed

1. **System Information Agent** 🔍
   - Generated commands to gather system information
   - Executed safely with proper environment setup
   - Followed safety guidelines based on user preferences

2. **File Operations Agent** 📝
   - Created summary files with collected information
   - Used template-driven command generation
   - Maintained proper working directory isolation

3. **Validation Agent** ✅
   - Verified output file creation and contents
   - Applied requested formatting standards
   - Performed final validation checks

4. **Cleanup Agent** 🧹
   - Safely removed temporary files
   - Followed cleanup best practices
   - Ensured no resource leaks

## Agent Node Features Demonstrated

- **AI-Powered Command Generation**: Agents dynamically create shell commands based on natural language instructions
- **Template System Integration**: Inline prompt templates with parameter substitution
- **Context Awareness**: Agents can reference previous operations and maintain workflow context
- **Safety Controls**: Built-in safety modes to restrict dangerous operations
- **Environment Management**: Proper working directory and environment variable handling
- **Specialized Roles**: Different agents for different types of operations (info gathering, file ops, validation, cleanup)
- **Timeout Management**: Appropriate timeouts for different complexity tasks

This example demonstrates how agent nodes can provide intelligent, AI-assisted automation while maintaining safety and control.
"

echo "Workflow completed successfully"
exit 0
