#!/bin/bash
set -euo pipefail

# answer-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: answer-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
USER_NAME=${USER_NAME:-""}
OUTPUT_FORMAT=${OUTPUT_FORMAT:-""}
INCLUDE_DETAILS=${INCLUDE_DETAILS:-""}
CURRENT_TIMESTAMP=${CURRENT_TIMESTAMP:-""}
SAMPLE_COUNT=${SAMPLE_COUNT:-""}
STATUS_MESSAGE=${STATUS_MESSAGE:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: calculate_stats
set_var "CURRENT_TIMESTAMP" "" "calculate_stats"

# Node: generate_data
set_var "SAMPLE_COUNT" "" "generate_data"

# Node: create_status
set_var "STATUS_MESSAGE" "Processing completed successfully" "create_status"

# Node: format_decision
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: text_answer
echo "Hello ${user_name}!

Answer Node Example - Text Format

Generated Statistics:
- Timestamp: ${current_timestamp}
- Sample Count: ${sample_count}
- Status: ${status_message}
- Details Included: ${include_details}

This demonstrates a basic text answer node with variable interpolation.
"

# Node: json_check
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: json_answer
echo "{
  "greeting": "Hello ${user_name}!",
  "workflow": {
    "name": "Answer Node Example",
    "format": "${output_format}",
    "timestamp": "${current_timestamp}"
  },
  "results": {
    "sample_count": ${sample_count},
    "status": "${status_message}",
    "include_details": ${include_details}
  },
  "metadata": {
    "node_type": "answer",
    "format_type": "json",
    "generated_by": "flowsh"
  }
}
"

# Node: markdown_answer
echo "# 🎯 Answer Node Example Results

**Hello ${user_name}!** Welcome to the flowsh answer node demonstration.

## 📊 Generated Statistics

| Metric | Value |
|--------|-------|
| **Timestamp** | `${current_timestamp}` |
| **Sample Count** | `${sample_count}` |
| **Status** | ✅ ${status_message} |
| **Details Included** | ${include_details} |

## 📝 About This Example

This answer node demonstrates:
- **Variable Interpolation**: Using `${variable_name}` syntax
- **Markdown Formatting**: Rich text with headers, tables, and emojis
- **Conditional Logic**: Different outputs based on user preferences
- **Type Safety**: Proper typing for different answer formats

---

*Generated by flowsh workflow engine at ${current_timestamp}*
"

echo "Workflow completed successfully"
exit 0
