#!/bin/bash
set -euo pipefail

# answer-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: answer-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
USER_NAME=${USER_NAME:-"User"}
OUTPUT_FORMAT=${OUTPUT_FORMAT:-"markdown"}
INCLUDE_DETAILS=${INCLUDE_DETAILS:-"true"}
CURRENT_TIMESTAMP=${CURRENT_TIMESTAMP:-""}
SAMPLE_COUNT=${SAMPLE_COUNT:-""}
STATUS_MESSAGE=${STATUS_MESSAGE:-""}
VARIABLE_NAME=${VARIABLE_NAME:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    
    # First check workflow_vars array
    local workflow_value="${workflow_vars[$var_name]:-}"
    if [[ -n "$workflow_value" ]]; then
        echo "$workflow_value"
        return
    fi
    
    # Fallback to environment variable (uppercase version)
    local env_var_name="${var_name^^}"  # Convert to uppercase
    local env_value="${!env_var_name:-}"
    if [[ -n "$env_value" ]]; then
        echo "$env_value"
        return
    fi
    
    # Finally use default value
    echo "$default_value"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Temporary file management
declare -a FLOWSH_TEMP_FILES=()

register_temp_file() {
    local temp_path="$1"
    FLOWSH_TEMP_FILES+=("$temp_path")
    log_debug "Registered temp file: $temp_path"
}

cleanup_temp_files() {
    local cleaned_count=0
    local failed_count=0
    
    for temp_file in "${FLOWSH_TEMP_FILES[@]}"; do
        if [[ -e "$temp_file" ]]; then
            if rm -rf "$temp_file" 2>/dev/null; then
                ((cleaned_count++))
                log_debug "Cleaned up temp file: $temp_file"
            else
                ((failed_count++))
                log_warning "Failed to clean up temp file: $temp_file"
            fi
        fi
    done
    
    # Clear the temp files array
    FLOWSH_TEMP_FILES=()
    
    if [[ $cleaned_count -gt 0 ]]; then
        log_info "Cleaned up $cleaned_count temporary files"
    fi
    
    if [[ $failed_count -gt 0 ]]; then
        log_warning "Failed to clean up $failed_count temporary files"
    fi
    
    return 0
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Process tracking for parallel execution
declare -a FLOWSH_ACTIVE_PIDS=()

register_process() {
    local pid="$1"
    local description="${2:-unknown}"
     
     # Use case statement instead of regex for PID validation
     case "$pid" in
         ''|*[!0-9]*) log_warning "Invalid PID for registration: $pid" ;;
         *)
             FLOWSH_ACTIVE_PIDS+=("$pid")
             log_debug "Registered process $pid: $description"
             ;;
     esac
}

unregister_process() {
    local pid="$1"
    local new_pids=()
    
    for active_pid in "${FLOWSH_ACTIVE_PIDS[@]}"; do
        if [[ "$active_pid" != "$pid" ]]; then
            new_pids+=("$active_pid")
        fi
    done
    
    FLOWSH_ACTIVE_PIDS=("${new_pids[@]}")
    log_debug "Unregistered process $pid"
}

# Mock circuit breaker operation for testing
execute_circuit_breaker_operation() {
    local timeout_seconds="${1:-30}"
    local failure_threshold="${2:-3}"
    log_info "Mock circuit breaker operation (timeout: ${timeout_seconds}s, threshold: ${failure_threshold})"
    
    # Simulate circuit breaker with 25% failure rate
    if [[ $((RANDOM % 4)) -eq 0 ]]; then
        log_warning "Mock circuit breaker: operation failed (simulated failure)"
        return 1
    else
        sleep 2
        log_success "Mock circuit breaker: operation succeeded"
        return 0
    fi
}

# Mock retry command execution
execute_retry_command() {
    local attempt_number="${1:-1}"
    local max_attempts="${2:-3}"
    log_info "Mock retry command execution (attempt $attempt_number/$max_attempts)"
    
    # Simulate work
    sleep 1
    
    # Simulate success after 2 attempts for realistic retry testing
    if [[ $attempt_number -ge 2 ]]; then
        log_success "Mock retry command: succeeded after $attempt_number attempts"
        return 0
    else
        log_warning "Mock retry command: failed on attempt $attempt_number"
        return 1
    fi
}

# Mock sequential iteration processing
execute_iteration_iterate_files_sequential() {
    local pattern="${1:-*}"
    log_info "Mock sequential iteration: processing files matching '$pattern'"
    
    # Simulate file processing
    sleep 0.5
    local files=("file1.txt" "file2.txt" "file3.txt")
    
    for file in "${files[@]}"; do
        log_info "Processing file: $file"
        sleep 0.5
    done
    
    log_success "Sequential iteration completed: processed ${#files[@]} files"
    return 0
}

# Mock fallback path execution for testing
execute_fallback_path() {
    local path_id="${1}"
    log_info "Mock fallback path execution: $path_id"
    
    # Simulate work
    sleep 1
    
    # Simulate success for primary_service_call, failure for others to test fallback behavior
    case "$path_id" in
        "primary_service_call")
            log_success "Primary service call succeeded"
            return 0
            ;;
        "secondary_service_call") 
            log_warning "Secondary service call failed"
            return 1
            ;;
        "cache_fallback_call")
            log_warning "Cache fallback failed"
            return 1
            ;;
        "default_response_call")
            log_success "Default response call succeeded"
            return 0
            ;;
        *)
            log_info "Unknown fallback path succeeded: $path_id"
            return 0
            ;;
    esac
}

# Workflow Execution

# Node: calculate_stats
# Node: calculate_stats
CURRENT_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
set_var "CURRENT_TIMESTAMP" "$CURRENT_TIMESTAMP" "calculate_stats"

# Node: generate_data
# Node: generate_data
SAMPLE_COUNT=$(echo $((RANDOM % 100 + 1)))
set_var "SAMPLE_COUNT" "$SAMPLE_COUNT" "generate_data"

# Node: create_status
set_var "STATUS_MESSAGE" "Processing completed successfully" "create_status"

# Node: format_decision
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: text_answer
echo "Hello $(get_var "USER_NAME" "text_answer")!

Answer Node Example - Text Format

Generated Statistics:
- Timestamp: $(get_var "CURRENT_TIMESTAMP" "text_answer")
- Sample Count: $(get_var "SAMPLE_COUNT" "text_answer")
- Status: $(get_var "STATUS_MESSAGE" "text_answer")
- Details Included: $(get_var "INCLUDE_DETAILS" "text_answer")

This demonstrates a basic text answer node with variable interpolation.
"

# Node: json_check
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: json_answer
echo "{
  "greeting": "Hello $(get_var "USER_NAME" "json_answer")!",
  "workflow": {
    "name": "Answer Node Example",
    "format": "$(get_var "OUTPUT_FORMAT" "json_answer")",
    "timestamp": "$(get_var "CURRENT_TIMESTAMP" "json_answer")"
  },
  "results": {
    "sample_count": $(get_var "SAMPLE_COUNT" "json_answer"),
    "status": "$(get_var "STATUS_MESSAGE" "json_answer")",
    "include_details": $(get_var "INCLUDE_DETAILS" "json_answer")
  },
  "metadata": {
    "node_type": "answer",
    "format_type": "json",
    "generated_by": "flowsh"
  }
}
"

# Node: markdown_answer
echo "# 🎯 Answer Node Example Results

**Hello $(get_var "USER_NAME" "markdown_answer")!** Welcome to the flowsh answer node demonstration.

## 📊 Generated Statistics

| Metric | Value |
|--------|-------|
| **Timestamp** | `$(get_var "CURRENT_TIMESTAMP" "markdown_answer")` |
| **Sample Count** | `$(get_var "SAMPLE_COUNT" "markdown_answer")` |
| **Status** | ✅ $(get_var "STATUS_MESSAGE" "markdown_answer") |
| **Details Included** | $(get_var "INCLUDE_DETAILS" "markdown_answer") |

## 📝 About This Example

This answer node demonstrates:
- **Variable Interpolation**: Using `$(get_var "VARIABLE_NAME" "markdown_answer")` syntax
- **Markdown Formatting**: Rich text with headers, tables, and emojis
- **Conditional Logic**: Different outputs based on user preferences
- **Type Safety**: Proper typing for different answer formats

---

*Generated by flowsh workflow engine at $(get_var "CURRENT_TIMESTAMP" "markdown_answer")*
"

echo "Workflow completed successfully"
exit 0
