#!/bin/bash
set -euo pipefail

# fallback-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: fallback-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
PRIMARY_SERVICE_URL=${PRIMARY_SERVICE_URL:-"https://primary-api.example.com"}
FALLBACK_STRATEGY=${FALLBACK_STRATEGY:-"sequential"}
MAX_FALLBACK_TIME=${MAX_FALLBACK_TIME:-"120"}
CONTINUE_ON_SUCCESS=${CONTINUE_ON_SUCCESS:-"false"}
FAILURE_SIMULATION=${FAILURE_SIMULATION:-"primary_fail"}
FALLBACK_ATTEMPT_COUNT=${FALLBACK_ATTEMPT_COUNT:-""}
FALLBACK_CONTEXT=${FALLBACK_CONTEXT:-""}
PRIMARY_FALLBACK_RESULT=${PRIMARY_FALLBACK_RESULT:-""}
COMBINED_FALLBACK_RESULTS=${COMBINED_FALLBACK_RESULTS:-""}
FALLBACK_STATISTICS=${FALLBACK_STATISTICS:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    
    # First check workflow_vars array
    local workflow_value="${workflow_vars[$var_name]:-}"
    if [[ -n "$workflow_value" ]]; then
        echo "$workflow_value"
        return
    fi
    
    # Fallback to environment variable (uppercase version)
    local env_var_name="${var_name^^}"  # Convert to uppercase
    local env_value="${!env_var_name:-}"
    if [[ -n "$env_value" ]]; then
        echo "$env_value"
        return
    fi
    
    # Finally use default value
    echo "$default_value"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Temporary file management
declare -a FLOWSH_TEMP_FILES=()

register_temp_file() {
    local temp_path="$1"
    FLOWSH_TEMP_FILES+=("$temp_path")
    log_debug "Registered temp file: $temp_path"
}

cleanup_temp_files() {
    local cleaned_count=0
    local failed_count=0
    
    for temp_file in "${FLOWSH_TEMP_FILES[@]}"; do
        if [[ -e "$temp_file" ]]; then
            if rm -rf "$temp_file" 2>/dev/null; then
                ((cleaned_count++))
                log_debug "Cleaned up temp file: $temp_file"
            else
                ((failed_count++))
                log_warning "Failed to clean up temp file: $temp_file"
            fi
        fi
    done
    
    # Clear the temp files array
    FLOWSH_TEMP_FILES=()
    
    if [[ $cleaned_count -gt 0 ]]; then
        log_info "Cleaned up $cleaned_count temporary files"
    fi
    
    if [[ $failed_count -gt 0 ]]; then
        log_warning "Failed to clean up $failed_count temporary files"
    fi
    
    return 0
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Process tracking for parallel execution
declare -a FLOWSH_ACTIVE_PIDS=()

register_process() {
    local pid="$1"
    local description="${2:-unknown}"
     
     # Use case statement instead of regex for PID validation
     case "$pid" in
         ''|*[!0-9]*) log_warning "Invalid PID for registration: $pid" ;;
         *)
             FLOWSH_ACTIVE_PIDS+=("$pid")
             log_debug "Registered process $pid: $description"
             ;;
     esac
}

unregister_process() {
    local pid="$1"
    local new_pids=()
    
    for active_pid in "${FLOWSH_ACTIVE_PIDS[@]}"; do
        if [[ "$active_pid" != "$pid" ]]; then
            new_pids+=("$active_pid")
        fi
    done
    
    FLOWSH_ACTIVE_PIDS=("${new_pids[@]}")
    log_debug "Unregistered process $pid"
}

# Mock circuit breaker operation for testing
execute_circuit_breaker_operation() {
    local timeout_seconds="${1:-30}"
    local failure_threshold="${2:-3}"
    log_info "Mock circuit breaker operation (timeout: ${timeout_seconds}s, threshold: ${failure_threshold})"
    
    # Simulate circuit breaker with 25% failure rate
    if [[ $((RANDOM % 4)) -eq 0 ]]; then
        log_warning "Mock circuit breaker: operation failed (simulated failure)"
        return 1
    else
        sleep 2
        log_success "Mock circuit breaker: operation succeeded"
        return 0
    fi
}

# Mock retry command execution
execute_retry_command() {
    local attempt_number="${1:-1}"
    local max_attempts="${2:-3}"
    log_info "Mock retry command execution (attempt $attempt_number/$max_attempts)"
    
    # Simulate work
    sleep 1
    
    # Simulate success after 2 attempts for realistic retry testing
    if [[ $attempt_number -ge 2 ]]; then
        log_success "Mock retry command: succeeded after $attempt_number attempts"
        return 0
    else
        log_warning "Mock retry command: failed on attempt $attempt_number"
        return 1
    fi
}

# Mock sequential iteration processing
execute_iteration_iterate_files_sequential() {
    local pattern="${1:-*}"
    log_info "Mock sequential iteration: processing files matching '$pattern'"
    
    # Simulate file processing
    sleep 0.5
    local files=("file1.txt" "file2.txt" "file3.txt")
    
    for file in "${files[@]}"; do
        log_info "Processing file: $file"
        sleep 0.5
    done
    
    log_success "Sequential iteration completed: processed ${#files[@]} files"
    return 0
}

# Mock fallback path execution for testing
execute_fallback_path() {
    local path_id="${1}"
    log_info "Mock fallback path execution: $path_id"
    
    # Simulate work
    sleep 1
    
    # Simulate success for primary_service_call, failure for others to test fallback behavior
    case "$path_id" in
        "primary_service_call")
            log_success "Primary service call succeeded"
            return 0
            ;;
        "secondary_service_call") 
            log_warning "Secondary service call failed"
            return 1
            ;;
        "cache_fallback_call")
            log_warning "Cache fallback failed"
            return 1
            ;;
        "default_response_call")
            log_success "Default response call succeeded"
            return 0
            ;;
        *)
            log_info "Unknown fallback path succeeded: $path_id"
            return 0
            ;;
    esac
}

# Workflow Execution

# Node: initialize_tracking
set_var "FALLBACK_ATTEMPT_COUNT" "0" "initialize_tracking"

# Node: setup_fallback_context
# Node: setup_fallback_context
FALLBACK_CONTEXT=$(echo "Fallback context: Strategy=$(get_workflow_var \"FALLBACK_STRATEGY\" \"default\"), Max time=$(get_workflow_var \"MAX_FALLBACK_TIME\" \"default\")s, Continue=$(get_workflow_var \"CONTINUE_ON_SUCCESS\" \"default\"), Simulation=$(get_workflow_var \"FAILURE_SIMULATION\" \"default\")")
set_var "FALLBACK_CONTEXT" "$FALLBACK_CONTEXT" "setup_fallback_context"

# Node: primary_service_fallback
# Node: primary_service_fallback (primary_service_fallback)
execute_fallback_primary_service_fallback() {
    log_step "🛡️ Fallback Handler: Primary Service with Fallbacks"

    local fallback_strategy=$(get_workflow_var "fallback_strategy" "sequential")
    local max_fallback_time=$(get_workflow_var "max_fallback_time" "300")
    local continue_on_success=$(get_workflow_var "continue_on_success" "false")
    local fallback_start_time=$(date +%s)
    
    # Define fallback paths
    local -a fallback_paths=("primary_service_call" "secondary_service_call" "cache_fallback_call" "default_response_call")
    
    log_info "Starting fallback handler: strategy=$fallback_strategy, paths=${#fallback_paths[@]}"

    case "$fallback_strategy" in
        "sequential")
            # Try each fallback path in order until one succeeds
            for path_index in "${!fallback_paths[@]}"; do
                local path_id="${fallback_paths[$path_index]}"
                
                # Check timeout
                local elapsed_time=$(($(date +%s) - fallback_start_time))
                if [[ $elapsed_time -ge $(get_workflow_var "max_fallback_time" "300") ]]; then
                    log_error "Fallback timeout exceeded: ${elapsed_time}s >= $(get_workflow_var "max_fallback_time" "300")s"
                    return 1
                fi
                
                log_info "Trying fallback path $((path_index + 1))/${#fallback_paths[@]}: $path_id"
                
                if execute_fallback_path "$path_id"; then
                    log_success "Fallback path '$path_id' succeeded"
                    set_workflow_var "fallback_used" "$path_id"
                    set_workflow_var "fallback_attempt" "$((path_index + 1))"
                    set_workflow_var "fallback_strategy" "sequential"
                    
                    if [[ "$(get_workflow_var "continue_on_success" "false")" == "false" ]]; then
                        return 0
                    fi
                else
                    log_warning "Fallback path '$path_id' failed"
                fi
            done
            
            if [[ "$(get_workflow_var "continue_on_success" "false")" == "true" ]]; then
                log_info "All fallback paths attempted (continue_on_success=true)"
                return 0
            else
                log_error "All ${#fallback_paths[@]} fallback paths failed"
                return 1
            fi
            ;;
        "parallel")
            # Try all fallback paths in parallel
            local temp_dir=$(mktemp -d -t "fallback_${BASHPID}_XXXXXX")
            local success_found="false"
            local successful_path=""
            
            # Start all fallback paths in parallel
            for path_index in "${!fallback_paths[@]}"; do
                local path_id="${fallback_paths[$path_index]}"
                (
                    if execute_fallback_path "$path_id"; then
                        echo "success:$path_id" > "$temp_dir/result_$path_index"
                    else
                        echo "failure:$path_id" > "$temp_dir/result_$path_index"
                    fi
                ) &
                local pid=$!
                register_process "$pid" "Fallback path: $path_id"
            done
            
            # Wait for results with timeout check
            while [[ "$success_found" == "false" ]]; do
                local elapsed_time=$(($(date +%s) - fallback_start_time))
                if [[ $elapsed_time -ge $(get_workflow_var "max_fallback_time" "300") ]]; then
                    log_error "Fallback timeout exceeded: ${elapsed_time}s >= $(get_workflow_var "max_fallback_time" "300")s"
                    break
                fi
                
                # Check for completed results
                for result_file in "$temp_dir"/result_*; do
                    [[ -f "$result_file" ]] || continue
                    local result_content=$(cat "$result_file")
                    if [[ "$result_content" =~ ^success: ]]; then
                        success_found="true"
                        successful_path="${result_content#success:}"
                        break
                    fi
                done
                
                [[ "$success_found" == "false" ]] && sleep 0.1
            done
            
            # Wait for all background processes to complete
            wait
            
            # Clean up
            rm -rf "$temp_dir"
            
            if [[ "$success_found" == "true" ]]; then
                set_workflow_var "fallback_used" "$successful_path"
                set_workflow_var "fallback_strategy" "parallel"
                log_success "Parallel fallback succeeded with path: $successful_path"
                return 0
            else
                log_error "All parallel fallback paths failed"
                return 1
            fi
            ;;
        *)
            log_error "Unknown fallback strategy: $fallback_strategy"
            return 1
            ;;
    esac
}
execute_fallback_primary_service_fallback

# Node: primary_service_call
sh -c "echo 'Attempting primary service: \${primary_service_url}' && if [ '\${failure_simulation}' = 'primary_fail' ] || [ '\${failure_simulation}' = 'all_fail' ]; then echo 'Primary service unavailable' && exit 1; else echo 'Primary service response: SUCCESS - Data from primary API' && exit 0; fi"

# Node: secondary_service_call
sh -c "echo 'Attempting secondary service fallback...' && if [ '\${failure_simulation}' = 'first_fallback_fail' ] || [ '\${failure_simulation}' = 'all_fail' ]; then echo 'Secondary service also unavailable' && exit 1; else echo 'Secondary service response: SUCCESS - Data from backup API' && exit 0; fi"

# Node: cache_fallback_call
sh -c "echo 'Attempting cache fallback...' && if [ '\${failure_simulation}' = 'all_fail' ]; then echo 'Cache unavailable' && exit 1; else echo 'Cache response: SUCCESS - Cached data from local storage (may be stale)' && exit 0; fi"

# Node: default_response_call
sh -c "echo 'Using default response fallback...' && echo 'Default response: LIMITED - Basic functionality available with default data' && exit 0"

# Node: record_primary_fallback_result
# Node: record_primary_fallback_result
PRIMARY_FALLBACK_RESULT=$(echo "Primary fallback completed with strategy: $(get_workflow_var \"FALLBACK_STRATEGY\" \"default\")")
set_var "PRIMARY_FALLBACK_RESULT" "$PRIMARY_FALLBACK_RESULT" "record_primary_fallback_result"

# Node: database_fallback_example
# Node: database_fallback_example (database_fallback_example)
execute_fallback_database_fallback_example() {
    log_step "🛡️ Fallback Handler: Database Operation Fallbacks"

    local fallback_strategy="sequential"
    local max_fallback_time="60"
    local continue_on_success="false"
    local fallback_start_time=$(date +%s)
    
    # Define fallback paths
    local -a fallback_paths=("primary_database_call" "read_replica_call" "database_cache_call")
    
    log_info "Starting fallback handler: strategy=$fallback_strategy, paths=${#fallback_paths[@]}"

    case "$fallback_strategy" in
        "sequential")
            # Try each fallback path in order until one succeeds
            for path_index in "${!fallback_paths[@]}"; do
                local path_id="${fallback_paths[$path_index]}"
                
                # Check timeout
                local elapsed_time=$(($(date +%s) - fallback_start_time))
                if [[ $elapsed_time -ge "60" ]]; then
                    log_error "Fallback timeout exceeded: ${elapsed_time}s >= "60"s"
                    return 1
                fi
                
                log_info "Trying fallback path $((path_index + 1))/${#fallback_paths[@]}: $path_id"
                
                if execute_fallback_path "$path_id"; then
                    log_success "Fallback path '$path_id' succeeded"
                    set_workflow_var "fallback_used" "$path_id"
                    set_workflow_var "fallback_attempt" "$((path_index + 1))"
                    set_workflow_var "fallback_strategy" "sequential"
                    
                    if [[ ""false"" == "false" ]]; then
                        return 0
                    fi
                else
                    log_warning "Fallback path '$path_id' failed"
                fi
            done
            
            if [[ ""false"" == "true" ]]; then
                log_info "All fallback paths attempted (continue_on_success=true)"
                return 0
            else
                log_error "All ${#fallback_paths[@]} fallback paths failed"
                return 1
            fi
            ;;
        "parallel")
            # Try all fallback paths in parallel
            local temp_dir=$(mktemp -d -t "fallback_${BASHPID}_XXXXXX")
            local success_found="false"
            local successful_path=""
            
            # Start all fallback paths in parallel
            for path_index in "${!fallback_paths[@]}"; do
                local path_id="${fallback_paths[$path_index]}"
                (
                    if execute_fallback_path "$path_id"; then
                        echo "success:$path_id" > "$temp_dir/result_$path_index"
                    else
                        echo "failure:$path_id" > "$temp_dir/result_$path_index"
                    fi
                ) &
                local pid=$!
                register_process "$pid" "Fallback path: $path_id"
            done
            
            # Wait for results with timeout check
            while [[ "$success_found" == "false" ]]; do
                local elapsed_time=$(($(date +%s) - fallback_start_time))
                if [[ $elapsed_time -ge "60" ]]; then
                    log_error "Fallback timeout exceeded: ${elapsed_time}s >= "60"s"
                    break
                fi
                
                # Check for completed results
                for result_file in "$temp_dir"/result_*; do
                    [[ -f "$result_file" ]] || continue
                    local result_content=$(cat "$result_file")
                    if [[ "$result_content" =~ ^success: ]]; then
                        success_found="true"
                        successful_path="${result_content#success:}"
                        break
                    fi
                done
                
                [[ "$success_found" == "false" ]] && sleep 0.1
            done
            
            # Wait for all background processes to complete
            wait
            
            # Clean up
            rm -rf "$temp_dir"
            
            if [[ "$success_found" == "true" ]]; then
                set_workflow_var "fallback_used" "$successful_path"
                set_workflow_var "fallback_strategy" "parallel"
                log_success "Parallel fallback succeeded with path: $successful_path"
                return 0
            else
                log_error "All parallel fallback paths failed"
                return 1
            fi
            ;;
        *)
            log_error "Unknown fallback strategy: $fallback_strategy"
            return 1
            ;;
    esac
}
execute_fallback_database_fallback_example

# Node: primary_database_call
sh -c "echo 'Querying primary database...' && if [ '\${failure_simulation}' = 'all_fail' ]; then echo 'Database connection failed' && exit 1; else echo 'Database result: User data retrieved from primary DB' && exit 0; fi"

# Node: read_replica_call
sh -c "echo 'Querying read replica...' && echo 'Replica result: User data from read replica (may be slightly stale)' && exit 0"

# Node: database_cache_call
sh -c "echo 'Querying database cache...' && echo 'Cache result: Cached user data (potentially stale but fast)' && exit 0"

# Node: parallel_fallback_example
# Node: parallel_fallback_example (parallel_fallback_example)
execute_fallback_parallel_fallback_example() {
    log_step "🛡️ Fallback Handler: Parallel Fallback Strategy"

    local fallback_strategy="parallel"
    local max_fallback_time="30"
    local continue_on_success="true"
    local fallback_start_time=$(date +%s)
    
    # Define fallback paths
    local -a fallback_paths=("fast_service_call" "medium_service_call" "slow_service_call")
    
    log_info "Starting fallback handler: strategy=$fallback_strategy, paths=${#fallback_paths[@]}"

    case "$fallback_strategy" in
        "sequential")
            # Try each fallback path in order until one succeeds
            for path_index in "${!fallback_paths[@]}"; do
                local path_id="${fallback_paths[$path_index]}"
                
                # Check timeout
                local elapsed_time=$(($(date +%s) - fallback_start_time))
                if [[ $elapsed_time -ge "30" ]]; then
                    log_error "Fallback timeout exceeded: ${elapsed_time}s >= "30"s"
                    return 1
                fi
                
                log_info "Trying fallback path $((path_index + 1))/${#fallback_paths[@]}: $path_id"
                
                if execute_fallback_path "$path_id"; then
                    log_success "Fallback path '$path_id' succeeded"
                    set_workflow_var "fallback_used" "$path_id"
                    set_workflow_var "fallback_attempt" "$((path_index + 1))"
                    set_workflow_var "fallback_strategy" "sequential"
                    
                    if [[ ""true"" == "false" ]]; then
                        return 0
                    fi
                else
                    log_warning "Fallback path '$path_id' failed"
                fi
            done
            
            if [[ ""true"" == "true" ]]; then
                log_info "All fallback paths attempted (continue_on_success=true)"
                return 0
            else
                log_error "All ${#fallback_paths[@]} fallback paths failed"
                return 1
            fi
            ;;
        "parallel")
            # Try all fallback paths in parallel
            local temp_dir=$(mktemp -d -t "fallback_${BASHPID}_XXXXXX")
            local success_found="false"
            local successful_path=""
            
            # Start all fallback paths in parallel
            for path_index in "${!fallback_paths[@]}"; do
                local path_id="${fallback_paths[$path_index]}"
                (
                    if execute_fallback_path "$path_id"; then
                        echo "success:$path_id" > "$temp_dir/result_$path_index"
                    else
                        echo "failure:$path_id" > "$temp_dir/result_$path_index"
                    fi
                ) &
                local pid=$!
                register_process "$pid" "Fallback path: $path_id"
            done
            
            # Wait for results with timeout check
            while [[ "$success_found" == "false" ]]; do
                local elapsed_time=$(($(date +%s) - fallback_start_time))
                if [[ $elapsed_time -ge "30" ]]; then
                    log_error "Fallback timeout exceeded: ${elapsed_time}s >= "30"s"
                    break
                fi
                
                # Check for completed results
                for result_file in "$temp_dir"/result_*; do
                    [[ -f "$result_file" ]] || continue
                    local result_content=$(cat "$result_file")
                    if [[ "$result_content" =~ ^success: ]]; then
                        success_found="true"
                        successful_path="${result_content#success:}"
                        break
                    fi
                done
                
                [[ "$success_found" == "false" ]] && sleep 0.1
            done
            
            # Wait for all background processes to complete
            wait
            
            # Clean up
            rm -rf "$temp_dir"
            
            if [[ "$success_found" == "true" ]]; then
                set_workflow_var "fallback_used" "$successful_path"
                set_workflow_var "fallback_strategy" "parallel"
                log_success "Parallel fallback succeeded with path: $successful_path"
                return 0
            else
                log_error "All parallel fallback paths failed"
                return 1
            fi
            ;;
        *)
            log_error "Unknown fallback strategy: $fallback_strategy"
            return 1
            ;;
    esac
}
execute_fallback_parallel_fallback_example

# Node: fast_service_call
sh -c "echo 'Fast service executing...' && sleep 1 && echo 'Fast service result: Quick response with basic data' && exit 0"

# Node: medium_service_call
sh -c "echo 'Medium service executing...' && sleep 2 && echo 'Medium service result: Balanced response with standard data' && exit 0"

# Node: slow_service_call
sh -c "echo 'Slow service executing...' && sleep 3 && echo 'Slow service result: Comprehensive response with detailed data' && exit 0"

# Node: aggregate_fallback_results

# Node: aggregate_fallback_results (Aggregate All Fallback Results)
execute_aggregation_aggregate_fallback_results() {
    log_step "📊 Variable Aggregation: Aggregate All Fallback Results"

    local -a input_vars=("PRIMARY_SERVICE_FALLBACK" "DATABASE_FALLBACK_EXAMPLE" "PARALLEL_FALLBACK_EXAMPLE")
    local output_var="combined_fallback_results"
    local method="concat"
    local separator=$'
--- FALLBACK SEPARATOR ---
'

    log_debug "Concatenating ${#input_vars[@]} variables with separator"
    local -a values=()
    for var_name in "${input_vars[@]}"; do
        local value="$(get_workflow_var "$var_name" "")"
        [[ -n "$value" ]] && values+=("$value")
    done
    
    if [[ ${#values[@]} -eq 0 ]]; then
        log_warning "No non-empty values to concatenate"
        set_workflow_var "$output_var" ""
    else
        local result
        result=$(IFS="$separator"; echo "${values[*]}")
        set_workflow_var "$output_var" "$result"
        log_success "Concatenated ${#values[@]} values into $output_var"
    fi

    log_success "Variable aggregation completed: ${#input_vars[@]} inputs -> $output_var"
}
execute_aggregation_aggregate_fallback_results

# Node: generate_fallback_statistics
# Node: generate_fallback_statistics
FALLBACK_STATISTICS=$(echo 'Fallback Statistics: Strategy=$(get_workflow_var "FALLBACK_STRATEGY" "default"), Max time=$(get_workflow_var "MAX_FALLBACK_TIME" "default")s, Continue=$(get_workflow_var "CONTINUE_ON_SUCCESS" "default"), Simulation=$(get_workflow_var "FAILURE_SIMULATION" "default"), Completion='$(date))
set_var "FALLBACK_STATISTICS" "$FALLBACK_STATISTICS" "generate_fallback_statistics"

# Node: final_report
echo "# 🛡️ Fallback Node Example Results

## Configuration Summary
- **Primary Service**: $(get_var "PRIMARY_SERVICE_URL" "final_report")
- **Fallback Strategy**: $(get_var "FALLBACK_STRATEGY" "final_report")
- **Max Fallback Time**: $(get_var "MAX_FALLBACK_TIME" "final_report") seconds
- **Continue on Success**: $(get_var "CONTINUE_ON_SUCCESS" "final_report")
- **Failure Simulation**: $(get_var "FAILURE_SIMULATION" "final_report")

## Fallback Operations Performed

### 1. Primary Service Fallback Chain
**Strategy**: $(get_var "FALLBACK_STRATEGY" "final_report") execution
**Fallback Sequence**:
1. Primary Service → Primary API endpoint
2. Secondary Service → Backup API endpoint  
3. Cache Fallback → Local cached data
4. Default Response → Minimal functionality

### 2. Database Operation Fallbacks
**Strategy**: Sequential execution
**Fallback Sequence**:
1. Primary Database → Main database cluster
2. Read Replica → Read-only replica database
3. Database Cache → Cached database results

### 3. Parallel Fallback Strategy
**Strategy**: Parallel execution
**Concurrent Services**:
- Fast Service (1s response, basic data)
- Medium Service (2s response, standard data)
- Slow Service (3s response, comprehensive data)

## Fallback Results Summary

$(get_var "COMBINED_FALLBACK_RESULTS" "final_report")

## Performance Metrics
$(get_var "FALLBACK_STATISTICS" "final_report")

## Fallback Node Features Demonstrated

### Execution Strategies
- **Sequential Fallbacks**: Try fallbacks one after another until success
- **Parallel Fallbacks**: Execute multiple fallbacks simultaneously for speed
- **Mixed Strategies**: Different strategies for different use cases

### Fallback Configuration
- **Fallback Paths**: Ordered list of alternative execution paths
- **Time Limits**: Maximum time constraints for fallback operations
- **Success Continuation**: Option to continue trying after first success
- **Dynamic Strategy Selection**: Runtime strategy configuration

### Graceful Degradation Patterns

1. **Service Quality Tiers**
   - Primary: Full functionality, best performance
   - Secondary: Reduced functionality, good performance  
   - Cache: Limited functionality, fast response
   - Default: Minimal functionality, immediate response

2. **Data Freshness Trade-offs**
   - Primary Database: Real-time, authoritative data
   - Read Replica: Near real-time, slightly stale data
   - Cache: Potentially stale but fast access

3. **Performance vs. Completeness**
   - Fast Service: Quick response, basic information
   - Medium Service: Balanced response time and data richness
   - Slow Service: Comprehensive data with longer response time

### Error Handling Strategies
- **Automatic Failover**: Seamless transition between services
- **Timeout Management**: Appropriate timeouts for each fallback level
- **Resource Conservation**: Efficient resource usage during failures
- **Status Reporting**: Clear indication of which fallback was used

### Use Cases
- **API Gateway Resilience**: Multiple backend service options
- **Database High Availability**: Primary/replica/cache hierarchies
- **Content Delivery**: CDN with multiple source fallbacks
- **Authentication Systems**: Primary/backup identity providers
- **Payment Processing**: Multiple payment gateway options
- **Microservice Communication**: Service mesh resilience patterns

### Monitoring and Observability
- **Fallback Metrics**: Track which fallbacks are used most frequently
- **Performance Impact**: Measure latency impact of fallback usage
- **Success Rates**: Monitor success rates at each fallback level
- **Resource Utilization**: Track resource consumption during fallbacks

### Best Practices Demonstrated

1. **Layered Fallbacks**: Multiple levels of degradation
2. **Timeout Hierarchies**: Shorter timeouts for higher-priority services
3. **Resource Efficiency**: Lighter operations for fallback services
4. **User Experience**: Maintain functionality even with degraded services
5. **Operational Visibility**: Clear reporting of fallback usage
6. **Configuration Flexibility**: Runtime configuration of fallback behavior

This example demonstrates how fallback nodes provide robust resilience patterns essential for building fault-tolerant, highly available systems that gracefully degrade under failure conditions.
"

echo "Workflow completed successfully"
exit 0
