#!/bin/bash
set -euo pipefail

# iteration-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: iteration-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
FILE_LIST=${FILE_LIST:-""}
PROCESSING_MODE=${PROCESSING_MODE:-""}
ENABLE_PARALLEL=${ENABLE_PARALLEL:-""}
FILES_ARRAY=${FILES_ARRAY:-""}
PROCESSING_RESULTS=${PROCESSING_RESULTS:-""}
FILE_PROCESSING_RESULTS=${FILE_PROCESSING_RESULTS:-""}
ITERATION_ITEM=${ITERATION_ITEM:-""}
ITERATION_INDEX=${ITERATION_INDEX:-""}
ITERATION_NUMBER=${ITERATION_NUMBER:-""}
ITERATION_TOTAL=${ITERATION_TOTAL:-""}
ITERATION_RESULT=${ITERATION_RESULT:-""}
ITERATION_COUNT=${ITERATION_COUNT:-""}
ITERATION_COMPLETED=${ITERATION_COMPLETED:-""}
CURRENT_FILE=${CURRENT_FILE:-""}
FILE_EXTENSION=${FILE_EXTENSION:-""}
CURRENT_FILE_RESULT=${CURRENT_FILE_RESULT:-""}
FINAL_RESULTS=${FINAL_RESULTS:-""}
TOTAL_FILES_PROCESSED=${TOTAL_FILES_PROCESSED:-""}
PROCESSING_SUMMARY=${PROCESSING_SUMMARY:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: prepare_file_array
set_var "FILES_ARRAY" "" "prepare_file_array"

# Node: initialize_results
set_var "PROCESSING_RESULTS" "" "initialize_results"

# Node: iterate_files

# Node: iterate_files (Process Each File)
execute_iteration_iterate_files() {
    log_step "🔁 Starting Parallel Iteration: Process Each File"
    
    # Parallel iteration is planned for Phase 2C
    # For now, fall back to sequential processing
    log_warning "Parallel iteration not yet implemented, using sequential processing"
    
    # Use sequential implementation
    
# Node: iterate_files (Process Each File)
execute_iteration_iterate_files_sequential_sequential() {
    log_step "🔁 Starting Iteration: Process Each File"
    
    # Get input array variable
    local input_variable="files_array"
    local output_variable="file_processing_results"
    local input_array_raw="$(get_workflow_var "$input_variable" "")"
    
    # Parse input array (newline-separated values by default)
    local -a input_array=()
    if [[ -n "$input_array_raw" ]]; then
        # Handle different array formats
        if [[ "$input_array_raw" =~ ^\[.*\]$ ]]; then
            # JSON array format - extract values
            while IFS= read -r item; do
                [[ -n "$item" ]] && input_array+=("$item")
            done < <(echo "$input_array_raw" | jq -r '.[]' 2>/dev/null || echo "$input_array_raw")
        else
            # Newline-separated format
            while IFS= read -r item; do
                [[ -n "$item" ]] && input_array+=("$item")
            done <<< "$input_array_raw"
        fi
    fi
    
    local total_items=${#input_array[@]}
    log_info "Processing $total_items items sequentially"
    
    # Results collection
    local -a output_results=()
    
    # Process each item
    for item_index in "${!input_array[@]}"; do
        local current_item="${input_array[$item_index]}"
        
        log_debug "Processing item $((item_index + 1))/$total_items: $current_item"
        
        # Set iteration context variables for child nodes
        set_workflow_var "iteration_item" "$current_item"
        set_workflow_var "iteration_index" "$item_index"
        set_workflow_var "iteration_number" "$((item_index + 1))"
        set_workflow_var "iteration_total" "$total_items"
        
        # Clear previous iteration result
        set_workflow_var "iteration_result" ""
        
        # Execute iteration body (child nodes would be called here by main executor)
        log_debug "Executing iteration body for item: $current_item"
        
        # This is where child nodes would be executed
        # The main executor will handle the edge routing to child nodes
        
        # Collect result (after child nodes have executed)
        local iteration_result="$(get_workflow_var "iteration_result" "$current_item")"
        output_results+=("$iteration_result")
        
        log_debug "Item $((item_index + 1)) result: $iteration_result"
    done
    
    # Aggregate results based on output format preference
    local aggregated_results
    if [[ $total_items -eq 0 ]]; then
        aggregated_results=""
    else
        # Store as newline-separated by default, can be processed by aggregation nodes
        aggregated_results=$(IFS=$'\n'; echo "${output_results[*]}")
    fi
    
    # Set output variable
    set_workflow_var "$output_variable" "$aggregated_results"
    
    # Set iteration metadata
    set_workflow_var "iteration_count" "$total_items"
    set_workflow_var "iteration_completed" "true"
    
    log_success "Iteration completed: processed $total_items items"
}
    
    # Call sequential implementation
    execute_iteration_iterate_files_sequential
}
execute_iteration_iterate_files

# Node: get_current_file
set_var "CURRENT_FILE" "" "get_current_file"

# Node: analyze_file_type
set_var "FILE_EXTENSION" "" "analyze_file_type"

# Node: process_by_type
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: process_yaml_file
sh

# Node: process_json_file
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: handle_json
sh

# Node: process_script_file
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: handle_script
sh

# Node: process_other_file
sh

# Node: create_file_report
set_var "CURRENT_FILE_RESULT" "" "create_file_report"

# Node: collect_iteration_results

# Node: collect_iteration_results (Collect All File Results)
execute_aggregation_collect_iteration_results() {
    log_step "📊 Variable Aggregation: Collect All File Results"

    local -a input_vars=("file_processing_results")
    local output_var="final_results"
    local method="concat"
    local separator=$'
'

    case "$method" in
        "concat")
            log_debug "Concatenating ${#input_vars[@]} variables with separator"
            local -a values=()
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && values+=("$value")
            done
            
            if [[ ${#values[@]} -eq 0 ]]; then
                log_warning "No non-empty values to concatenate"
                set_workflow_var "$output_var" ""
            else
                local result
                result=$(IFS="$separator"; echo "${values[*]}")
                set_workflow_var "$output_var" "$result"
                log_success "Concatenated ${#values[@]} values into $output_var"
            fi
            ;;

        "sum")
            log_debug "Summing numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        # Fallback to integer arithmetic if bc not available
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            set_workflow_var "$output_var" "$total"
            log_success "Summed $valid_count numeric values, result: $total"
            ;;

        "avg")
            log_debug "Calculating average of numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            if [[ $valid_count -gt 0 ]]; then
                local average
                if command -v bc >/dev/null 2>&1; then
                    average=$(echo "scale=6; $total / $valid_count" | bc -l)
                else
                    average=$((total / valid_count))
                fi
                set_workflow_var "$output_var" "$average"
                log_success "Calculated average of $valid_count values: $average"
            else
                log_warning "No valid numeric values to average"
                set_workflow_var "$output_var" "0"
            fi
            ;;

        "collect")
            log_debug "Collecting values into JSON array from ${#input_vars[@]} variables"
            local -a collected=()
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && collected+=("$value")
            done
            
            # Store as JSON array for structured access
            if command -v jq >/dev/null 2>&1; then
                local json_array
                json_array=$(printf '%s
' "${collected[@]}" | jq -R . | jq -s .)
                set_workflow_var "$output_var" "$json_array"
                log_success "Collected ${#collected[@]} values into JSON array"
            else
                # Fallback: create simple array format
                local array_string="["
                local first=true
                for value in "${collected[@]}"; do
                    if [[ "$first" == "true" ]]; then
                        first=false
                    else
                        array_string+=", "
                    fi
                    array_string+="\"$value\""
                done
                array_string+="]"
                set_workflow_var "$output_var" "$array_string"
                log_success "Collected ${#collected[@]} values into array (jq not available, using fallback format)"
            fi
            ;;

        "merge")
            log_debug "Merging JSON objects from ${#input_vars[@]} variables"
            local merged_json="{}"
            local merge_count=0
            
            if command -v jq >/dev/null 2>&1; then
                for var_name in "${input_vars[@]}"; do
                    local value="$(get_workflow_var "$var_name" "{}")"
                    # Validate that value is valid JSON
                    if echo "$value" | jq -e . >/dev/null 2>&1; then
                        merged_json=$(jq -s '.[0] * .[1]' <<< "$merged_json $value" 2>/dev/null)
                        if [[ $? -eq 0 ]]; then
                            ((merge_count++))
                        else
                            log_warning "Failed to merge JSON from $var_name"
                        fi
                    else
                        log_warning "Invalid JSON in variable $var_name, skipping"
                    fi
                done
                
                set_workflow_var "$output_var" "$merged_json"
                log_success "Merged $merge_count JSON objects"
            else
                log_error "jq is required for merge operation but not available"
                set_workflow_var "$output_var" "{}"
                return 1
            fi
            ;;

        *)
            log_error "Unknown aggregation method: $method"
            return 1
            ;;
    esac

    log_success "Variable aggregation completed: ${#input_vars[@]} inputs -> $output_var"
}
execute_aggregation_collect_iteration_results

# Node: calculate_statistics
set_var "TOTAL_FILES_PROCESSED" "" "calculate_statistics"

# Node: create_summary_report
set_var "PROCESSING_SUMMARY" "" "create_summary_report"

# Node: final_results
echo "# 🔄 Iteration Node Example Results

## Processing Configuration
- **Input Files**: $(get_var "FILE_LIST" "final_results")
- **Processing Mode**: $(get_var "PROCESSING_MODE" "final_results")
- **Parallel Processing**: $(get_var "ENABLE_PARALLEL" "final_results")
- **Total Files**: $(get_var "TOTAL_FILES_PROCESSED" "final_results")

## Processing Results

$(get_var "FINAL_RESULTS" "final_results")

## Summary Statistics
$(get_var "PROCESSING_SUMMARY" "final_results")

## File Type Breakdown
The iteration processed different file types with specialized handling:

- **YAML/YML Files** 📄: Structure validation and syntax checking
- **JSON Files** 🔗: Schema validation and formatting verification
- **Shell Scripts** 🔧: Syntax checking and permission analysis
- **Other Files** 📋: Basic file analysis and metadata extraction

## Iteration Node Features Demonstrated

- **Array Processing**: Iterate through collections of data items
- **Variable Mapping**: Input/output variable configuration
- **Parallel Execution**: Optional parallel processing for performance
- **Dynamic Processing**: Different handling based on item properties
- **Result Aggregation**: Collecting and combining iteration results
- **Type-aware Processing**: Conditional logic based on data characteristics
- **Progress Tracking**: Monitoring iteration progress and completion
- **Flexible Input**: Support for various data collection formats

This example demonstrates how iteration nodes enable efficient processing of data collections with type-specific logic and result aggregation.
"

echo "Workflow completed successfully"
exit 0
