#!/bin/bash
set -euo pipefail

# llm-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: llm-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# Environment Variables
USER_QUERY=${USER_QUERY:-""}
RESPONSE_STYLE=${RESPONSE_STYLE:-""}
MAX_LENGTH=${MAX_LENGTH:-""}
INCLUDE_EXAMPLES=${INCLUDE_EXAMPLES:-""}
CONTEXT_INFO=${CONTEXT_INFO:-""}
BASIC_LLM_CHAT=${BASIC_LLM_CHAT:-""}
ADVANCED_LLM_TEMPLATE=${ADVANCED_LLM_TEMPLATE:-""}
LLM_WITH_VISION=${LLM_WITH_VISION:-""}
COMPLETION_MODE_LLM=${COMPLETION_MODE_LLM:-""}
COMBINED_ANALYSIS=${COMBINED_ANALYSIS:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: prepare_context
CONTEXT_INFO=""

# Node: basic_llm_chat
curl -s -X POST "https://api.openai.com/v1/chat/completions" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "Hello"}]}'

# Node: advanced_llm_template
curl -s -X POST "https://api.openai.com/v1/chat/completions" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model": "gpt-4", "messages": [{"role": "user", "content": "Hello"}]}'

# Node: llm_with_vision
curl -s -X POST "https://api.openai.com/v1/chat/completions" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model": "gpt-4-vision-preview", "messages": [{"role": "user", "content": "Hello"}]}'

# Node: completion_mode_llm
curl -s -X POST "https://api.openai.com/v1/chat/completions" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model": "gpt-3.5-turbo-instruct", "messages": [{"role": "user", "content": "Hello"}]}'

# Node: aggregate_responses

# Node: aggregate_responses (Aggregate LLM Responses)
execute_aggregation_aggregate_responses() {
    log_step "📊 Variable Aggregation: Aggregate LLM Responses"

    local -a input_vars=("basic_llm_chat" "advanced_llm_template" "llm_with_vision" "completion_mode_llm")
    local output_var="combined_analysis"
    local method="concat"
    local separator=$'

---

'

    case "$method" in
        "concat")
            log_debug "Concatenating ${#input_vars[@]} variables with separator"
            local -a values=()
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && values+=("$value")
            done
            
            if [[ ${#values[@]} -eq 0 ]]; then
                log_warning "No non-empty values to concatenate"
                set_workflow_var "$output_var" ""
            else
                local result
                result=$(IFS="$separator"; echo "${values[*]}")
                set_workflow_var "$output_var" "$result"
                log_success "Concatenated ${#values[@]} values into $output_var"
            fi
            ;;

        "sum")
            log_debug "Summing numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        # Fallback to integer arithmetic if bc not available
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            set_workflow_var "$output_var" "$total"
            log_success "Summed $valid_count numeric values, result: $total"
            ;;

        "avg")
            log_debug "Calculating average of numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            if [[ $valid_count -gt 0 ]]; then
                local average
                if command -v bc >/dev/null 2>&1; then
                    average=$(echo "scale=6; $total / $valid_count" | bc -l)
                else
                    average=$((total / valid_count))
                fi
                set_workflow_var "$output_var" "$average"
                log_success "Calculated average of $valid_count values: $average"
            else
                log_warning "No valid numeric values to average"
                set_workflow_var "$output_var" "0"
            fi
            ;;

        "collect")
            log_debug "Collecting values into JSON array from ${#input_vars[@]} variables"
            local -a collected=()
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && collected+=("$value")
            done
            
            # Store as JSON array for structured access
            if command -v jq >/dev/null 2>&1; then
                local json_array
                json_array=$(printf '%s
' "${collected[@]}" | jq -R . | jq -s .)
                set_workflow_var "$output_var" "$json_array"
                log_success "Collected ${#collected[@]} values into JSON array"
            else
                # Fallback: create simple array format
                local array_string="["
                local first=true
                for value in "${collected[@]}"; do
                    if [[ "$first" == "true" ]]; then
                        first=false
                    else
                        array_string+=", "
                    fi
                    array_string+="\"$value\""
                done
                array_string+="]"
                set_workflow_var "$output_var" "$array_string"
                log_success "Collected ${#collected[@]} values into array (jq not available, using fallback format)"
            fi
            ;;

        "merge")
            log_debug "Merging JSON objects from ${#input_vars[@]} variables"
            local merged_json="{}"
            local merge_count=0
            
            if command -v jq >/dev/null 2>&1; then
                for var_name in "${input_vars[@]}"; do
                    local value="$(get_workflow_var "$var_name" "{}")"
                    # Validate that value is valid JSON
                    if echo "$value" | jq -e . >/dev/null 2>&1; then
                        merged_json=$(jq -s '.[0] * .[1]' <<< "$merged_json $value" 2>/dev/null)
                        if [[ $? -eq 0 ]]; then
                            ((merge_count++))
                        else
                            log_warning "Failed to merge JSON from $var_name"
                        fi
                    else
                        log_warning "Invalid JSON in variable $var_name, skipping"
                    fi
                done
                
                set_workflow_var "$output_var" "$merged_json"
                log_success "Merged $merge_count JSON objects"
            else
                log_error "jq is required for merge operation but not available"
                set_workflow_var "$output_var" "{}"
                return 1
            fi
            ;;

        *)
            log_error "Unknown aggregation method: $method"
            return 1
            ;;
    esac

    log_success "Variable aggregation completed: ${#input_vars[@]} inputs -> $output_var"
}

# Node: final_summary
echo "# 🧠 LLM Node Example Results

## Original Query
**Question**: ${user_query}
**Preferences**: ${response_style} style, ${max_length} length, examples: ${include_examples}

## LLM Configurations Demonstrated

### 1. Basic Chat Mode 💬
- **Provider**: OpenAI GPT-3.5-turbo
- **Mode**: Chat with system/user messages
- **Features**: Basic temperature and token controls
- **Use Case**: Quick, conversational interactions

### 2. Advanced Template Mode 🎯
- **Provider**: OpenAI GPT-4
- **Mode**: Chat with structured templates
- **Features**: Template parameters, context management, memory window
- **Use Case**: Complex, structured analysis tasks

### 3. Vision-Enabled Mode 👁️
- **Provider**: OpenAI GPT-4-Vision
- **Mode**: Chat with visual analysis capabilities
- **Features**: Image understanding, visual context
- **Use Case**: Analysis involving diagrams, charts, images

### 4. Completion Mode 📝
- **Provider**: OpenAI GPT-3.5-turbo-instruct
- **Mode**: Completion (not chat)
- **Features**: Direct text completion, stop sequences
- **Use Case**: Text generation, creative writing, completion tasks

## Advanced Features Showcased

- **Multiple Model Providers**: Support for OpenAI, Anthropic, Google, local models
- **Flexible Prompting**: Inline prompts, template systems, multi-message conversations
- **Parameter Control**: Temperature, max_tokens, top_p, frequency/presence penalties
- **Context Management**: Context variables, memory windows, role prefixes
- **Vision Integration**: Image analysis capabilities when supported
- **Template Parameters**: Dynamic prompt customization with variable substitution
- **Response Aggregation**: Combining multiple LLM responses for comprehensive analysis

## Combined Analysis Results

${combined_analysis}

---

This example demonstrates the full range of LLM node capabilities in flowsh, from simple chat interactions to complex, template-driven AI workflows with advanced configuration options.
"

echo "Workflow completed successfully"
exit 0
