#!/bin/bash
set -euo pipefail

# parallel-iteration-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: parallel-iteration-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
TASK_LIST=${TASK_LIST:-""}
MAX_CONCURRENT=${MAX_CONCURRENT:-""}
CHUNK_SIZE=${CHUNK_SIZE:-""}
ERROR_HANDLING=${ERROR_HANDLING:-""}
ENABLE_PROGRESS_TRACKING=${ENABLE_PROGRESS_TRACKING:-""}
TASKS_ARRAY=${TASKS_ARRAY:-""}
START_TIME=${START_TIME:-""}
CURRENT_TASK=${CURRENT_TASK:-""}
TASK_RESULT=${TASK_RESULT:-""}
PARALLEL_RESULTS=${PARALLEL_RESULTS:-""}
COMBINED_RESULTS=${COMBINED_RESULTS:-""}
END_TIME=${END_TIME:-""}
EXECUTION_DURATION=${EXECUTION_DURATION:-""}
TOTAL_TASKS=${TOTAL_TASKS:-""}
THROUGHPUT=${THROUGHPUT:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: prepare_task_array
set_var "TASKS_ARRAY" "" "prepare_task_array"

# Node: setup_performance_monitoring
set_var "START_TIME" "" "setup_performance_monitoring"

# Node: parallel_task_processor
# Node: parallel_task_processor (Parallel Task Processing Engine)
execute_parallel_iteration_parallel_task_processor() {
    log_step "🔁 Parallel Iteration: Parallel Task Processing Engine"

    local input_variable="tasks_array"
    local output_variable="parallel_results"
    local max_parallel=${max_concurrent}
    local progress_tracking=true
    local error_handling="${error_handling}"
    
    # Get input array and validate
    local input_array_raw="$(get_workflow_var "$input_variable")"
    if [[ -z "$input_array_raw" ]]; then
        log_warning "Input variable '$input_variable' is empty, skipping parallel iteration"
        set_workflow_var "$output_variable" ""
        return 0
    fi

    # Parse input array into bash array
    local -a input_array=()
    while IFS= read -r item; do
        [[ -n "$item" ]] && input_array+=("$item")
    done <<< "$input_array_raw"

    local total_items=${#input_array[@]}
    if [[ $total_items -eq 0 ]]; then
        log_info "No items to process in parallel iteration"
        set_workflow_var "$output_variable" ""
        return 0
    fi

    log_info "Starting parallel processing of $total_items items (max parallel: ${max_concurrent})"

    # Setup parallel processing infrastructure
    local temp_dir=$(mktemp -d)
    local -a active_pids=()
    local completed_items=0
    local failed_items=0

    # Process items with controlled parallelism
    for item_index in "${!input_array[@]}"; do
        local current_item="${input_array[$item_index]}"
        
        # Wait if we've reached max parallel limit
        while (( ${#active_pids[@]} >= max_parallel )); do
            # Check for completed processes
            local -a new_pids=()
            for pid in "${active_pids[@]}"; do
                if kill -0 "$pid" 2>/dev/null; then
                    new_pids+=("$pid")  # Still running
                else
                    # Process completed
                    wait "$pid"
                    local exit_code=$?
                    
                    if [[ $exit_code -eq 0 ]]; then
                        ((completed_items++))
                        log_progress "Completed $completed_items/$total_items items"
                    else
                        ((failed_items++))
                        log_warning "Parallel iteration item failed with exit code $exit_code"
                        
                        case "$error_handling" in
                            "fail")
                                log_error "Parallel iteration failed (fail strategy)"
                                for remaining_pid in "${active_pids[@]}"; do
                                    kill "$remaining_pid" 2>/dev/null || true
                                done
                                rm -rf "$temp_dir"
                                return 1
                                ;;
                            "continue"|"ignore")
                                # Continue processing
                                ;;
                        esac
                    fi
                fi
            done
            active_pids=("${new_pids[@]}")
            
            [[ ${#active_pids[@]} -ge $max_parallel ]] && sleep 0.1
        done

        # Start new background iteration
        (
            # Set up isolated context
            local item_index=$item_index
            local current_item="$current_item"
            local iteration_temp_dir="$temp_dir/item_$item_index"
            mkdir -p "$iteration_temp_dir"
            
            # Set iteration context variables
            export ITERATION_ITEM="$current_item"
            export ITERATION_INDEX="$item_index"
            export ITERATION_TEMP_DIR="$iteration_temp_dir"
            
            # Execute iteration body (placeholder)
            # Child node execution placeholder
            # This will be replaced with actual child node calls
            log_debug "Processing parallel iteration item: $current_item (index: $item_index)"
            
            # Default processing (replace with actual nodes)
            sleep 0.1  # Simulate work
            
            # Save result
            echo "$current_item" > "$iteration_temp_dir/result.out"
        ) &
        
        local bg_pid=$!
        active_pids+=("$bg_pid")
        log_debug "Started parallel iteration for item $item_index (PID: $bg_pid)"
    done

    # Wait for all remaining processes
    log_info "Waiting for remaining parallel iterations to complete..."
    for pid in "${active_pids[@]}"; do
        wait "$pid"
        local exit_code=$?
        if [[ $exit_code -eq 0 ]]; then
            ((completed_items++))
        else
            ((failed_items++))
        fi
    done

    # Collect results
    local -a final_results=()
    for item_index in "${!input_array[@]}"; do
        local result_file="$temp_dir/item_$item_index/result.out"
        if [[ -f "$result_file" ]]; then
            final_results+=("$(cat "$result_file")")
        else
            final_results+=("")
        fi
    done

    # Store aggregated results
    local aggregated_results
    aggregated_results=$(IFS=$'\n'; echo "${final_results[*]}")
    set_workflow_var "$output_variable" "$aggregated_results"

    # Performance summary
    local success_rate=$(( (completed_items * 100) / total_items ))
    log_success "Parallel iteration completed: $completed_items/$total_items items succeeded ($success_rate%)"
    
    if [[ $failed_items -gt 0 ]]; then
        log_warning "Parallel iteration had $failed_items failures"
    fi

    # Cleanup
    rm -rf "$temp_dir"
    return 0
}
execute_parallel_iteration_parallel_task_processor

# Node: process_individual_task
set_var "CURRENT_TASK" "" "process_individual_task"

# Node: simulate_task_work
sh

# Node: generate_task_result
set_var "TASK_RESULT" "" "generate_task_result"

# Node: task_complexity_check
if true; then
  echo "Condition passed"
else
  echo "Condition failed"
fi

# Node: process_complex_task
sh

# Node: process_simple_task
sh

# Node: aggregate_results

# Node: aggregate_results (Aggregate Parallel Results)
execute_aggregation_aggregate_results() {
    log_step "📊 Variable Aggregation: Aggregate Parallel Results"

    local -a input_vars=("parallel_results")
    local output_var="combined_results"
    local method="concat"
    local separator=$'
'

    case "$method" in
        "concat")
            log_debug "Concatenating ${#input_vars[@]} variables with separator"
            local -a values=()
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && values+=("$value")
            done
            
            if [[ ${#values[@]} -eq 0 ]]; then
                log_warning "No non-empty values to concatenate"
                set_workflow_var "$output_var" ""
            else
                local result
                result=$(IFS="$separator"; echo "${values[*]}")
                set_workflow_var "$output_var" "$result"
                log_success "Concatenated ${#values[@]} values into $output_var"
            fi
            ;;

        "sum")
            log_debug "Summing numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        # Fallback to integer arithmetic if bc not available
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            set_workflow_var "$output_var" "$total"
            log_success "Summed $valid_count numeric values, result: $total"
            ;;

        "avg")
            log_debug "Calculating average of numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            if [[ $valid_count -gt 0 ]]; then
                local average
                if command -v bc >/dev/null 2>&1; then
                    average=$(echo "scale=6; $total / $valid_count" | bc -l)
                else
                    average=$((total / valid_count))
                fi
                set_workflow_var "$output_var" "$average"
                log_success "Calculated average of $valid_count values: $average"
            else
                log_warning "No valid numeric values to average"
                set_workflow_var "$output_var" "0"
            fi
            ;;

        "collect")
            log_debug "Collecting values into JSON array from ${#input_vars[@]} variables"
            local -a collected=()
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && collected+=("$value")
            done
            
            # Store as JSON array for structured access
            if command -v jq >/dev/null 2>&1; then
                local json_array
                json_array=$(printf '%s
' "${collected[@]}" | jq -R . | jq -s .)
                set_workflow_var "$output_var" "$json_array"
                log_success "Collected ${#collected[@]} values into JSON array"
            else
                # Fallback: create simple array format
                local array_string="["
                local first=true
                for value in "${collected[@]}"; do
                    if [[ "$first" == "true" ]]; then
                        first=false
                    else
                        array_string+=", "
                    fi
                    array_string+="\"$value\""
                done
                array_string+="]"
                set_workflow_var "$output_var" "$array_string"
                log_success "Collected ${#collected[@]} values into array (jq not available, using fallback format)"
            fi
            ;;

        "merge")
            log_debug "Merging JSON objects from ${#input_vars[@]} variables"
            local merged_json="{}"
            local merge_count=0
            
            if command -v jq >/dev/null 2>&1; then
                for var_name in "${input_vars[@]}"; do
                    local value="$(get_workflow_var "$var_name" "{}")"
                    # Validate that value is valid JSON
                    if echo "$value" | jq -e . >/dev/null 2>&1; then
                        merged_json=$(jq -s '.[0] * .[1]' <<< "$merged_json $value" 2>/dev/null)
                        if [[ $? -eq 0 ]]; then
                            ((merge_count++))
                        else
                            log_warning "Failed to merge JSON from $var_name"
                        fi
                    else
                        log_warning "Invalid JSON in variable $var_name, skipping"
                    fi
                done
                
                set_workflow_var "$output_var" "$merged_json"
                log_success "Merged $merge_count JSON objects"
            else
                log_error "jq is required for merge operation but not available"
                set_workflow_var "$output_var" "{}"
                return 1
            fi
            ;;

        *)
            log_error "Unknown aggregation method: $method"
            return 1
            ;;
    esac

    log_success "Variable aggregation completed: ${#input_vars[@]} inputs -> $output_var"
}
execute_aggregation_aggregate_results

# Node: calculate_performance_metrics
set_var "END_TIME" "" "calculate_performance_metrics"

# Node: compute_execution_stats
set_var "EXECUTION_DURATION" "" "compute_execution_stats"

# Node: count_processed_tasks
set_var "TOTAL_TASKS" "" "count_processed_tasks"

# Node: calculate_throughput
set_var "THROUGHPUT" "" "calculate_throughput"

# Node: final_report
echo "# 🚀 Parallel Iteration Node Example Results

## Configuration Summary
- **Total Tasks**: $(get_var "TOTAL_TASKS" "final_report")
- **Max Concurrent**: $(get_var "MAX_CONCURRENT" "final_report")
- **Chunk Size**: $(get_var "CHUNK_SIZE" "final_report")
- **Error Handling**: $(get_var "ERROR_HANDLING" "final_report")
- **Progress Tracking**: $(get_var "ENABLE_PROGRESS_TRACKING" "final_report")

## Performance Metrics
- **Execution Time**: $(get_var "EXECUTION_DURATION" "final_report") seconds
- **Throughput**: $(get_var "THROUGHPUT" "final_report") tasks/second
- **Concurrency Efficiency**: $(get_var "MAX_CONCURRENT" "final_report") parallel workers
- **Chunk Processing**: $(get_var "CHUNK_SIZE" "final_report") tasks per batch

## Processing Results

$(get_var "COMBINED_RESULTS" "final_report")

## Parallel Processing Analysis

### Concurrency Benefits
- **Scalability**: Processing $(get_var "TOTAL_TASKS" "final_report") tasks across $(get_var "MAX_CONCURRENT" "final_report") parallel workers
- **Resource Optimization**: Chunked processing with $(get_var "CHUNK_SIZE" "final_report") items per batch
- **Error Resilience**: $(get_var "ERROR_HANDLING" "final_report") strategy for handling individual failures
- **Progress Monitoring**: Real-time tracking of $(get_var "ENABLE_PROGRESS_TRACKING" "final_report") execution progress

### Performance Characteristics
- **Parallel Speedup**: Theoretical max $(get_var "MAX_CONCURRENT" "final_report")x improvement over sequential processing
- **Actual Throughput**: $(get_var "THROUGHPUT" "final_report") tasks/second with current configuration
- **Resource Utilization**: Balanced load across available parallel workers
- **Fault Tolerance**: Robust error handling ensures workflow continuation

## Parallel Iteration Node Features Demonstrated

- **Concurrent Execution**: Multiple tasks running simultaneously
- **Configurable Parallelism**: Adjustable concurrent worker limits
- **Chunked Processing**: Batch processing for memory efficiency
- **Progress Tracking**: Real-time monitoring of execution progress
- **Error Handling Strategies**: Multiple approaches to handle failures
- **Performance Optimization**: Automatic load balancing and resource management
- **Worker Management**: Intelligent worker allocation and task distribution
- **Result Aggregation**: Efficient collection and combination of parallel results
- **Scalability Controls**: Fine-tuned performance parameters

This example showcases how parallel iteration nodes enable high-performance processing of large datasets with intelligent concurrency management and robust error handling.
"

echo "Workflow completed successfully"
exit 0
