#!/bin/bash
set -euo pipefail

# retry-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: retry-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# =============================================================================
# VARIABLE MANAGEMENT FUNCTIONS
# =============================================================================

# Set variable with debug logging
# Usage: set_var "variable_name" "value" "node_id"
set_var() {
    local var_name="$1"
    local value="$2" 
    local node_id="${3:-root}"
    
    # Set the variable globally
    declare -g "$var_name"="$value"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: SET $var_name = '$value'" >&2
    fi
}

# Get variable value with debug logging  
# Usage: get_var "variable_name" "node_id"
get_var() {
    local var_name="$1"
    local node_id="${2:-root}"
    
    # Get the variable value using indirect expansion
    local value="${!var_name:-}"
    
    # Debug logging when FLOWSH_DEBUG=true
    if [[ "${FLOWSH_DEBUG:-false}" == "true" ]]; then
        echo "[DEBUG] $node_id: GET $var_name = '$value'" >&2
    fi
    
    # Return the value
    echo "$value"
}

# Environment Variables
MAX_RETRY_ATTEMPTS=${MAX_RETRY_ATTEMPTS:-"5"}
BASE_DELAY=${BASE_DELAY:-"2"}
BACKOFF_MULTIPLIER=${BACKOFF_MULTIPLIER:-"1.5"}
OPERATION_TIMEOUT=${OPERATION_TIMEOUT:-"60"}
FAILURE_SIMULATION=${FAILURE_SIMULATION:-"intermittent"}
RETRY_ATTEMPT_COUNT=${RETRY_ATTEMPT_COUNT:-""}
OPERATION_SUCCESS_COUNT=${OPERATION_SUCCESS_COUNT:-""}
NETWORK_OPERATION_RESULT=${NETWORK_OPERATION_RESULT:-""}
TIMEOUT_OPERATION_RESULT=${TIMEOUT_OPERATION_RESULT:-""}
NETWORK_SPECIFIC_RESULT=${NETWORK_SPECIFIC_RESULT:-""}
COMPLEX_OPERATION_RESULT=${COMPLEX_OPERATION_RESULT:-""}
RETRY_STATISTICS=${RETRY_STATISTICS:-""}
COMBINED_RETRY_RESULTS=${COMBINED_RETRY_RESULTS:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    
    # First check workflow_vars array
    local workflow_value="${workflow_vars[$var_name]:-}"
    if [[ -n "$workflow_value" ]]; then
        echo "$workflow_value"
        return
    fi
    
    # Fallback to environment variable (uppercase version)
    local env_var_name="${var_name^^}"  # Convert to uppercase
    local env_value="${!env_var_name:-}"
    if [[ -n "$env_value" ]]; then
        echo "$env_value"
        return
    fi
    
    # Finally use default value
    echo "$default_value"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Temporary file management
declare -a FLOWSH_TEMP_FILES=()

register_temp_file() {
    local temp_path="$1"
    FLOWSH_TEMP_FILES+=("$temp_path")
    log_debug "Registered temp file: $temp_path"
}

cleanup_temp_files() {
    local cleaned_count=0
    local failed_count=0
    
    for temp_file in "${FLOWSH_TEMP_FILES[@]}"; do
        if [[ -e "$temp_file" ]]; then
            if rm -rf "$temp_file" 2>/dev/null; then
                ((cleaned_count++))
                log_debug "Cleaned up temp file: $temp_file"
            else
                ((failed_count++))
                log_warning "Failed to clean up temp file: $temp_file"
            fi
        fi
    done
    
    # Clear the temp files array
    FLOWSH_TEMP_FILES=()
    
    if [[ $cleaned_count -gt 0 ]]; then
        log_info "Cleaned up $cleaned_count temporary files"
    fi
    
    if [[ $failed_count -gt 0 ]]; then
        log_warning "Failed to clean up $failed_count temporary files"
    fi
    
    return 0
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Process tracking for parallel execution
declare -a FLOWSH_ACTIVE_PIDS=()

register_process() {
    local pid="$1"
    local description="${2:-unknown}"
     
     # Use case statement instead of regex for PID validation
     case "$pid" in
         ''|*[!0-9]*) log_warning "Invalid PID for registration: $pid" ;;
         *)
             FLOWSH_ACTIVE_PIDS+=("$pid")
             log_debug "Registered process $pid: $description"
             ;;
     esac
}

unregister_process() {
    local pid="$1"
    local new_pids=()
    
    for active_pid in "${FLOWSH_ACTIVE_PIDS[@]}"; do
        if [[ "$active_pid" != "$pid" ]]; then
            new_pids+=("$active_pid")
        fi
    done
    
    FLOWSH_ACTIVE_PIDS=("${new_pids[@]}")
    log_debug "Unregistered process $pid"
}

# Mock circuit breaker operation for testing
execute_circuit_breaker_operation() {
    local timeout_seconds="${1:-30}"
    local failure_threshold="${2:-3}"
    log_info "Mock circuit breaker operation (timeout: ${timeout_seconds}s, threshold: ${failure_threshold})"
    
    # Simulate circuit breaker with 25% failure rate
    if [[ $((RANDOM % 4)) -eq 0 ]]; then
        log_warning "Mock circuit breaker: operation failed (simulated failure)"
        return 1
    else
        sleep 2
        log_success "Mock circuit breaker: operation succeeded"
        return 0
    fi
}

# Mock retry command execution
execute_retry_command() {
    local attempt_number="${1:-1}"
    local max_attempts="${2:-3}"
    log_info "Mock retry command execution (attempt $attempt_number/$max_attempts)"
    
    # Simulate work
    sleep 1
    
    # Simulate success after 2 attempts for realistic retry testing
    if [[ $attempt_number -ge 2 ]]; then
        log_success "Mock retry command: succeeded after $attempt_number attempts"
        return 0
    else
        log_warning "Mock retry command: failed on attempt $attempt_number"
        return 1
    fi
}

# Mock sequential iteration processing
execute_iteration_iterate_files_sequential() {
    local pattern="${1:-*}"
    log_info "Mock sequential iteration: processing files matching '$pattern'"
    
    # Simulate file processing
    sleep 0.5
    local files=("file1.txt" "file2.txt" "file3.txt")
    
    for file in "${files[@]}"; do
        log_info "Processing file: $file"
        sleep 0.5
    done
    
    log_success "Sequential iteration completed: processed ${#files[@]} files"
    return 0
}

# Mock fallback path execution for testing
execute_fallback_path() {
    local path_id="${1}"
    log_info "Mock fallback path execution: $path_id"
    
    # Simulate work
    sleep 1
    
    # Simulate success for primary_service_call, failure for others to test fallback behavior
    case "$path_id" in
        "primary_service_call")
            log_success "Primary service call succeeded"
            return 0
            ;;
        "secondary_service_call") 
            log_warning "Secondary service call failed"
            return 1
            ;;
        "cache_fallback_call")
            log_warning "Cache fallback failed"
            return 1
            ;;
        "default_response_call")
            log_success "Default response call succeeded"
            return 0
            ;;
        *)
            log_info "Unknown fallback path succeeded: $path_id"
            return 0
            ;;
    esac
}

# Workflow Execution

# Node: initialize_retry_tracking
set_var "RETRY_ATTEMPT_COUNT" "0" "initialize_retry_tracking"

# Node: initialize_success_tracking
set_var "OPERATION_SUCCESS_COUNT" "0" "initialize_success_tracking"

# Node: retry_network_operation
# Node: retry_network_operation (retry_network_operation)
execute_retry_retry_network_operation() {
    log_step "🔄 Retry Handler: Retry Network Operation"
    local max_attempts=$(get_workflow_var "max_retry_attempts" "3")
    local retry_delay=$(get_workflow_var "base_delay" "5")
    local backoff_multiplier=$(get_workflow_var "backoff_multiplier" "2")
    local retry_condition="any_failure"
    local timeout_seconds=$(get_workflow_var "operation_timeout" "30")
    
    log_info "Starting retry handler: max_attempts=$max_attempts, delay=$retry_delay, condition=$retry_condition"
    for attempt in $(seq 1 $max_attempts); do
        log_info "Retry attempt $attempt/$max_attempts"
        
        local start_time=$(date +%s)
        local should_retry=false
        local exit_code=0
        
        # Execute with timeout
        if execute_retry_command "$attempt" "$max_attempts"; then
            log_success "Retry attempt $attempt succeeded"
            return 0
        else
            exit_code=$?
            log_warning "Retry attempt $attempt failed with exit code: $exit_code"
        fi
        
        # Check if we should retry based on condition
        # Retry on any failure
        should_retry=true
        log_debug "Will retry on any failure"
        
        if [[ "$should_retry" == "false" ]]; then
            log_error "Non-retryable condition detected, stopping retries"
            return $exit_code
        fi
        
        # Don't sleep after the last attempt
        if [[ $attempt -lt $max_attempts ]]; then
            local delay_time=$(echo "$retry_delay * ($backoff_multiplier ^ ($attempt - 1))" | bc -l)
            local rounded_delay=$(printf "%.0f" "$delay_time")
            log_info "Waiting $rounded_delay seconds before next attempt..."
            sleep "$rounded_delay"
        fi
    done
    
    log_error "All $max_attempts retry attempts failed"
    return $exit_code
}
execute_retry_retry_network_operation

# Node: simulate_network_call
sh -c "echo 'Attempting network operation...' && if [ '$(get_var "FAILURE_SIMULATION" "simulate_network_call")' = 'intermittent' ] && [ $(( RANDOM % 3 )) -eq 0 ]; then echo 'Network operation failed' && exit 1; else echo 'Network operation successful' && exit 0; fi"

# Node: record_network_success
set_var "NETWORK_OPERATION_RESULT" "Network operation completed successfully after retries" "record_network_success"

# Node: retry_timeout_operation
# Node: retry_timeout_operation (retry_timeout_operation)
execute_retry_retry_timeout_operation() {
    log_step "🔄 Retry Handler: Retry Timeout-Prone Operation"
    local max_attempts=3
    local retry_delay=1
    local backoff_multiplier=2.0
    local retry_condition="timeout_only"
    local timeout_seconds=30
    
    log_info "Starting retry handler: max_attempts=$max_attempts, delay=$retry_delay, condition=$retry_condition"
    for attempt in $(seq 1 $max_attempts); do
        log_info "Retry attempt $attempt/$max_attempts"
        
        local start_time=$(date +%s)
        local should_retry=false
        local exit_code=0
        
        # Execute with timeout
        if execute_retry_command "$attempt" "$max_attempts"; then
            log_success "Retry attempt $attempt succeeded"
            return 0
        else
            exit_code=$?
            log_warning "Retry attempt $attempt failed with exit code: $exit_code"
        fi
        
        # Check if we should retry based on condition
        # Retry only on timeout errors
        if [[ $exit_code -eq 124 || $exit_code -eq 142 ]]; then
            should_retry=true
            log_debug "Timeout detected (exit code: $exit_code)"
        else
            should_retry=false
            log_debug "Non-timeout failure (exit code: $exit_code)"
        fi
        
        if [[ "$should_retry" == "false" ]]; then
            log_error "Non-retryable condition detected, stopping retries"
            return $exit_code
        fi
        
        # Don't sleep after the last attempt
        if [[ $attempt -lt $max_attempts ]]; then
            local delay_time=$(echo "$retry_delay * ($backoff_multiplier ^ ($attempt - 1))" | bc -l)
            local rounded_delay=$(printf "%.0f" "$delay_time")
            log_info "Waiting $rounded_delay seconds before next attempt..."
            sleep "$rounded_delay"
        fi
    done
    
    log_error "All $max_attempts retry attempts failed"
    return $exit_code
}
execute_retry_retry_timeout_operation

# Node: simulate_timeout_operation
sh -c "echo 'Starting timeout-prone operation...' && if [ '$(get_var "FAILURE_SIMULATION" "simulate_timeout_operation")' = 'timeout' ]; then sleep 15 && echo 'Operation timed out'; else echo 'Operation completed within timeout' && exit 0; fi"

# Node: record_timeout_success
set_var "TIMEOUT_OPERATION_RESULT" "Timeout operation completed successfully" "record_timeout_success"

# Node: retry_network_only
# Node: retry_network_only (retry_network_only)
execute_retry_retry_network_only() {
    log_step "🔄 Retry Handler: Retry Network-Only Failures"
    local max_attempts=4
    local retry_delay=3
    local backoff_multiplier=1.8
    local retry_condition="network_only"
    local timeout_seconds=45
    
    log_info "Starting retry handler: max_attempts=$max_attempts, delay=$retry_delay, condition=$retry_condition"
    for attempt in $(seq 1 $max_attempts); do
        log_info "Retry attempt $attempt/$max_attempts"
        
        local start_time=$(date +%s)
        local should_retry=false
        local exit_code=0
        
        # Execute with timeout
        if execute_retry_command "$attempt" "$max_attempts"; then
            log_success "Retry attempt $attempt succeeded"
            return 0
        else
            exit_code=$?
            log_warning "Retry attempt $attempt failed with exit code: $exit_code"
        fi
        
        # Check if we should retry based on condition
        # Retry only on network-related errors
        case $exit_code in
            6|7|28|35|56)  # curl network error codes
                should_retry=true
                log_debug "Network error detected (exit code: $exit_code)"
                ;;
            *)
                should_retry=false
                log_debug "Non-network failure (exit code: $exit_code)"
                ;;
        esac
        
        if [[ "$should_retry" == "false" ]]; then
            log_error "Non-retryable condition detected, stopping retries"
            return $exit_code
        fi
        
        # Don't sleep after the last attempt
        if [[ $attempt -lt $max_attempts ]]; then
            local delay_time=$(echo "$retry_delay * ($backoff_multiplier ^ ($attempt - 1))" | bc -l)
            local rounded_delay=$(printf "%.0f" "$delay_time")
            log_info "Waiting $rounded_delay seconds before next attempt..."
            sleep "$rounded_delay"
        fi
    done
    
    log_error "All $max_attempts retry attempts failed"
    return $exit_code
}
execute_retry_retry_network_only

# Node: simulate_network_specific
sh -c "echo 'Network-specific operation starting...' && if [ '$(get_var "FAILURE_SIMULATION" "simulate_network_specific")' = 'network' ] && [ $(( RANDOM % 2 )) -eq 0 ]; then echo 'Network connectivity issue' && exit 2; else echo 'Network operation successful' && exit 0; fi"

# Node: record_network_specific_success
set_var "NETWORK_SPECIFIC_RESULT" "Network-specific operation completed after appropriate retries" "record_network_specific_success"

# Node: advanced_retry_operation
# Node: advanced_retry_operation (advanced_retry_operation)
execute_retry_advanced_retry_operation() {
    log_step "🔄 Retry Handler: Advanced Retry with Custom Logic"
    local max_attempts=$(get_workflow_var "max_retry_attempts" "3")
    local retry_delay=$(get_workflow_var "base_delay" "5")
    local backoff_multiplier=$(get_workflow_var "backoff_multiplier" "2")
    local retry_condition="any_failure"
    local timeout_seconds=$(get_workflow_var "operation_timeout" "30")
    
    log_info "Starting retry handler: max_attempts=$max_attempts, delay=$retry_delay, condition=$retry_condition"
    for attempt in $(seq 1 $max_attempts); do
        log_info "Retry attempt $attempt/$max_attempts"
        
        local start_time=$(date +%s)
        local should_retry=false
        local exit_code=0
        
        # Execute with timeout
        if execute_retry_command "$attempt" "$max_attempts"; then
            log_success "Retry attempt $attempt succeeded"
            return 0
        else
            exit_code=$?
            log_warning "Retry attempt $attempt failed with exit code: $exit_code"
        fi
        
        # Check if we should retry based on condition
        # Retry on any failure
        should_retry=true
        log_debug "Will retry on any failure"
        
        if [[ "$should_retry" == "false" ]]; then
            log_error "Non-retryable condition detected, stopping retries"
            return $exit_code
        fi
        
        # Don't sleep after the last attempt
        if [[ $attempt -lt $max_attempts ]]; then
            local delay_time=$(echo "$retry_delay * ($backoff_multiplier ^ ($attempt - 1))" | bc -l)
            local rounded_delay=$(printf "%.0f" "$delay_time")
            log_info "Waiting $rounded_delay seconds before next attempt..."
            sleep "$rounded_delay"
        fi
    done
    
    log_error "All $max_attempts retry attempts failed"
    return $exit_code
}
execute_retry_advanced_retry_operation

# Node: complex_operation_simulation
sh -c "echo 'Complex operation attempt...' && case '$(get_var "FAILURE_SIMULATION" "complex_operation_simulation")' in 'none') echo 'Success on first try' && exit 0 ;; 'intermittent') if [ $(( RANDOM % 4 )) -eq 0 ]; then echo 'Success after intermittent failure' && exit 0; else echo 'Intermittent failure' && exit 1; fi ;; 'timeout') sleep 2 && echo 'Complex operation success' && exit 0 ;; 'network') if [ $(( RANDOM % 3 )) -eq 0 ]; then echo 'Network success' && exit 0; else echo 'Network failure' && exit 1; fi ;; esac"

# Node: record_complex_success
# Node: record_complex_success
COMPLEX_OPERATION_RESULT=$(echo 'Complex operation succeeded with $(get_workflow_var "FAILURE_SIMULATION" "0") simulation mode after retry logic')
set_var "COMPLEX_OPERATION_RESULT" "$COMPLEX_OPERATION_RESULT" "record_complex_success"

# Node: calculate_retry_statistics
# Node: calculate_retry_statistics
RETRY_STATISTICS=$(echo 'Retry Statistics: Max attempts=$(get_workflow_var "MAX_RETRY_ATTEMPTS" "0"), Base delay=$(get_workflow_var "BASE_DELAY" "0")s, Backoff=$(get_workflow_var "BACKOFF_MULTIPLIER" "0")x, Timeout=$(get_workflow_var "OPERATION_TIMEOUT" "0")s, Simulation=$(get_workflow_var "FAILURE_SIMULATION" "0")')
set_var "RETRY_STATISTICS" "$RETRY_STATISTICS" "calculate_retry_statistics"

# Node: aggregate_all_results

# Node: aggregate_all_results (Aggregate All Retry Results)
execute_aggregation_aggregate_all_results() {
    log_step "📊 Variable Aggregation: Aggregate All Retry Results"

    local -a input_vars=("NETWORK_OPERATION_RESULT" "TIMEOUT_OPERATION_RESULT" "NETWORK_SPECIFIC_RESULT" "COMPLEX_OPERATION_RESULT")
    local output_var="combined_retry_results"
    local method="concat"
    local separator=$'
'

    log_debug "Concatenating ${#input_vars[@]} variables with separator"
    local -a values=()
    for var_name in "${input_vars[@]}"; do
        local value="$(get_workflow_var "$var_name" "")"
        [[ -n "$value" ]] && values+=("$value")
    done
    
    if [[ ${#values[@]} -eq 0 ]]; then
        log_warning "No non-empty values to concatenate"
        set_workflow_var "$output_var" ""
    else
        local result
        result=$(IFS="$separator"; echo "${values[*]}")
        set_workflow_var "$output_var" "$result"
        log_success "Concatenated ${#values[@]} values into $output_var"
    fi

    log_success "Variable aggregation completed: ${#input_vars[@]} inputs -> $output_var"
}
execute_aggregation_aggregate_all_results

# Node: final_report
echo "# 🔄 Retry Node Example Results

## Retry Configuration
- **Maximum Attempts**: $(get_var "MAX_RETRY_ATTEMPTS" "final_report")
- **Base Delay**: $(get_var "BASE_DELAY" "final_report") seconds
- **Backoff Multiplier**: $(get_var "BACKOFF_MULTIPLIER" "final_report")x
- **Operation Timeout**: $(get_var "OPERATION_TIMEOUT" "final_report") seconds
- **Failure Simulation**: $(get_var "FAILURE_SIMULATION" "final_report")

## Retry Operations Performed

### 1. Network Operation with Intermittent Failures
- **Retry Condition**: Any failure
- **Strategy**: Exponential backoff for all failure types
- **Use Case**: General network operations with unpredictable failures

### 2. Timeout-Specific Retry Pattern
- **Retry Condition**: Timeout only
- **Strategy**: Faster retry cycle for timeout-specific issues
- **Use Case**: Operations prone to timeout but not other failures

### 3. Network-Only Failure Retry
- **Retry Condition**: Network failures only
- **Strategy**: Moderate backoff for network connectivity issues
- **Use Case**: Network-dependent operations with stable processing

### 4. Advanced Retry with Complex Logic
- **Retry Condition**: Any failure with custom handling
- **Strategy**: Full configurability with multiple failure modes
- **Use Case**: Complex operations requiring sophisticated retry logic

## Retry Results Summary

$(get_var "COMBINED_RETRY_RESULTS" "final_report")

## Performance Metrics
$(get_var "RETRY_STATISTICS" "final_report")

## Retry Node Features Demonstrated

### Retry Conditions
- **Any Failure**: Retry on any type of operation failure
- **Timeout Only**: Retry specifically for timeout conditions
- **Network Only**: Retry for network-related failures only

### Backoff Strategies
- **Linear Backoff**: Fixed delay between retries
- **Exponential Backoff**: Increasing delays with configurable multiplier
- **Custom Delays**: Flexible delay configuration per retry pattern

### Timeout Management
- **Operation Timeout**: Overall timeout for entire retry sequence
- **Individual Timeouts**: Per-attempt timeout control
- **Escalation Logic**: Timeout handling with retry escalation

### Failure Classification
- **Transient Failures**: Temporary issues that may resolve with retry
- **Persistent Failures**: Issues requiring different handling strategies
- **Timeout Failures**: Specific timeout-related failure handling
- **Network Failures**: Connectivity and network-specific issues

### Advanced Features
- **Configurable Attempts**: Flexible maximum retry count
- **Dynamic Delays**: Runtime calculation of retry delays
- **Condition-Based Retries**: Different retry logic for different failure types
- **Result Tracking**: Comprehensive logging of retry attempts and outcomes
- **Integration Ready**: Seamless integration with other workflow nodes

### Use Cases
- **API Integration**: Reliable communication with external services
- **Database Operations**: Resilient data access with connection retry
- **File Operations**: Robust file system interactions
- **Network Services**: Fault-tolerant network communications
- **Batch Processing**: Reliable large-scale data processing
- **Microservice Communication**: Inter-service reliability patterns

## Retry Best Practices Demonstrated

1. **Exponential Backoff**: Reduces load on failing services
2. **Maximum Attempt Limits**: Prevents infinite retry loops
3. **Timeout Controls**: Ensures bounded execution time
4. **Failure Classification**: Different strategies for different failure types
5. **Result Aggregation**: Comprehensive tracking and reporting
6. **Configuration Flexibility**: Runtime adjustment of retry parameters

This example showcases how retry nodes provide robust failure recovery mechanisms essential for reliable workflow execution in distributed and network-dependent environments.
"

echo "Workflow completed successfully"
exit 0
