#!/bin/bash
set -euo pipefail

# template-transform-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: template-transform-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# Environment Variables
USER_NAME=${USER_NAME:-""}
PROJECT_NAME=${PROJECT_NAME:-""}
TEMPLATE_TYPE=${TEMPLATE_TYPE:-""}
URGENCY_LEVEL=${URGENCY_LEVEL:-""}
INCLUDE_DETAILS=${INCLUDE_DETAILS:-""}
CURRENT_TIMESTAMP=${CURRENT_TIMESTAMP:-""}
TEMPLATE_METADATA=${TEMPLATE_METADATA:-""}
URGENCY_PREFIX=${URGENCY_PREFIX:-""}
GREETING_MESSAGE=${GREETING_MESSAGE:-""}
PROJECT_STATUS=${PROJECT_STATUS:-""}
NEXT_STEPS=${NEXT_STEPS:-""}
FOOTER_INFO=${FOOTER_INFO:-""}
GENERATED_EMAIL=${GENERATED_EMAIL:-""}
REPORT_TITLE=${REPORT_TITLE:-""}
EXECUTIVE_SUMMARY=${EXECUTIVE_SUMMARY:-""}
DETAILED_ANALYSIS=${DETAILED_ANALYSIS:-""}
RECOMMENDATIONS=${RECOMMENDATIONS:-""}
CONCLUSION=${CONCLUSION:-""}
GENERATED_REPORT=${GENERATED_REPORT:-""}
INCLUDE_DETAILS_BOOL=${INCLUDE_DETAILS_BOOL:-""}
DEBUG_ENABLED=${DEBUG_ENABLED:-""}
GENERATION_INFO=${GENERATION_INFO:-""}
METADATA_SECTION=${METADATA_SECTION:-""}
GENERATED_CONFIG=${GENERATED_CONFIG:-""}
OVERVIEW_CONTENT=${OVERVIEW_CONTENT:-""}
PROJECT_NAME_SLUG=${PROJECT_NAME_SLUG:-""}
CONFIG_INSTRUCTIONS=${CONFIG_INSTRUCTIONS:-""}
ADVANCED_USAGE=${ADVANCED_USAGE:-""}
API_REFERENCE=${API_REFERENCE:-""}
SUPPORT_INFO=${SUPPORT_INFO:-""}
GENERATED_DOCS=${GENERATED_DOCS:-""}
ALL_TEMPLATE_OUTPUTS=${ALL_TEMPLATE_OUTPUTS:-""}
TEMPLATE_SUMMARY=${TEMPLATE_SUMMARY:-""}
VARIABLE_NAME=${VARIABLE_NAME:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: prepare_timestamp
CURRENT_TIMESTAMP=""

# Node: prepare_metadata
TEMPLATE_METADATA=""

# Node: transform_email_template

# Node: transform_email_template (Transform Email Template)
execute_template_transform_transform_email_template() {
    log_step "🔧 Template Transform: Transform Email Template"

    local output_var="generated_email"
    local template_content=""

    # Inline template content
    template_content='Subject: {{urgency_prefix}}Project Update: {{project_name}}

Dear {{user_name}},

{{greeting_message}}

Project: {{project_name}}
Status: {{project_status}}
Priority: {{urgency_level}}
{{#include_details}}

Detailed Information:
- Generated: {{current_timestamp}}
- Template Type: {{template_type}}
- Metadata: {{template_metadata}}

Next Steps:
{{next_steps}}
{{/include_details}}

Best regards,
The {{project_name}} Team

---
{{footer_info}}
'
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # Apply template parameters (variable substitution)
    local param_value="${user_name}"
    log_debug "Processing parameter: user_name = $param_value"
    rendered_content="${rendered_content//\{\{user_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{user_name\}/$param_value}"
    local param_value="${project_name}"
    log_debug "Processing parameter: project_name = $param_value"
    rendered_content="${rendered_content//\{\{project_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{project_name\}/$param_value}"
    local param_value="${urgency_level}"
    log_debug "Processing parameter: urgency_level = $param_value"
    rendered_content="${rendered_content//\{\{urgency_level\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{urgency_level\}/$param_value}"
    local param_value="if [ '${urgency_level}' = 'critical' ]; then echo '[URGENT] '; elif [ '${urgency_level}' = 'high' ]; then echo '[HIGH] '; else echo ''; fi"
    log_debug "Processing parameter: urgency_prefix = $param_value"
    rendered_content="${rendered_content//\{\{urgency_prefix\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{urgency_prefix\}/$param_value}"
    local param_value="In Progress"
    log_debug "Processing parameter: project_status = $param_value"
    rendered_content="${rendered_content//\{\{project_status\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{project_status\}/$param_value}"
    local param_value="I hope this message finds you well. Here's an update on your project."
    log_debug "Processing parameter: greeting_message = $param_value"
    rendered_content="${rendered_content//\{\{greeting_message\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{greeting_message\}/$param_value}"
    local param_value="${current_timestamp}"
    log_debug "Processing parameter: current_timestamp = $param_value"
    rendered_content="${rendered_content//\{\{current_timestamp\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{current_timestamp\}/$param_value}"
    local param_value="${template_type}"
    log_debug "Processing parameter: template_type = $param_value"
    rendered_content="${rendered_content//\{\{template_type\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_type\}/$param_value}"
    local param_value="${template_metadata}"
    log_debug "Processing parameter: template_metadata = $param_value"
    rendered_content="${rendered_content//\{\{template_metadata\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_metadata\}/$param_value}"
    local param_value="${include_details}"
    log_debug "Processing parameter: include_details = $param_value"
    rendered_content="${rendered_content//\{\{include_details\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{include_details\}/$param_value}"
    local param_value="1. Review the current progress
2. Provide feedback on deliverables
3. Schedule next milestone meeting"
    log_debug "Processing parameter: next_steps = $param_value"
    rendered_content="${rendered_content//\{\{next_steps\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{next_steps\}/$param_value}"
    local param_value="This email was generated automatically by the flowsh workflow system."
    log_debug "Processing parameter: footer_info = $param_value"
    rendered_content="${rendered_content//\{\{footer_info\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{footer_info\}/$param_value}"


    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node transform_email_template
process_template_functions_transform_email_template() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_transform_email_template "$1"
}

# Node: transform_report_template

# Node: transform_report_template (Transform Report Template)
execute_template_transform_transform_report_template() {
    log_step "🔧 Template Transform: Transform Report Template"

    local output_var="generated_report"
    local template_content=""

    # Inline template content
    template_content='# {{report_title}}

**Generated:** {{current_timestamp}}  
**Author:** {{user_name}}  
**Project:** {{project_name}}  
**Priority:** {{urgency_level}}

## Executive Summary

{{executive_summary}}

## Project Details

| Attribute | Value |
|-----------|-------|
| Name | {{project_name}} |
| Owner | {{user_name}} |
| Priority | {{urgency_level}} |
| Generated | {{current_timestamp}} |
| Template | {{template_type}} |

{{#include_details}}
## Detailed Analysis

{{detailed_analysis}}

### Metadata Information
```
{{template_metadata}}
```

### Recommendations
{{recommendations}}
{{/include_details}}

## Conclusion

{{conclusion}}

---
*Report generated by flowsh template transformation system*
'
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # Apply template parameters (variable substitution)
    local param_value="Project Status Report: ${project_name}"
    log_debug "Processing parameter: report_title = $param_value"
    rendered_content="${rendered_content//\{\{report_title\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{report_title\}/$param_value}"
    local param_value="${user_name}"
    log_debug "Processing parameter: user_name = $param_value"
    rendered_content="${rendered_content//\{\{user_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{user_name\}/$param_value}"
    local param_value="${project_name}"
    log_debug "Processing parameter: project_name = $param_value"
    rendered_content="${rendered_content//\{\{project_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{project_name\}/$param_value}"
    local param_value="${urgency_level}"
    log_debug "Processing parameter: urgency_level = $param_value"
    rendered_content="${rendered_content//\{\{urgency_level\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{urgency_level\}/$param_value}"
    local param_value="${current_timestamp}"
    log_debug "Processing parameter: current_timestamp = $param_value"
    rendered_content="${rendered_content//\{\{current_timestamp\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{current_timestamp\}/$param_value}"
    local param_value="${template_type}"
    log_debug "Processing parameter: template_type = $param_value"
    rendered_content="${rendered_content//\{\{template_type\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_type\}/$param_value}"
    local param_value="${template_metadata}"
    log_debug "Processing parameter: template_metadata = $param_value"
    rendered_content="${rendered_content//\{\{template_metadata\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_metadata\}/$param_value}"
    local param_value="${include_details}"
    log_debug "Processing parameter: include_details = $param_value"
    rendered_content="${rendered_content//\{\{include_details\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{include_details\}/$param_value}"
    local param_value="This report provides a comprehensive overview of the current project status, highlighting key achievements, challenges, and next steps for ${project_name}."
    log_debug "Processing parameter: executive_summary = $param_value"
    rendered_content="${rendered_content//\{\{executive_summary\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{executive_summary\}/$param_value}"
    local param_value="The project is progressing according to schedule with ${urgency_level} priority. All major milestones are on track for completion within the established timeline."
    log_debug "Processing parameter: detailed_analysis = $param_value"
    rendered_content="${rendered_content//\{\{detailed_analysis\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{detailed_analysis\}/$param_value}"
    local param_value="1. Continue current development approach
2. Monitor ${urgency_level} priority items closely
3. Schedule regular progress reviews"
    log_debug "Processing parameter: recommendations = $param_value"
    rendered_content="${rendered_content//\{\{recommendations\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{recommendations\}/$param_value}"
    local param_value="The ${project_name} project is well-positioned for successful completion. Continued focus on ${urgency_level} priority items will ensure optimal outcomes."
    log_debug "Processing parameter: conclusion = $param_value"
    rendered_content="${rendered_content//\{\{conclusion\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{conclusion\}/$param_value}"


    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node transform_report_template
process_template_functions_transform_report_template() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_transform_report_template "$1"
}

# Node: transform_config_template

# Node: transform_config_template (Transform Configuration Template)
execute_template_transform_transform_config_template() {
    log_step "🔧 Template Transform: Transform Configuration Template"

    local output_var="generated_config"
    local template_content=""

    # Inline template content
    template_content='# {{project_name}} Configuration
# Generated: {{current_timestamp}}
# Owner: {{user_name}}

[project]
name = \"{{project_name}}\"
owner = \"{{user_name}}\"
priority = \"{{urgency_level}}\"
generated_at = \"{{current_timestamp}}\"

[settings]
template_type = \"{{template_type}}\"
include_details = {{include_details_bool}}
debug_mode = {{debug_enabled}}

{{#include_details}}
[detailed_config]
metadata = \"{{template_metadata}}\"
generation_info = \"{{generation_info}}\"

[advanced_settings]
auto_backup = true
compression = \"gzip\"
retention_days = 30
{{/include_details}}

[metadata]
{{metadata_section}}
'
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # Apply template parameters (variable substitution)
    local param_value="${project_name}"
    log_debug "Processing parameter: project_name = $param_value"
    rendered_content="${rendered_content//\{\{project_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{project_name\}/$param_value}"
    local param_value="${user_name}"
    log_debug "Processing parameter: user_name = $param_value"
    rendered_content="${rendered_content//\{\{user_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{user_name\}/$param_value}"
    local param_value="${urgency_level}"
    log_debug "Processing parameter: urgency_level = $param_value"
    rendered_content="${rendered_content//\{\{urgency_level\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{urgency_level\}/$param_value}"
    local param_value="${current_timestamp}"
    log_debug "Processing parameter: current_timestamp = $param_value"
    rendered_content="${rendered_content//\{\{current_timestamp\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{current_timestamp\}/$param_value}"
    local param_value="${template_type}"
    log_debug "Processing parameter: template_type = $param_value"
    rendered_content="${rendered_content//\{\{template_type\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_type\}/$param_value}"
    local param_value="${template_metadata}"
    log_debug "Processing parameter: template_metadata = $param_value"
    rendered_content="${rendered_content//\{\{template_metadata\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_metadata\}/$param_value}"
    local param_value="${include_details}"
    log_debug "Processing parameter: include_details = $param_value"
    rendered_content="${rendered_content//\{\{include_details\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{include_details\}/$param_value}"
    local param_value="if [ '${include_details}' = 'true' ]; then echo 'true'; else echo 'false'; fi"
    log_debug "Processing parameter: include_details_bool = $param_value"
    rendered_content="${rendered_content//\{\{include_details_bool\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{include_details_bool\}/$param_value}"
    local param_value="if [ '${urgency_level}' = 'high' ] || [ '${urgency_level}' = 'critical' ]; then echo 'true'; else echo 'false'; fi"
    log_debug "Processing parameter: debug_enabled = $param_value"
    rendered_content="${rendered_content//\{\{debug_enabled\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{debug_enabled\}/$param_value}"
    local param_value="Generated by flowsh template transform node for ${project_name}"
    log_debug "Processing parameter: generation_info = $param_value"
    rendered_content="${rendered_content//\{\{generation_info\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{generation_info\}/$param_value}"
    local param_value="version = "1.0"
tags = ["${template_type}", "${urgency_level}"]
generated_by = "flowsh""
    log_debug "Processing parameter: metadata_section = $param_value"
    rendered_content="${rendered_content//\{\{metadata_section\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{metadata_section\}/$param_value}"


    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node transform_config_template
process_template_functions_transform_config_template() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_transform_config_template "$1"
}

# Node: transform_docs_template

# Node: transform_docs_template (Transform Documentation Template)
execute_template_transform_transform_docs_template() {
    log_step "🔧 Template Transform: Transform Documentation Template"

    local output_var="generated_docs"
    local template_content=""

    # Inline template content
    template_content='# {{project_name}} Documentation

> **Author:** {{user_name}}  
> **Generated:** {{current_timestamp}}  
> **Priority:** {{urgency_level}}

## Overview

{{overview_content}}

## Quick Start

```bash
# Clone the project
git clone https://github.com/{{user_name}}/{{project_name_slug}}.git
cd {{project_name_slug}}

# Install dependencies
npm install

# Start development
npm run dev
```

## Configuration

{{config_instructions}}

{{#include_details}}
## Advanced Usage

{{advanced_usage}}

### Template Information
- **Type:** {{template_type}}
- **Priority:** {{urgency_level}}
- **Metadata:** {{template_metadata}}

### API Reference

{{api_reference}}
{{/include_details}}

## Support

{{support_info}}

---

**Last updated:** {{current_timestamp}} by {{user_name}}
'
    log_debug "Using inline template content"

    # Validate template was resolved
    if [[ -z "$template_content" ]]; then
        log_error "Failed to resolve template content"
        set_workflow_var "$output_var" ""
        return 1
    fi

    log_debug "Template resolved, length: ${#template_content} characters"

    # Apply template parameters (basic substitution)
    local rendered_content="$template_content"

    # Apply template parameters (variable substitution)
    local param_value="${project_name}"
    log_debug "Processing parameter: project_name = $param_value"
    rendered_content="${rendered_content//\{\{project_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{project_name\}/$param_value}"
    local param_value="${user_name}"
    log_debug "Processing parameter: user_name = $param_value"
    rendered_content="${rendered_content//\{\{user_name\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{user_name\}/$param_value}"
    local param_value="${urgency_level}"
    log_debug "Processing parameter: urgency_level = $param_value"
    rendered_content="${rendered_content//\{\{urgency_level\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{urgency_level\}/$param_value}"
    local param_value="${current_timestamp}"
    log_debug "Processing parameter: current_timestamp = $param_value"
    rendered_content="${rendered_content//\{\{current_timestamp\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{current_timestamp\}/$param_value}"
    local param_value="${template_type}"
    log_debug "Processing parameter: template_type = $param_value"
    rendered_content="${rendered_content//\{\{template_type\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_type\}/$param_value}"
    local param_value="${template_metadata}"
    log_debug "Processing parameter: template_metadata = $param_value"
    rendered_content="${rendered_content//\{\{template_metadata\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{template_metadata\}/$param_value}"
    local param_value="${include_details}"
    log_debug "Processing parameter: include_details = $param_value"
    rendered_content="${rendered_content//\{\{include_details\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{include_details\}/$param_value}"
    local param_value="echo '${project_name}' | tr '[:upper:]' '[:lower:]' | tr ' ' '-'"
    log_debug "Processing parameter: project_name_slug = $param_value"
    rendered_content="${rendered_content//\{\{project_name_slug\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{project_name_slug\}/$param_value}"
    local param_value="Welcome to ${project_name}! This project provides powerful workflow automation capabilities with ${urgency_level} priority support."
    log_debug "Processing parameter: overview_content = $param_value"
    rendered_content="${rendered_content//\{\{overview_content\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{overview_content\}/$param_value}"
    local param_value="Configure your ${project_name} instance by editing the configuration file generated by the template transform system."
    log_debug "Processing parameter: config_instructions = $param_value"
    rendered_content="${rendered_content//\{\{config_instructions\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{config_instructions\}/$param_value}"
    local param_value="For advanced configurations, refer to the ${urgency_level} priority documentation sections and the template transformation examples."
    log_debug "Processing parameter: advanced_usage = $param_value"
    rendered_content="${rendered_content//\{\{advanced_usage\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{advanced_usage\}/$param_value}"
    local param_value="The API provides endpoints for template transformation, configuration management, and workflow automation specific to ${project_name}."
    log_debug "Processing parameter: api_reference = $param_value"
    rendered_content="${rendered_content//\{\{api_reference\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{api_reference\}/$param_value}"
    local param_value="For support, contact ${user_name} or visit the project documentation. Priority level: ${urgency_level}."
    log_debug "Processing parameter: support_info = $param_value"
    rendered_content="${rendered_content//\{\{support_info\}\}/$param_value}"
    rendered_content="${rendered_content//\$\{support_info\}/$param_value}"


    # Advanced template functions processing
    rendered_content=$(process_template_functions "$rendered_content")
    
    # Additional variable substitution for workflow variables
    rendered_content=$(substitute_variables "$rendered_content")

    # Set output variable
    set_workflow_var "$output_var" "$rendered_content"

    log_success "Template transformed and stored in $output_var"
    log_debug "Template output length: ${#rendered_content} characters"
}

# Advanced template function processor for node transform_docs_template
process_template_functions_transform_docs_template() {
    local content="$1"

    # {{#date}} -> current date (YYYY-MM-DD)
    content="${content//\{\{#date\}\}/$(date '+%Y-%m-%d')}"

    # {{#time}} -> current time (HH:MM:SS)
    content="${content//\{\{#time\}\}/$(date '+%H:%M:%S')}"

    # {{#datetime}} -> current date and time (ISO 8601)
    content="${content//\{\{#datetime\}\}/$(date -Iseconds)}"

    # {{#timestamp}} -> current Unix timestamp
    content="${content//\{\{#timestamp\}\}/$(date '+%s')}"

    # {{#uuid}} -> generate UUID (fallback if uuidgen not available)
    if command -v uuidgen >/dev/null 2>&1; then
        content="${content//\{\{#uuid\}\}/$(uuidgen)}"
    else
        # Fallback UUID generation using date and random
        local fallback_uuid="uuid-$(date +%s)-$RANDOM"
        content="${content//\{\{#uuid\}\}/$fallback_uuid}"
    fi

    # {{#random}} -> random number (0-32767)
    content="${content//\{\{#random\}\}/$RANDOM}"

    # {{#hostname}} -> current hostname
    content="${content//\{\{#hostname\}\}/$(hostname 2>/dev/null || echo 'unknown')}"

    # {{#user}} -> current user
    content="${content//\{\{#user\}\}/$(whoami 2>/dev/null || echo 'unknown')}"

    # {{#pwd}} -> current working directory
    content="${content//\{\{#pwd\}\}/$(pwd)}"

    # Process variable-based functions with regex matching
    # {{#base64:variable}} -> base64 encode variable
    while [[ "$content" =~ \{\{#base64:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            if command -v base64 >/dev/null 2>&1; then
                encoded_value="$(echo -n "$var_value" | base64 -w 0)"
            else
                log_warning "base64 command not available, skipping encoding for $var_name"
                encoded_value="$var_value"
            fi
        fi
        
        content="${content//\{\{#base64:$var_name\}\}/$encoded_value}"
    done

    # {{#url_encode:variable}} -> URL encode variable
    while [[ "$content" =~ \{\{#url_encode:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local encoded_value=""
        
        if [[ -n "$var_value" ]]; then
            # Simple URL encoding (encode spaces and special characters)
            encoded_value="$(echo "$var_value" | sed 's/ /%20/g; s/&/%26/g; s/?/%3F/g; s/=/%3D/g')"
        fi
        
        content="${content//\{\{#url_encode:$var_name\}\}/$encoded_value}"
    done

    # {{#upper:variable}} -> uppercase variable
    while [[ "$content" =~ \{\{#upper:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local upper_value=""
        
        if [[ -n "$var_value" ]]; then
            upper_value="$(echo "$var_value" | tr '[:lower:]' '[:upper:]')"
        fi
        
        content="${content//\{\{#upper:$var_name\}\}/$upper_value}"
    done

    # {{#lower:variable}} -> lowercase variable
    while [[ "$content" =~ \{\{#lower:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local lower_value=""
        
        if [[ -n "$var_value" ]]; then
            lower_value="$(echo "$var_value" | tr '[:upper:]' '[:lower:]')"
        fi
        
        content="${content//\{\{#lower:$var_name\}\}/$lower_value}"
    done

    # {{#length:variable}} -> length of variable
    while [[ "$content" =~ \{\{#length:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local length_value="${#var_value}"
        
        content="${content//\{\{#length:$var_name\}\}/$length_value}"
    done

    # {{#json_escape:variable}} -> JSON escape variable
    while [[ "$content" =~ \{\{#json_escape:([^}]+)\}\} ]]; do
        local var_name="${BASH_REMATCH[1]}"
        local var_value="$(get_workflow_var "$var_name" "")"
        local escaped_value=""
        
        if [[ -n "$var_value" ]]; then
            # Basic JSON escaping
            escaped_value="$(echo "$var_value" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g; s/\n/\\n/g; s/\r/\\r/g')"
        fi
        
        content="${content//\{\{#json_escape:$var_name\}\}/$escaped_value}"
    done

    echo "$content"
}

# Use the node-specific template function processor
process_template_functions() {
    process_template_functions_transform_docs_template "$1"
}

# Node: aggregate_templates

# Node: aggregate_templates (Aggregate All Template Outputs)
execute_aggregation_aggregate_templates() {
    log_step "📊 Variable Aggregation: Aggregate All Template Outputs"

    local -a input_vars=("generated_email" "generated_report" "generated_config" "generated_docs")
    local output_var="all_template_outputs"
    local method="concat"
    local separator=$'

=== TEMPLATE SEPARATOR ===

'

    case "$method" in
        "concat")
            log_debug "Concatenating ${#input_vars[@]} variables with separator"
            local -a values=()
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && values+=("$value")
            done
            
            if [[ ${#values[@]} -eq 0 ]]; then
                log_warning "No non-empty values to concatenate"
                set_workflow_var "$output_var" ""
            else
                local result
                result=$(IFS="$separator"; echo "${values[*]}")
                set_workflow_var "$output_var" "$result"
                log_success "Concatenated ${#values[@]} values into $output_var"
            fi
            ;;

        "sum")
            log_debug "Summing numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        # Fallback to integer arithmetic if bc not available
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            set_workflow_var "$output_var" "$total"
            log_success "Summed $valid_count numeric values, result: $total"
            ;;

        "avg")
            log_debug "Calculating average of numeric values from ${#input_vars[@]} variables"
            local total=0
            local valid_count=0
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "0")"
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)?$ ]]; then
                    if command -v bc >/dev/null 2>&1; then
                        total=$(echo "$total + $value" | bc -l)
                    else
                        total=$((total + ${value%.*}))
                    fi
                    ((valid_count++))
                else
                    log_warning "Skipping non-numeric value in $var_name: $value"
                fi
            done
            
            if [[ $valid_count -gt 0 ]]; then
                local average
                if command -v bc >/dev/null 2>&1; then
                    average=$(echo "scale=6; $total / $valid_count" | bc -l)
                else
                    average=$((total / valid_count))
                fi
                set_workflow_var "$output_var" "$average"
                log_success "Calculated average of $valid_count values: $average"
            else
                log_warning "No valid numeric values to average"
                set_workflow_var "$output_var" "0"
            fi
            ;;

        "collect")
            log_debug "Collecting values into JSON array from ${#input_vars[@]} variables"
            local -a collected=()
            
            for var_name in "${input_vars[@]}"; do
                local value="$(get_workflow_var "$var_name" "")"
                [[ -n "$value" ]] && collected+=("$value")
            done
            
            # Store as JSON array for structured access
            if command -v jq >/dev/null 2>&1; then
                local json_array
                json_array=$(printf '%s
' "${collected[@]}" | jq -R . | jq -s .)
                set_workflow_var "$output_var" "$json_array"
                log_success "Collected ${#collected[@]} values into JSON array"
            else
                # Fallback: create simple array format
                local array_string="["
                local first=true
                for value in "${collected[@]}"; do
                    if [[ "$first" == "true" ]]; then
                        first=false
                    else
                        array_string+=", "
                    fi
                    array_string+="\"$value\""
                done
                array_string+="]"
                set_workflow_var "$output_var" "$array_string"
                log_success "Collected ${#collected[@]} values into array (jq not available, using fallback format)"
            fi
            ;;

        "merge")
            log_debug "Merging JSON objects from ${#input_vars[@]} variables"
            local merged_json="{}"
            local merge_count=0
            
            if command -v jq >/dev/null 2>&1; then
                for var_name in "${input_vars[@]}"; do
                    local value="$(get_workflow_var "$var_name" "{}")"
                    # Validate that value is valid JSON
                    if echo "$value" | jq -e . >/dev/null 2>&1; then
                        merged_json=$(jq -s '.[0] * .[1]' <<< "$merged_json $value" 2>/dev/null)
                        if [[ $? -eq 0 ]]; then
                            ((merge_count++))
                        else
                            log_warning "Failed to merge JSON from $var_name"
                        fi
                    else
                        log_warning "Invalid JSON in variable $var_name, skipping"
                    fi
                done
                
                set_workflow_var "$output_var" "$merged_json"
                log_success "Merged $merge_count JSON objects"
            else
                log_error "jq is required for merge operation but not available"
                set_workflow_var "$output_var" "{}"
                return 1
            fi
            ;;

        *)
            log_error "Unknown aggregation method: $method"
            return 1
            ;;
    esac

    log_success "Variable aggregation completed: ${#input_vars[@]} inputs -> $output_var"
}

# Node: generate_summary
TEMPLATE_SUMMARY=""

# Node: final_results
echo "# 📝 Template Transform Node Example Results

## Configuration Summary
- **User:** ${user_name}
- **Project:** ${project_name}
- **Template Type:** ${template_type}
- **Priority Level:** ${urgency_level}
- **Include Details:** ${include_details}
- **Generated:** ${current_timestamp}

## Template Transformation Results

${all_template_outputs}

## Operations Summary
${template_summary}

## Template Transform Node Features Demonstrated

### Core Capabilities
- **Dynamic Content Generation**: Templates with variable substitution
- **Conditional Logic**: Template sections based on boolean conditions
- **Parameter Mapping**: Flexible parameter binding and transformation
- **Multiple Output Formats**: Email, reports, configuration, documentation
- **Expression Evaluation**: Runtime calculation of template values

### Template Sources
- **Inline Templates**: Templates defined directly in the workflow
- **File Templates**: Templates loaded from external files
- **Library Templates**: Reusable templates from template libraries
- **Custom Templates**: User-defined template structures

### Parameter Features
- **Static Values**: Direct string/number parameter binding
- **Variable References**: Dynamic values from workflow variables
- **Expression Parameters**: Computed values using shell expressions
- **Conditional Parameters**: Values based on boolean logic
- **Nested Parameters**: Complex object and array parameter structures

### Template Syntax
- **Variable Substitution**: `${VARIABLE_NAME}` syntax
- **Conditional Blocks**: `{{#condition}}...{{/condition}}` syntax
- **Expression Evaluation**: Runtime computation of template values
- **Escaping**: Proper handling of special characters
- **Formatting**: Structured output with proper indentation

### Advanced Features
- **Template Inheritance**: Building on base template structures
- **Partial Templates**: Reusable template components
- **Custom Helpers**: Extended template functionality
- **Output Variables**: Storing generated content in workflow variables
- **Error Handling**: Robust template processing with fallbacks

### Use Cases
- **Email Generation**: Personalized communication templates
- **Report Creation**: Automated report generation with dynamic data
- **Configuration Management**: Dynamic config file generation
- **Documentation**: Auto-generated project documentation
- **Code Generation**: Template-driven code and script generation
- **Notification Systems**: Dynamic alert and notification content

### Integration Patterns
- **Multi-Template Workflows**: Processing multiple templates in sequence
- **Template Chaining**: Using output from one template as input to another
- **Conditional Templates**: Different templates based on workflow conditions
- **Template Libraries**: Reusable template collections
- **Dynamic Template Selection**: Runtime template choice based on parameters

This example demonstrates the full power of template transform nodes for dynamic content generation, enabling flexible, maintainable, and scalable template-driven workflows.
"

echo "Workflow completed successfully"
exit 0
