#!/bin/bash
set -euo pipefail

# variable-assignment-node-example - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: variable-assignment-node-example"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# Environment Variables
BASE_VALUE=${BASE_VALUE:-""}
NUMBER_INPUT=${NUMBER_INPUT:-""}
USER_NAME=${USER_NAME:-""}
WELCOME_MESSAGE=${WELCOME_MESSAGE:-""}
MAX_ATTEMPTS=${MAX_ATTEMPTS:-""}
DEBUG_ENABLED=${DEBUG_ENABLED:-""}
ORIGINAL_INPUT=${ORIGINAL_INPUT:-""}
CALCULATION_BASE=${CALCULATION_BASE:-""}
PERSONALIZED_GREETING=${PERSONALIZED_GREETING:-""}
CALCULATED_RESULT=${CALCULATED_RESULT:-""}
CURRENT_TIMESTAMP=${CURRENT_TIMESTAMP:-""}
SYSTEM_INFO=${SYSTEM_INFO:-""}
STATUS_MESSAGE=${STATUS_MESSAGE:-""}
ACTIVITY_LOG=${ACTIVITY_LOG:-""}
PROCESSED_TEXT=${PROCESSED_TEXT:-""}
JSON_DATA=${JSON_DATA:-""}
ENV_SUMMARY=${ENV_SUMMARY:-""}
TEMP_DATA=${TEMP_DATA:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: assign_constant_string
WELCOME_MESSAGE="Welcome to the flowsh variable assignment demonstration!"

# Node: assign_constant_number
MAX_ATTEMPTS="3"

# Node: assign_constant_boolean
DEBUG_ENABLED="true"

# Node: copy_variable
ORIGINAL_INPUT=""

# Node: copy_number_variable
CALCULATION_BASE=""

# Node: string_concatenation
PERSONALIZED_GREETING=""

# Node: mathematical_calculation
CALCULATED_RESULT=""

# Node: date_timestamp
CURRENT_TIMESTAMP=""

# Node: file_operation
SYSTEM_INFO=""

# Node: conditional_expression
STATUS_MESSAGE=""

# Node: initialize_log
ACTIVITY_LOG="Log initialized"

# Node: append_to_log_1
ACTIVITY_LOG=""

# Node: append_to_log_2
ACTIVITY_LOG=""

# Node: append_calculation
ACTIVITY_LOG=""

# Node: complex_string_manipulation
PROCESSED_TEXT=""

# Node: json_creation
JSON_DATA=""

# Node: environment_info
ENV_SUMMARY=""

# Node: create_temp_variable
TEMP_DATA="This is temporary data that will be cleared"

# Node: clear_temp_variable
TEMP_DATA=""

# Node: final_summary
echo "# 📝 Variable Assignment Node Example Results

## Original Inputs
- **Base Value**: ${base_value}
- **Number Input**: ${number_input}
- **User Name**: ${user_name}

## Constant Assignments
- **Welcome Message**: ${welcome_message}
- **Max Attempts**: ${max_attempts}
- **Debug Enabled**: ${debug_enabled}

## Variable Copying
- **Original Input Copy**: ${original_input}
- **Calculation Base**: ${calculation_base}

## Expression Results
- **Personalized Greeting**: ${personalized_greeting}
- **Mathematical Result**: ${calculated_result}
- **Current Timestamp**: ${current_timestamp}
- **System Information**: ${system_info}
- **Status Message**: ${status_message}

## Advanced Operations
- **Processed Text**: ${processed_text}
- **JSON Data**: ${json_data}
- **Environment Summary**: ${env_summary}

## Write Mode Operations
- **Activity Log**: ${activity_log}
- **Temp Data (after clear)**: "${temp_data}" (should be empty)

## Variable Assignment Features Demonstrated

### Assignment Types
- **Constant**: Direct value assignment (strings, numbers, booleans)
- **Variable**: Copying values between variables
- **Expression**: Dynamic value generation using shell commands

### Write Modes
- **Over-write**: Replace existing value (default behavior)
- **Append**: Add to existing value (useful for logs and accumulation)
- **Clear**: Empty the variable (cleanup operations)

### Expression Capabilities
- **String Concatenation**: Combining multiple variables
- **Mathematical Operations**: Arithmetic calculations
- **System Commands**: Executing shell commands for dynamic values
- **Conditional Logic**: If/else operations in expressions
- **Text Processing**: Advanced string manipulation (sed, tr, awk)
- **JSON Generation**: Creating structured data
- **Environment Access**: Reading system information

### Use Cases
- **Data Transformation**: Converting and processing input values
- **Configuration Management**: Setting up workflow parameters
- **Logging and Tracking**: Building activity logs and audit trails
- **Calculations**: Mathematical operations and computations
- **System Integration**: Gathering environment and system information
- **Dynamic Content**: Creating personalized and contextual outputs

This example demonstrates the full range of variable assignment capabilities, from simple value setting to complex dynamic expression evaluation.
"

echo "Workflow completed successfully"
exit 0
