/**
 * Advanced Theme Configurations for React Flow Visualization
 *
 * This module provides specialized themes for different use cases:
 * - High contrast themes for accessibility
 * - Professional themes for presentations
 * - Developer themes optimized for code workflows
 * - Colorblind-friendly themes
 */

import { ThemeConfig } from './types.js';

// =============================================================================
// High Contrast Theme (Accessibility)
// =============================================================================

const highContrastTheme: ThemeConfig = {
  name: 'high-contrast',
  colors: {
    primary: '#000000',
    secondary: '#404040',
    success: '#006600',
    warning: '#cc6600',
    error: '#cc0000',
    info: '#0066cc',
    background: '#ffffff',
    text: '#000000',
    border: '#000000',
  },
  nodeStyles: {
    start: {
      backgroundColor: '#ffffff',
      borderColor: '#000000',
      borderWidth: 3,
      borderRadius: 4,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000000',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    end: {
      backgroundColor: '#000000',
      borderColor: '#000000',
      borderWidth: 3,
      borderRadius: 4,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#ffffff',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    'if-else': {
      backgroundColor: '#ffffff',
      borderColor: '#000000',
      borderWidth: 4,
      borderRadius: 8,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000000',
      minWidth: 160,
      minHeight: 60,
      padding: '14px',
      textAlign: 'center',
    },
    llm: {
      backgroundColor: '#e6f3ff',
      borderColor: '#000000',
      borderWidth: 3,
      borderRadius: 4,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000000',
      minWidth: 170,
      minHeight: 60,
      padding: '14px',
      textAlign: 'center',
    },
    agent: {
      backgroundColor: '#f0e6ff',
      borderColor: '#000000',
      borderWidth: 3,
      borderRadius: 4,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000000',
      minWidth: 160,
      minHeight: 60,
      padding: '14px',
      textAlign: 'center',
    },
    code: {
      backgroundColor: '#f0f0f0',
      borderColor: '#000000',
      borderWidth: 3,
      borderRadius: 2,
      fontSize: 15,
      fontWeight: 'bold',
      color: '#000000',
      minWidth: 150,
      minHeight: 55,
      padding: '12px',
      textAlign: 'center',
    },
    default: {
      backgroundColor: '#ffffff',
      borderColor: '#000000',
      borderWidth: 3,
      borderRadius: 4,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000000',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
  },
  edgeStyles: {
    default: {
      stroke: '#000000',
      strokeWidth: 3,
      fill: 'none',
    },
    conditional: {
      stroke: '#000000',
      strokeWidth: 4,
      strokeDasharray: '10,5',
      fill: 'none',
    },
    error: {
      stroke: '#cc0000',
      strokeWidth: 4,
      fill: 'none',
    },
    success: {
      stroke: '#006600',
      strokeWidth: 3,
      fill: 'none',
    },
    animated: {
      stroke: '#0066cc',
      strokeWidth: 3,
      fill: 'none',
    },
  },
  spacing: {
    xs: 6,
    sm: 12,
    md: 24,
    lg: 36,
    xl: 48,
  },
};

// =============================================================================
// Professional Theme (Presentations)
// =============================================================================

const professionalTheme: ThemeConfig = {
  name: 'professional',
  colors: {
    primary: '#2c3e50',
    secondary: '#95a5a6',
    success: '#27ae60',
    warning: '#f39c12',
    error: '#e74c3c',
    info: '#3498db',
    background: '#ecf0f1',
    text: '#2c3e50',
    border: '#bdc3c7',
  },
  nodeStyles: {
    start: {
      backgroundColor: '#2ecc71',
      borderColor: '#27ae60',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 130,
      minHeight: 45,
      padding: '12px',
      textAlign: 'center',
    },
    end: {
      backgroundColor: '#e74c3c',
      borderColor: '#c0392b',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 130,
      minHeight: 45,
      padding: '12px',
      textAlign: 'center',
    },
    'if-else': {
      backgroundColor: '#f39c12',
      borderColor: '#e67e22',
      borderWidth: 2,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 150,
      minHeight: 55,
      padding: '14px',
      textAlign: 'center',
    },
    llm: {
      backgroundColor: '#3498db',
      borderColor: '#2980b9',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 160,
      minHeight: 55,
      padding: '14px',
      textAlign: 'center',
    },
    agent: {
      backgroundColor: '#9b59b6',
      borderColor: '#8e44ad',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 150,
      minHeight: 55,
      padding: '14px',
      textAlign: 'center',
    },
    code: {
      backgroundColor: '#34495e',
      borderColor: '#2c3e50',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    'variable-assignment': {
      backgroundColor: '#16a085',
      borderColor: '#1abc9c',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 170,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    answer: {
      backgroundColor: '#2c3e50',
      borderColor: '#34495e',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#ffffff',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    default: {
      backgroundColor: '#95a5a6',
      borderColor: '#7f8c8d',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '500',
      color: '#ffffff',
      minWidth: 130,
      minHeight: 45,
      padding: '12px',
      textAlign: 'center',
    },
  },
  edgeStyles: {
    default: {
      stroke: '#7f8c8d',
      strokeWidth: 2,
      fill: 'none',
    },
    conditional: {
      stroke: '#f39c12',
      strokeWidth: 2,
      strokeDasharray: '8,4',
      fill: 'none',
    },
    error: {
      stroke: '#e74c3c',
      strokeWidth: 2,
      fill: 'none',
    },
    success: {
      stroke: '#27ae60',
      strokeWidth: 2,
      fill: 'none',
    },
    animated: {
      stroke: '#3498db',
      strokeWidth: 2,
      fill: 'none',
    },
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 18,
    lg: 28,
    xl: 36,
  },
};

// =============================================================================
// Developer Theme (Code-focused)
// =============================================================================

const developerTheme: ThemeConfig = {
  name: 'developer',
  colors: {
    primary: '#61dafb',
    secondary: '#888888',
    success: '#98d982',
    warning: '#ffcc02',
    error: '#f14c4c',
    info: '#61dafb',
    background: '#282c34',
    text: '#abb2bf',
    border: '#4b5263',
  },
  nodeStyles: {
    start: {
      backgroundColor: '#21252b',
      borderColor: '#98d982',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '500',
      color: '#98d982',
      minWidth: 120,
      minHeight: 40,
      padding: '10px',
      textAlign: 'center',
    },
    end: {
      backgroundColor: '#21252b',
      borderColor: '#f14c4c',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '500',
      color: '#f14c4c',
      minWidth: 120,
      minHeight: 40,
      padding: '10px',
      textAlign: 'center',
    },
    'if-else': {
      backgroundColor: '#21252b',
      borderColor: '#ffcc02',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 13,
      fontWeight: '500',
      color: '#ffcc02',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    llm: {
      backgroundColor: '#21252b',
      borderColor: '#61dafb',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '500',
      color: '#61dafb',
      minWidth: 150,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    agent: {
      backgroundColor: '#21252b',
      borderColor: '#c678dd',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '500',
      color: '#c678dd',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    code: {
      backgroundColor: '#1e2127',
      borderColor: '#56b6c2',
      borderWidth: 2,
      borderRadius: 3,
      fontSize: 12,
      fontWeight: '500',
      color: '#56b6c2',
      minWidth: 130,
      minHeight: 45,
      padding: '10px',
      textAlign: 'center',
    },
    'variable-assignment': {
      backgroundColor: '#21252b',
      borderColor: '#e06c75',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '500',
      color: '#e06c75',
      minWidth: 160,
      minHeight: 45,
      padding: '10px',
      textAlign: 'center',
    },
    answer: {
      backgroundColor: '#21252b',
      borderColor: '#d19a66',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '500',
      color: '#d19a66',
      minWidth: 130,
      minHeight: 45,
      padding: '10px',
      textAlign: 'center',
    },
    default: {
      backgroundColor: '#21252b',
      borderColor: '#4b5263',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '400',
      color: '#abb2bf',
      minWidth: 120,
      minHeight: 40,
      padding: '10px',
      textAlign: 'center',
    },
  },
  edgeStyles: {
    default: {
      stroke: '#4b5263',
      strokeWidth: 1.5,
      fill: 'none',
    },
    conditional: {
      stroke: '#ffcc02',
      strokeWidth: 1.5,
      strokeDasharray: '6,3',
      fill: 'none',
    },
    error: {
      stroke: '#f14c4c',
      strokeWidth: 1.5,
      fill: 'none',
    },
    success: {
      stroke: '#98d982',
      strokeWidth: 1.5,
      fill: 'none',
    },
    animated: {
      stroke: '#61dafb',
      strokeWidth: 1.5,
      fill: 'none',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};

// =============================================================================
// Colorblind-Friendly Theme
// =============================================================================

const colorblindFriendlyTheme: ThemeConfig = {
  name: 'colorblind-friendly',
  colors: {
    primary: '#0173b2',
    secondary: '#666666',
    success: '#029e73',
    warning: '#cc78bc',
    error: '#ca9161',
    info: '#0173b2',
    background: '#ffffff',
    text: '#333333',
    border: '#999999',
  },
  nodeStyles: {
    start: {
      backgroundColor: '#e8f4f8',
      borderColor: '#029e73',
      borderWidth: 3,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#025951',
      minWidth: 130,
      minHeight: 45,
      padding: '12px',
      textAlign: 'center',
    },
    end: {
      backgroundColor: '#f4f1e8',
      borderColor: '#ca9161',
      borderWidth: 3,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#8b6f42',
      minWidth: 130,
      minHeight: 45,
      padding: '12px',
      textAlign: 'center',
    },
    'if-else': {
      backgroundColor: '#f8f4f8',
      borderColor: '#cc78bc',
      borderWidth: 3,
      borderRadius: 12,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#8b4d7b',
      minWidth: 150,
      minHeight: 55,
      padding: '14px',
      textAlign: 'center',
    },
    llm: {
      backgroundColor: '#e8f1f8',
      borderColor: '#0173b2',
      borderWidth: 3,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#014a7a',
      minWidth: 160,
      minHeight: 55,
      padding: '14px',
      textAlign: 'center',
    },
    agent: {
      backgroundColor: '#f8f1e8',
      borderColor: '#cc78bc',
      borderWidth: 3,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#8b4d7b',
      minWidth: 150,
      minHeight: 55,
      padding: '14px',
      textAlign: 'center',
    },
    code: {
      backgroundColor: '#f0f0f0',
      borderColor: '#666666',
      borderWidth: 3,
      borderRadius: 6,
      fontSize: 13,
      fontWeight: '600',
      color: '#333333',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    'variable-assignment': {
      backgroundColor: '#e8f4f8',
      borderColor: '#029e73',
      borderWidth: 3,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#025951',
      minWidth: 170,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    answer: {
      backgroundColor: '#e8f1f8',
      borderColor: '#0173b2',
      borderWidth: 3,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 'bold',
      color: '#014a7a',
      minWidth: 140,
      minHeight: 50,
      padding: '12px',
      textAlign: 'center',
    },
    default: {
      backgroundColor: '#f5f5f5',
      borderColor: '#999999',
      borderWidth: 2,
      borderRadius: 8,
      fontSize: 14,
      fontWeight: '500',
      color: '#333333',
      minWidth: 130,
      minHeight: 45,
      padding: '12px',
      textAlign: 'center',
    },
  },
  edgeStyles: {
    default: {
      stroke: '#999999',
      strokeWidth: 2,
      fill: 'none',
    },
    conditional: {
      stroke: '#cc78bc',
      strokeWidth: 3,
      strokeDasharray: '10,5',
      fill: 'none',
    },
    error: {
      stroke: '#ca9161',
      strokeWidth: 3,
      fill: 'none',
    },
    success: {
      stroke: '#029e73',
      strokeWidth: 2,
      fill: 'none',
    },
    animated: {
      stroke: '#0173b2',
      strokeWidth: 2,
      fill: 'none',
    },
  },
  spacing: {
    xs: 5,
    sm: 10,
    md: 18,
    lg: 26,
    xl: 34,
  },
};

// =============================================================================
// Solarized Theme (Developer Favorite)
// =============================================================================

const solarizedTheme: ThemeConfig = {
  name: 'solarized',
  colors: {
    primary: '#268bd2',
    secondary: '#657b83',
    success: '#859900',
    warning: '#b58900',
    error: '#dc322f',
    info: '#2aa198',
    background: '#fdf6e3',
    text: '#657b83',
    border: '#93a1a1',
  },
  nodeStyles: {
    start: {
      backgroundColor: '#eee8d5',
      borderColor: '#859900',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#859900',
      minWidth: 125,
      minHeight: 42,
      padding: '11px',
      textAlign: 'center',
    },
    end: {
      backgroundColor: '#eee8d5',
      borderColor: '#dc322f',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#dc322f',
      minWidth: 125,
      minHeight: 42,
      padding: '11px',
      textAlign: 'center',
    },
    'if-else': {
      backgroundColor: '#eee8d5',
      borderColor: '#b58900',
      borderWidth: 2,
      borderRadius: 10,
      fontSize: 14,
      fontWeight: '600',
      color: '#b58900',
      minWidth: 145,
      minHeight: 52,
      padding: '13px',
      textAlign: 'center',
    },
    llm: {
      backgroundColor: '#eee8d5',
      borderColor: '#268bd2',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#268bd2',
      minWidth: 155,
      minHeight: 52,
      padding: '13px',
      textAlign: 'center',
    },
    agent: {
      backgroundColor: '#eee8d5',
      borderColor: '#6c71c4',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#6c71c4',
      minWidth: 145,
      minHeight: 52,
      padding: '13px',
      textAlign: 'center',
    },
    code: {
      backgroundColor: '#eee8d5',
      borderColor: '#2aa198',
      borderWidth: 2,
      borderRadius: 4,
      fontSize: 13,
      fontWeight: '600',
      color: '#2aa198',
      minWidth: 135,
      minHeight: 47,
      padding: '11px',
      textAlign: 'center',
    },
    'variable-assignment': {
      backgroundColor: '#eee8d5',
      borderColor: '#d33682',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#d33682',
      minWidth: 165,
      minHeight: 47,
      padding: '11px',
      textAlign: 'center',
    },
    answer: {
      backgroundColor: '#eee8d5',
      borderColor: '#657b83',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '600',
      color: '#657b83',
      minWidth: 135,
      minHeight: 47,
      padding: '11px',
      textAlign: 'center',
    },
    default: {
      backgroundColor: '#eee8d5',
      borderColor: '#93a1a1',
      borderWidth: 2,
      borderRadius: 6,
      fontSize: 14,
      fontWeight: '500',
      color: '#657b83',
      minWidth: 125,
      minHeight: 42,
      padding: '11px',
      textAlign: 'center',
    },
  },
  edgeStyles: {
    default: {
      stroke: '#93a1a1',
      strokeWidth: 1.5,
      fill: 'none',
    },
    conditional: {
      stroke: '#b58900',
      strokeWidth: 1.5,
      strokeDasharray: '7,3',
      fill: 'none',
    },
    error: {
      stroke: '#dc322f',
      strokeWidth: 1.5,
      fill: 'none',
    },
    success: {
      stroke: '#859900',
      strokeWidth: 1.5,
      fill: 'none',
    },
    animated: {
      stroke: '#268bd2',
      strokeWidth: 1.5,
      fill: 'none',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 15,
    lg: 22,
    xl: 30,
  },
};

// =============================================================================
// Theme Registry Export
// =============================================================================

export const advancedThemes: Record<string, ThemeConfig> = {
  'high-contrast': highContrastTheme,
  professional: professionalTheme,
  developer: developerTheme,
  'colorblind-friendly': colorblindFriendlyTheme,
  solarized: solarizedTheme,
};

export {
  highContrastTheme,
  professionalTheme,
  developerTheme,
  colorblindFriendlyTheme,
  solarizedTheme,
};
