#!/bin/bash
set -euo pipefail

# Counting Loop Test - Generated by flowsh
# Registry-based workflow execution script

echo "Starting workflow: Counting Loop Test"

# Workflow variables and state management
declare -A workflow_vars
declare -A workflow_state

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
VERBOSE=${VERBOSE:-false}
AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}

# Environment Variables
COUNTER=${COUNTER:-""}
LOOP_INDEX=${LOOP_INDEX:-""}
LOOP_ITERATION=${LOOP_ITERATION:-""}
LOOP_FINAL_COUNT=${LOOP_FINAL_COUNT:-""}
LOOP_COMPLETED=${LOOP_COMPLETED:-""}

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

# Logging functions with colors
log_info() {
    echo -e "${CYAN}ℹ️  $*${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $*${NC}"
}

log_error() {
    echo -e "${RED}❌ $*${NC}" >&2
}

log_warning() {
    echo -e "${YELLOW}⚠️  $*${NC}" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${BLUE}🔍 DEBUG: $*${NC}" >&2 || true
}

log_step() {
    echo -e "${CYAN}🚀 $*${NC}"
}

# Operation logging with correlation IDs
log_operation_start() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    log_debug "$correlation_id" "Starting $operation_type: $operation_name"
}

log_operation_end() {
    local operation_name="$1"
    local operation_type="$2"
    local correlation_id="$3"
    local status="${4:-success}"
    log_debug "$correlation_id" "Completed $operation_type: $operation_name ($status)"
}

# Enhanced error handling
handle_error() {
    local exit_code=$1
    local context="$2"
    local node_id="${3:-unknown}"
    
    case $exit_code in
        124)
            log_error "Timeout: $context took longer than ${AGENT_TIMEOUT}s (node: $node_id)"
            ;;
        127)
            log_error "Command not found in: $context (node: $node_id)"
            ;;
        1)
            log_error "General error in: $context (node: $node_id)"
            ;;
        *)
            log_error "Unknown error (exit code $exit_code) in: $context (node: $node_id)"
            ;;
    esac
    
    return $exit_code
}

# Variable management
set_workflow_var() {
    local var_name="$1"
    local var_value="$2"
    workflow_vars["$var_name"]="$var_value"
    log_debug "Set variable: $var_name = $var_value"
}

get_workflow_var() {
    local var_name="$1"
    local default_value="${2:-}"
    echo "${workflow_vars[$var_name]:-$default_value}"
}

# State management
set_workflow_state() {
    local state_key="$1"
    local state_value="$2"
    workflow_state["$state_key"]="$state_value"
    log_debug "Set state: $state_key = $state_value"
}

get_workflow_state() {
    local state_key="$1"
    local default_value="${2:-}"
    echo "${workflow_state[$state_key]:-$default_value}"
}

# Variable substitution in templates
substitute_variables() {
    local template="$1"
    local result="$template"
    
    # Find all variable references in the format {{#variable_name#}}
    while [[ $result =~ \{\{#([^#]+)#\}\} ]]; do
        local var_ref="${BASH_REMATCH[1]}"
        local var_value=$(get_workflow_var "$var_ref" "")
        
        if [[ -z "$var_value" ]]; then
            log_warning "Variable reference '$var_ref' not found, using empty string"
        fi
        
        # Escape special characters for sed
        local escaped_value=$(printf '%s\n' "$var_value" | sed 's/[[\.\*^\$()+?{|]/\\&/g')
        result=$(echo "$result" | sed "s|{{#${var_ref}#}}|$escaped_value|g")
    done
    
    echo "$result"
}

# Workflow Execution

# Node: setup_message
echo

# Node: counting_loop

# Node: counting_loop (Counting Loop)
execute_loop_counting_loop() {
    log_step "🔄 Starting Loop: Counting Loop"
    
    # Loop configuration
    local loop_counter=0
    local max_iterations=10
    local continue_loop=true
    local break_on="condition"
    
    # Loop execution with safety checks
    while [[ "$continue_loop" == "true" && $loop_counter -lt $max_iterations ]]; do
        log_debug "Loop iteration $loop_counter (max: $max_iterations)"
        
        # Set loop context variables for child nodes
        set_workflow_var "loop_index" "$loop_counter"
        set_workflow_var "loop_iteration" "$((loop_counter + 1))"
        
        # Evaluate loop condition
        local condition_result
        condition_result="false"  # Unsupported operator: undefined
        
        # Check if we should continue based on condition and break_on setting
        if [[ "$break_on" == "condition" ]]; then
            if [[ "$condition_result" != "true" ]]; then
                log_info "Loop exit condition met at iteration $loop_counter"
                break
            fi
        fi
        
        # Execute loop body (child nodes would be called here by the main executor)
        log_debug "Executing loop body for iteration $loop_counter"
        
        # This is where child nodes would be executed
        # The main executor will handle the edge routing to child nodes
        
        # Increment counter for next iteration
        ((loop_counter++))
        
        # Safety check for max iterations
        if [[ $loop_counter -ge $max_iterations ]]; then
            log_warning "Loop reached max iterations ($max_iterations), stopping"
            break
        fi
    done
    
    # Set final loop variables
    set_workflow_var "loop_final_count" "$loop_counter"
    set_workflow_var "loop_completed" "true"
    
    log_success "Loop completed after $loop_counter iterations"
}

# Node: increment_counter
COUNTER="$((counter + 1))"

# Node: display_count
echo

# Node: completion_message
echo

echo "Workflow completed successfully"
exit 0
