/**
 * Resource Management Utilities for Phase 2C
 *
 * Provides comprehensive resource monitoring, memory management,
 * and process lifecycle utilities for parallel workflow execution.
 *
 * Features:
 * - Memory usage monitoring and limits
 * - Process lifecycle management
 * - Temporary file cleanup automation
 * - Resource leak detection
 * - Performance tracking integration
 */

export interface ResourceLimits {
  maxMemoryMB?: number; // Maximum memory usage in MB
  maxProcesses?: number; // Maximum concurrent processes
  maxTempFiles?: number; // Maximum temporary files
  maxExecutionTimeMs?: number; // Maximum execution time in milliseconds
}

export interface ResourceUsage {
  memoryUsageMB: number;
  activeProcesses: number;
  tempFileCount: number;
  executionTimeMs: number;
  timestamp: number;
}

export interface ProcessInfo {
  pid: number;
  startTime: number;
  command: string;
  memoryMB?: number;
  status: 'running' | 'completed' | 'failed' | 'terminated';
}

/**
 * Resource Manager for monitoring and controlling workflow resource usage
 */
export class ResourceManager {
  private limits: ResourceLimits;
  private activeProcesses = new Map<number, ProcessInfo>();
  private tempFiles = new Set<string>();
  private cleanupHandlers = new Set<() => void>();
  private startTime: number;
  private resourceCheckInterval?: NodeJS.Timeout | undefined;
  private eventListeners = new Map<string, (...args: any[]) => void>();
  private isCleanedUp = false;

  constructor(limits: ResourceLimits = {}) {
    this.limits = {
      maxMemoryMB: limits.maxMemoryMB || 1000, // 1GB default
      maxProcesses: limits.maxProcesses || 50, // 50 processes default
      maxTempFiles: limits.maxTempFiles || 100, // 100 files default
      maxExecutionTimeMs: limits.maxExecutionTimeMs || 300000, // 5 minutes default
    };

    this.startTime = Date.now();
    this.setupCleanupHandlers();
  }

  /**
   * Generate shell code for resource monitoring functions
   */
  generateResourceMonitoringCode(): string {
    return `
# =============================================================================
# Resource Management Functions (Generated by ResourceManager)
# =============================================================================

# Global resource tracking variables
declare -g FLOWSH_ACTIVE_PIDS=()
declare -g FLOWSH_TEMP_FILES=()
declare -g FLOWSH_START_TIME=$(date +%s)
declare -g FLOWSH_MAX_MEMORY_MB=${this.limits.maxMemoryMB}
declare -g FLOWSH_MAX_PROCESSES=${this.limits.maxProcesses}
declare -g FLOWSH_MAX_EXECUTION_TIME_SEC=${Math.floor(this.limits.maxExecutionTimeMs! / 1000)}

# Check if system commands are available
check_system_commands() {
    local missing_commands=()
    
    if ! command -v ps >/dev/null 2>&1; then
        missing_commands+=("ps")
    fi
    
    if ! command -v free >/dev/null 2>&1 && ! command -v vm_stat >/dev/null 2>&1; then
        missing_commands+=("memory monitoring (free/vm_stat)")
    fi
    
    if [[ \${#missing_commands[@]} -gt 0 ]]; then
        log_warning "Missing system commands: \${missing_commands[*]}"
        log_warning "Resource monitoring will be limited"
        return 1
    fi
    
    return 0
}

# Get current memory usage in MB
get_memory_usage() {
    local memory_mb=0
    
    if command -v free >/dev/null 2>&1; then
        # Linux systems
        memory_mb=$(free -m | awk 'NR==2{printf "%d", $3}')
    elif command -v vm_stat >/dev/null 2>&1; then
        # macOS systems
        local pages_used=$(vm_stat | grep "Pages active\\|Pages inactive\\|Pages speculative\\|Pages wired down" | awk '{print $3}' | sed 's/\\.//' | paste -sd+ | bc)
        local page_size=$(vm_stat | grep "page size" | awk '{print $8}')
        memory_mb=$(( (pages_used * page_size) / 1024 / 1024 ))
    else
        log_debug "Memory monitoring not available on this system"
        return 0
    fi
    
    echo "\$memory_mb"
}

# Get process count for current user
get_process_count() {
    if command -v ps >/dev/null 2>&1; then
        ps -u "\$(whoami)" --no-headers | wc -l
    else
        echo "0"
    fi
}

# Check if resource limits are exceeded
check_resource_limits() {
    local current_memory=$(get_memory_usage)
    local current_processes=$(get_process_count)
    local current_time=$(date +%s)
    local execution_time=$((current_time - FLOWSH_START_TIME))
    
    # Check memory limit
    if [[ \$current_memory -gt \$FLOWSH_MAX_MEMORY_MB ]]; then
        log_error "Memory limit exceeded: \${current_memory}MB > \${FLOWSH_MAX_MEMORY_MB}MB"
        return 1
    fi
    
    # Check process limit
    if [[ \$current_processes -gt \$FLOWSH_MAX_PROCESSES ]]; then
        log_error "Process limit exceeded: \${current_processes} > \${FLOWSH_MAX_PROCESSES}"
        return 1
    fi
    
    # Check execution time limit
    if [[ \$execution_time -gt \$FLOWSH_MAX_EXECUTION_TIME_SEC ]]; then
        log_error "Execution time limit exceeded: \${execution_time}s > \${FLOWSH_MAX_EXECUTION_TIME_SEC}s"
        return 1
    fi
    
    return 0
}

# Register a process for tracking
register_process() {
    local pid="\$1"
    local description="\${2:-unknown}"
    
    if [[ -n "\$pid" && "\$pid" =~ ^[0-9]+$ ]]; then
        FLOWSH_ACTIVE_PIDS+=("\$pid")
        log_debug "Registered process \$pid: \$description"
        
        # Check limits after registering
        if ! check_resource_limits; then
            log_warning "Resource limits exceeded after registering process \$pid"
        fi
    else
        log_warning "Invalid PID for registration: \$pid"
    fi
}

# Unregister a process from tracking
unregister_process() {
    local pid="\$1"
    local new_pids=()
    
    for active_pid in "\${FLOWSH_ACTIVE_PIDS[@]}"; do
        if [[ "\$active_pid" != "\$pid" ]]; then
            new_pids+=("\$active_pid")
        fi
    done
    
    FLOWSH_ACTIVE_PIDS=("\${new_pids[@]}")
    log_debug "Unregistered process \$pid"
}

# Register a temporary file for cleanup
register_temp_file() {
    local file_path="\$1"
    
    if [[ -n "\$file_path" ]]; then
        FLOWSH_TEMP_FILES+=("\$file_path")
        log_debug "Registered temp file: \$file_path"
        
        # Check temp file limit
        if [[ \${#FLOWSH_TEMP_FILES[@]} -gt ${this.limits.maxTempFiles} ]]; then
            log_warning "Temp file limit exceeded: \${#FLOWSH_TEMP_FILES[@]} > ${this.limits.maxTempFiles}"
        fi
    fi
}

# Create temporary directory with automatic registration
create_managed_temp_dir() {
    local prefix="\${1:-flowsh_temp}"
    local temp_dir=$(mktemp -d -t "\${prefix}_XXXXXX")
    
    if [[ -d "\$temp_dir" ]]; then
        register_temp_file "\$temp_dir"
        echo "\$temp_dir"
    else
        log_error "Failed to create temporary directory"
        return 1
    fi
}

# Clean up registered temporary files
cleanup_temp_files() {
    local cleaned_count=0
    local failed_count=0
    
    for temp_file in "\${FLOWSH_TEMP_FILES[@]}"; do
        if [[ -e "\$temp_file" ]]; then
            if rm -rf "\$temp_file" 2>/dev/null; then
                ((cleaned_count++))
                log_debug "Cleaned up temp file: \$temp_file"
            else
                ((failed_count++))
                log_warning "Failed to clean up temp file: \$temp_file"
            fi
        fi
    done
    
    # Clear the temp files array
    FLOWSH_TEMP_FILES=()
    
    if [[ \$cleaned_count -gt 0 ]]; then
        log_info "Cleaned up \$cleaned_count temporary files"
    fi
    
    if [[ \$failed_count -gt 0 ]]; then
        log_warning "Failed to clean up \$failed_count temporary files"
    fi
    
    return 0
}

# Kill and clean up active processes
cleanup_active_processes() {
    local terminated_count=0
    local failed_count=0
    
    for pid in "\${FLOWSH_ACTIVE_PIDS[@]}"; do
        if kill -0 "\$pid" 2>/dev/null; then
            # Process is still running, attempt to terminate
            if kill -TERM "\$pid" 2>/dev/null; then
                # Wait for graceful termination with timeout
                (sleep 1; kill -0 "\$pid" 2>/dev/null && kill -KILL "\$pid" 2>/dev/null || true) &
                wait
                
                # Force kill if still running
                if kill -0 "\$pid" 2>/dev/null; then
                    kill -KILL "\$pid" 2>/dev/null || true
                fi
                
                ((terminated_count++))
                log_debug "Terminated process \$pid"
            else
                ((failed_count++))
                log_warning "Failed to terminate process \$pid"
            fi
        else
            # Process already terminated
            log_debug "Process \$pid already terminated"
        fi
    done
    
    # Clear the active PIDs array
    FLOWSH_ACTIVE_PIDS=()
    
    if [[ \$terminated_count -gt 0 ]]; then
        log_info "Terminated \$terminated_count active processes"
    fi
    
    if [[ \$failed_count -gt 0 ]]; then
        log_warning "Failed to terminate \$failed_count processes"
    fi
    
    return 0
}

# Comprehensive cleanup function
cleanup_all_resources() {
    log_info "Starting comprehensive resource cleanup..."
    
    # Clean up processes first
    cleanup_active_processes
    
    # Then clean up temporary files
    cleanup_temp_files
    
    log_info "Resource cleanup completed"
}

# Get current resource usage summary
get_resource_usage() {
    local memory_mb=$(get_memory_usage)
    local process_count=$(get_process_count)
    local active_processes=\${#FLOWSH_ACTIVE_PIDS[@]}
    local temp_files=\${#FLOWSH_TEMP_FILES[@]}
    local execution_time=$(($(date +%s) - FLOWSH_START_TIME))
    
    cat << EOF
=== Resource Usage Summary ===
Memory Usage: \${memory_mb}MB / \${FLOWSH_MAX_MEMORY_MB}MB
Total Processes: \${process_count} / \${FLOWSH_MAX_PROCESSES}
Tracked Processes: \${active_processes}
Temporary Files: \${temp_files} / ${this.limits.maxTempFiles}
Execution Time: \${execution_time}s / \${FLOWSH_MAX_EXECUTION_TIME_SEC}s
===========================
EOF
}

# Setup cleanup trap handlers
setup_resource_cleanup_traps() {
    # Cleanup on script exit
    trap 'cleanup_all_resources; exit 0' EXIT
    
    # Cleanup on interruption
    trap 'log_warning "Workflow interrupted, cleaning up..."; cleanup_all_resources; exit 1' INT TERM
    
    # Periodic resource check (if supported)
    if command -v timeout >/dev/null 2>&1; then
        # Start background resource monitor
        monitor_resources_background &
        local monitor_pid=$!
        register_process "\$monitor_pid" "Resource Monitor"
    fi
}

# Background resource monitoring
monitor_resources_background() {
    while true; do
        sleep 30  # Check every 30 seconds
        
        if ! check_resource_limits; then
            log_error "Resource limits exceeded during background monitoring"
            log_info "Current resource usage:"
            get_resource_usage
            
            # Trigger cleanup and exit
            cleanup_all_resources
            exit 1
        fi
    done
}

# Enhanced parallel execution with resource management
execute_with_resource_management() {
    local command="\$1"
    local description="\${2:-parallel task}"
    local max_memory_mb="\${3:-100}"  # Per-process memory limit
    
    # Check global limits before starting
    if ! check_resource_limits; then
        log_error "Cannot start '\$description': resource limits exceeded"
        return 1
    fi
    
    # Execute command in background with resource monitoring
    (
        # Set process-specific limits if supported
        if command -v ulimit >/dev/null 2>&1; then
            # Limit memory (in KB)
            local memory_kb=$((max_memory_mb * 1024))
            ulimit -v "\$memory_kb" 2>/dev/null || true
            
            # Limit process execution time (in seconds)
            ulimit -t 300 2>/dev/null || true
        fi
        
        # Execute the actual command
        eval "\$command"
    ) &
    
    local bg_pid=$!
    register_process "\$bg_pid" "\$description"
    
    return 0
}

# Initialize resource management
init_resource_management() {
    log_info "Initializing resource management..."
    
    # Check system capabilities
    check_system_commands
    
    # Setup cleanup handlers
    setup_resource_cleanup_traps
    
    # Log initial resource usage
    log_info "Initial resource usage:"
    get_resource_usage
    
    log_success "Resource management initialized"
}

# Resource management initialization (called automatically)
init_resource_management`;
  }

  /**
   * Get current resource usage snapshot
   */
  getCurrentUsage(): ResourceUsage {
    const now = Date.now();
    return {
      memoryUsageMB: this.getMemoryUsage(),
      activeProcesses: this.activeProcesses.size,
      tempFileCount: this.tempFiles.size,
      executionTimeMs: now - this.startTime,
      timestamp: now,
    };
  }

  /**
   * Check if resource limits are exceeded
   */
  checkLimits(): { withinLimits: boolean; violations: string[] } {
    const usage = this.getCurrentUsage();
    const violations: string[] = [];

    if (usage.memoryUsageMB > (this.limits.maxMemoryMB || 1000)) {
      violations.push(`Memory: ${usage.memoryUsageMB}MB > ${this.limits.maxMemoryMB}MB`);
    }

    if (usage.activeProcesses > (this.limits.maxProcesses || 50)) {
      violations.push(`Processes: ${usage.activeProcesses} > ${this.limits.maxProcesses}`);
    }

    if (usage.tempFileCount > (this.limits.maxTempFiles || 100)) {
      violations.push(`Temp files: ${usage.tempFileCount} > ${this.limits.maxTempFiles}`);
    }

    if (usage.executionTimeMs > (this.limits.maxExecutionTimeMs || 300000)) {
      violations.push(
        `Execution time: ${usage.executionTimeMs}ms > ${this.limits.maxExecutionTimeMs}ms`
      );
    }

    return {
      withinLimits: violations.length === 0,
      violations,
    };
  }

  /**
   * Register a process for tracking
   */
  registerProcess(pid: number, command: string): void {
    const processInfo: ProcessInfo = {
      pid,
      startTime: Date.now(),
      command,
      status: 'running',
    };

    this.activeProcesses.set(pid, processInfo);
  }

  /**
   * Unregister a process from tracking
   */
  unregisterProcess(
    pid: number,
    status: 'completed' | 'failed' | 'terminated' = 'completed'
  ): void {
    const processInfo = this.activeProcesses.get(pid);
    if (processInfo) {
      processInfo.status = status;
      this.activeProcesses.delete(pid);
    }
  }

  /**
   * Register a temporary file for cleanup
   */
  registerTempFile(filePath: string): void {
    this.tempFiles.add(filePath);
  }

  /**
   * Unregister a temporary file (when manually cleaned up)
   */
  unregisterTempFile(filePath: string): void {
    this.tempFiles.delete(filePath);
  }

  /**
   * Add a cleanup handler to be called on shutdown
   */
  addCleanupHandler(handler: () => void): void {
    this.cleanupHandlers.add(handler);
  }

  /**
   * Perform comprehensive cleanup
   */
  async cleanup(): Promise<void> {
    if (this.isCleanedUp) {
      return; // Already cleaned up
    }
    this.isCleanedUp = true;

    // Stop resource monitoring
    if (this.resourceCheckInterval) {
      clearInterval(this.resourceCheckInterval);
      this.resourceCheckInterval = undefined;
    }

    // Remove event listeners
    for (const [event, listener] of this.eventListeners.entries()) {
      process.removeListener(event as any, listener);
    }
    this.eventListeners.clear();

    // Run custom cleanup handlers
    for (const handler of this.cleanupHandlers) {
      try {
        handler();
      } catch (error) {
        console.warn('Cleanup handler failed:', error);
      }
    }

    // Clean up tracked resources
    await this.cleanupProcesses();
    this.cleanupTempFiles();
  }

  /**
   * Get memory usage in MB (Node.js specific)
   */
  private getMemoryUsage(): number {
    const usage = process.memoryUsage();
    return Math.round((usage.heapUsed + usage.external) / 1024 / 1024);
  }

  /**
   * Setup automatic cleanup handlers
   */
  private setupCleanupHandlers(): void {
    // Create listeners and track them for cleanup
    const exitListener = () => {
      this.cleanup().catch(console.error);
    };

    const sigintListener = () => {
      console.log('\nReceived SIGINT, cleaning up resources...');
      this.cleanup()
        .then(() => process.exit(0))
        .catch(() => process.exit(1));
    };

    const sigtermListener = () => {
      console.log('Received SIGTERM, cleaning up resources...');
      this.cleanup()
        .then(() => process.exit(0))
        .catch(() => process.exit(1));
    };

    // Store listeners for later removal
    this.eventListeners.set('exit', exitListener);
    this.eventListeners.set('SIGINT', sigintListener);
    this.eventListeners.set('SIGTERM', sigtermListener);

    // Add listeners to process
    process.on('exit', exitListener);
    process.on('SIGINT', sigintListener);
    process.on('SIGTERM', sigtermListener);

    // Periodic resource monitoring
    this.resourceCheckInterval = setInterval(() => {
      const { withinLimits, violations } = this.checkLimits();
      if (!withinLimits) {
        console.warn('Resource limits exceeded:', violations);
      }
    }, 30000); // Check every 30 seconds
  }

  /**
   * Clean up active processes
   */
  private async cleanupProcesses(): Promise<void> {
    const activeProcesses = Array.from(this.activeProcesses.keys());

    for (const pid of activeProcesses) {
      try {
        // Attempt graceful termination
        process.kill(pid, 'SIGTERM');

        // Wait briefly for graceful shutdown
        await new Promise(resolve => setTimeout(resolve, 1000));

        // Force kill if still running
        try {
          process.kill(pid, 'SIGKILL');
        } catch {
          // Process already terminated
        }

        this.unregisterProcess(pid, 'terminated');
      } catch (error) {
        // Process might already be terminated
        this.unregisterProcess(pid, 'terminated');
      }
    }
  }

  /**
   * Clean up temporary files
   */
  private cleanupTempFiles(): void {
    const fs = require('fs');

    for (const filePath of this.tempFiles) {
      try {
        if (fs.existsSync(filePath)) {
          fs.rmSync(filePath, { recursive: true, force: true });
        }
        this.unregisterTempFile(filePath);
      } catch (error) {
        console.warn(`Failed to clean up temp file ${filePath}:`, error);
      }
    }
  }
}

/**
 * Global resource manager instance
 */
let globalResourceManager: ResourceManager | null = null;

/**
 * Get or create the global resource manager
 */
export function getResourceManager(limits?: ResourceLimits): ResourceManager {
  if (!globalResourceManager) {
    globalResourceManager = new ResourceManager(limits);
  }
  return globalResourceManager;
}

/**
 * Create a new resource manager with specific limits
 */
export function createResourceManager(limits: ResourceLimits): ResourceManager {
  return new ResourceManager(limits);
}

/**
 * Reset the global resource manager instance (mainly for testing)
 */
export function resetGlobalResourceManager(): void {
  if (globalResourceManager) {
    globalResourceManager.cleanup();
    globalResourceManager = null;
  }
}
