name: Publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: uv sync --locked

      - run: make qa

      - run: uv build

      - run: uv publish
